Step3 양방향을 단방향
next-step/jwp-refactoring pull request #100
Opened 2021-01-27 14:26 UTC by himj131

안녕하세요 현구님, step3 리뷰요청 드립니다  :) 

이번 미션에서는
양쪽에서 서로의 정보를 모두 알 필요가 없다고 생각되는 부분에서
양방향을 단방향으로 바꿔 봤습니다.

그리고 2단계에서 놓쳤던 서비스에 있는 일부 도메인 로직을 도메인 내부로 옮겨봤습니다.
리뷰 잘 부탁드립니다 😃

2021-01-27 23:46 UTC, kang-hyungu requested changes
미진님 구현하신 코드 확인했습니다
조금더 개선해보면 좋을 부분에 피드백 남겼어요
적용해보시면서 궁금한 점 생기면 dm주시거나 코멘트 남겨주세요

2021-01-27 23:46 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        save.addProducts(getMenuProducts(request.getMenuProducts()));
addProducts 메서드는 setter랑 어떤 차이가 있나요?
처음부터 메뉴 객체를 생성할 때 MenuProducts 객체를 전달하도록 만들면 이 메서드가 필요 없지 않을까요?

```java
        List<MenuProduct> menuProducts = getMenuProducts(request.getMenuProducts());
        Menu save = menuRepository.save(request.toMenuEntity(menuProducts));
```

2021-01-27 23:46 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    public Long getMenuId() {
primitive type으로 반환하게 만들면 클라이언트에서 null에 대한 처리를 안해도 되겠쬬

2021-01-27 23:46 UTC, kang-hyungu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        if (CollectionUtils.isEmpty(orderLineItems)) {
유효성 체크를 하는 if절들을 메서드 하나로 묶으면 좀더 읽기 좋지 않을까요?

2021-01-27 23:46 UTC, kang-hyungu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        savedOrder.addItems(items);
addItems 메서드도 setter랑 크게 달라보이지 않네요
이 메서드를 제거해보면 어떨까요

2021-01-27 23:46 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/domain/MenuProducts.java
>  public class MenuProducts {
도메인 객체에 setter가 많이 보이네요
객체지향 생활체조 규칙9 게터, 세터, 프로퍼티를 쓰지 않는다를 참고해서 모든 도메인 클래스에서 setter를 제거해보아요

2021-01-27 23:46 UTC, kang-hyungu commented on src/main/java/kitchenpos/table/application/TableGroupService.java
>      public void ungroup(final Long tableGroupId) {
이 메서드가 올바르게 동작하는게 맞나요?
1. TableGroupService인데 OrderTable에 대한 처리만 하고 있고
2. 스샷을 보시면 ungroup을 해도 TableGroup은 OrderTable 객체를 가지고 있습니다.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/15669435/106068624-2e74a980-6144-11eb-9f12-58e0431fb30a.png">

2021-01-27 23:46 UTC, kang-hyungu commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +    private Long tableGroupId;
tableGroupId를 가지고 있으면 간접적으로 양방향 관계를 유지하게 되는거 아닐까요?

2021-01-28 13:42 UTC, himj131 commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +    private Long tableGroupId;
TableGroup 객체를 가지면서  모든 필드에 접근할 수 있는 대신 tableGrouptId로 바꾸면 
TableGroupRepository 통해 TableGroup에 접근하기 때문에 방향성이 단일로 흘러 간다고 생각 했는데, 
현구님 말씀대로 간접적인 양방향인 것 같네요. 
제가 과제를 잘못 이해했나봐요.
order, menu 포함 이 부분 다시 수정해서 리뷰 요청 드릴게요~

2021-01-28 13:42 UTC, himj131 commented on src/main/java/kitchenpos/table/application/TableGroupService.java
>      public void ungroup(final Long tableGroupId) {
이 부분 살펴보고 정정하겠습니다.

2021-01-28 13:43 UTC, himj131 commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    public Long getMenuId() {
습관적으로 자꾸 래퍼클래스를 쓰게되네요 ㅠ 수정할게요.

2021-01-28 13:46 UTC, himj131 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        save.addProducts(getMenuProducts(request.getMenuProducts()));
음 이부분은 이전 단계부터 고칠 생각을 못했을까요... 피드백 감사합니다 :)

2021-01-29 05:42 UTC, himj131 commented
안녕하세요 현구님, 
해당 step 리뷰 재요청 드립니다~
orderTable과  tablegroup은 간접적으로 양방향 관계이지만
테이블을 변경할때 테이블 그룹에 속해있는지 여부를 판단하고, 테이블 그룹을 변경할때 테이블 상태를 확인하기도 해서
양방향이 유지 되는편이 좋을 것 같아, 그룹을 해제하는 서비스 코드만 수정했습니다. 
확인부탁드립니다 :)

2021-01-30 04:50 UTC, kang-hyungu approved these changes
미진님 피드백 반영 잘 하셨어요 👍 
pr은 머지 처리하겠습니다. 수고하셨습니다

2021-01-30 04:50 UTC, merged