Step1 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #154
Opened 2021-07-04 03:07 UTC by DoLiLu

안녕하세요 

레거시 코드 리팩토링 Step1 - 테스트를 통한 코드 보호

리뷰 요청 합니다.

앞으로 레거시 코드 리팩토링 미션 리뷰 잘 부탁드립니다 !

감사합니다.

2021-07-04 11:10 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-07-04 11:10 UTC, kyucumber commented on README.md
> +    * 이미 계산 완료 된 주문의 상태는 변경 불가능 하다.
주문은 어떤 주문 상태를 가질 수 있는지, 초기의 상태는 무엇인지 등에 대해서도 정리되면 좋을 것 같네요~

2021-07-04 11:10 UTC, kyucumber commented on src/main/resources/db/migration/V2__Insert_default_data.sql
> +INSERT INTO order_table (id, number_of_guests, empty) VALUES (4, 0, false);
3,4번은 주문 관련 데이터가 스키마 상에는 없는 것으로 보이는데 empty가 true여야 하지 않을까요?

2021-07-04 11:10 UTC, kyucumber commented on src/test/java/kitchenpos/common/ControllerTest.java
> +public class ControllerTest {
컨트롤러 부분까지도 테스트를 꼼꼼하게 잘 작성해주셨네요 👍

2021-07-04 11:10 UTC, kyucumber commented on src/main/java/kitchenpos/application/TableGroupService.java
> +            if (savedOrderTable.isEmpty() || Objects.nonNull(savedOrderTable.getTableGroupId())) {
요건 저도 헷갈리는데.. 🤔  아래쪽에 요런 코드가 있습니다.

```java
savedOrderTable.setEmpty(false);
```

테이블 그룹으로 지정되면 묶인 테이블들의 empty 값이 false로 바뀌는 것 같아요.
그렇다면 이미 false인 경우에 예외를 반환하려고 하는(`!savedOrderTable.isEmpty()`) 원래 의도가 맞는게 아닐까 싶은 생각이 드네요.

2021-07-04 11:10 UTC, kyucumber commented on src/test/java/kitchenpos/table/service/TableGroupServiceTest.java
> +public class TableGroupServiceTest {
테이블 그룹 지정 시 지정한 테이블에 이미 테이블 그룹이 있는 경우는 예외가 발생하지 않나요?

예외 케이스에 대해서도 테스트를 작성해주시면 어떨까요?

- [ ] 이미 그룹으로 묶인 테이블을 그룹 지정 시 예외가 발생한다.
- [ ] 데이터베이스에 저장된 테이블과 실제 묶으려는 테이블 개수가 맞지 않으면 예외가 발생한다.

2021-07-04 11:10 UTC, kyucumber commented on src/test/java/kitchenpos/order/service/OrderServiceTest.java
> +    @DisplayName("주문 상태를 변경한다")
요구사항에 남겨주셨던데, 아래 부분도 테스트를 작성해주시면 어떨까요?

- [ ] 이미 계산 완료 된 주문의 상태는 변경 불가능하다.

2021-07-04 21:06 UTC, DoLiLu commented on src/main/resources/db/migration/V2__Insert_default_data.sql
> +INSERT INTO order_table (id, number_of_guests, empty) VALUES (4, 0, false);
주문 테스트 코드 작성을 위하여 false 로 변경 하였는데,
3번은 주문 테스트를 작성하기 위한 초기 데이터로 false로 사용 하고
4번의 경우 말씀하신대로 사용하지 않아서 true로 변경 하였습니다.

2021-07-04 21:06 UTC, DoLiLu commented on README.md
> +    * 이미 계산 완료 된 주문의 상태는 변경 불가능 하다.
상태 순서 추가 하였습니다.

2021-07-04 21:07 UTC, DoLiLu commented on src/main/java/kitchenpos/application/TableGroupService.java
> +            if (savedOrderTable.isEmpty() || Objects.nonNull(savedOrderTable.getTableGroupId())) {
말씀 해주신 부분이 맞는거 같아서 다시 원래대로 변경 및 테스트 코드 수정 하였습니다.

2021-07-04 21:22 UTC, DoLiLu commented on src/test/java/kitchenpos/table/service/TableGroupServiceTest.java
> +public class TableGroupServiceTest {
테이블 그룹 관련 예외 테스트 추가 하였습니다.

2021-07-04 21:28 UTC, DoLiLu commented on src/test/java/kitchenpos/order/service/OrderServiceTest.java
> +    @DisplayName("주문 상태를 변경한다")
계산 완료 된 주문 상태 변경 예외 테스트 추가 하였습니다.

2021-07-05 02:51 UTC, kyucumber approved these changes
피드백 잘 반영해주셨네요

다음 단계 진행을 위해서 머지하겠습니다.

2021-07-05 02:51 UTC, merged