🚀 1단계 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #183
Opened 2021-07-07 18:39 UTC by fDevJc

안녕하세요 리뷰어님!

작성해야되는 테스트양이 엄청많네요 😭
작성하면서 제대로 하는게 맞는지 싶네용
Mock객체를 이용해 제가 원하는 방향으로 움직이는 코드가 테스트가 되는지 모르겠습니다.
1단계 제목처럼 코드를 보호할 수 있나? 라는 생각을 하게 되었습니다.
제가 잘못만든건지 😅 아니면 과제를 진행하면서 아하 하는부분이 있을지 궁금하네요
많은 피드백 부탁드리겠습니다.
감사합니다.

2021-07-08 13:58 UTC, young891221 requested changes
안녕하세요, 지철님!
우선 미션 진행 착실히 잘 해주셨네요 👍 
추가적으로 전체적인 테스트 관점에서 의견 하나 드렸습니다. 확인 부탁드립니다.

2021-07-08 13:58 UTC, young891221 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +@ExtendWith(MockitoExtension.class)
Mock을 이용한 전체적인 테스트를 잘 작성해 주셨는데요. 다만, Mock만으로 모든 테스트를 커버하기에는 불가능에 가깝습니다. Mock의 이용 용도는 주로 실행하기 까다로운 빈의 실행 해결 or 원하는 input/output의 빠른 테스트 등에 있다고 생각합니다.
실제로 리펙토링을 하려고 했을 때 코드를 보호하려고 한다면 어떤 예외가 터질지 예측하기 힘듭니다. 때문에, 미션 설명에도 언급되어 있는 부분이지만 `@SpringBootTest`을 활용한 전체 테스트도 추가가 꼭 필요합니다. 예를 들어, 디비에서 락이 걸린다던지, 컨넥션이 끊긴다는지, 슬로우 쿼리 등 디비만으로도 다양한 예외가 발생할 수 있는데 Mock처리를 한다면 모두 통과가 될 것이기 때문입니다.
추가적으로 `@SpringBootTest`을 활용한 기능 테스트 + 예외 테스트도 작성 부탁드립니다ㅎ

2021-07-08 14:50 UTC, fDevJc commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +@ExtendWith(MockitoExtension.class)
피드백 감사합니다!!
이번 코스를 통해 처음 테스트코드들을 작성해보아서
피드백에서 말씀해주신 전체 테스트란
앞선 과제들에서 진행했던 인수테스트 처럼
request, response 를 활용하여 controller -> service -> repository
전체 사이클을 테스트를 진행해보아야 한다? 라고 이해하고 작성하면 될까요??

2021-07-08 18:02 UTC, fDevJc commented on src/test/java/kitchenpos/ui/OrderRestControllerTest.java
> +
피드백으로 주신 `@SpringBootTest`를 이용한 전체 테스트를 작성하던 중
이게맞나...😭 싶어서 피드백을 받고 싶어 PR을 보내게되었습니다.
`@SpringBootTest`를 이용한 전체사이클 테스트의 장단점이나 필요성은 이해가 되나 어떻게 작성해야할지 막막하네요.

위와 같이 `주문`에 필요한 `테이블` , `메뉴` 등의 데이터를 어떻게 처리를 해야되는지 궁금합니다.
`MockMvc`를 사용하는 것이 맞는지..
아니면 인수테스트 과제에서 이용했던 `RestAssured`를 이용하여 테스트를 진행하는것이 맞는지 모르겠네요
`RestAssured`를 이용하여 작성한다면 이전과제에서 작성했던 인수테스트와 차이가 없는건가요??
그리고 위에서 `@SpringBootTest`를 이용한 전체 테스트는 `통합테스트`라고 생각하면 되는걸까요?

업무에서 테스트를 진행안했다보니 XX테스트에 이해도가 많이 부족한거 같네요 ㅠ

2021-07-09 11:10 UTC, young891221 commented on src/test/java/kitchenpos/ui/OrderRestControllerTest.java
> +
화이트박스 테스트로 input,output을 테스트한다는 개념에서 RestAssured도 좋습니다. @SpringBootTest는 좀 더 확장적으로 쓸 수 있지만 RestAssured와 마찬가지로 컨트롤러부분을 테스트하여 input,output을 테스트할 수 있습니다.
말씀하신 인수테스트, 통합테스트, 전체테스트 모두 비슷한 개념이라고 생각합니다. 인입점과 그 결과를 측정하는 전체적인 테스트가 모두 되는 형태가 맞습니다.

2021-07-09 11:12 UTC, young891221 commented on src/test/java/kitchenpos/ui/OrderRestControllerTest.java
> +
위의 커밋된 부분을 보았는데 RestAssured를 통한 테스트나 @SpringBootTest를 통한 컨트롤러 테스트로 작성해 주시면 될 것 같습니다. webmvctest는 의존성이 컨트롤러만 가져오는 형태라서요.

2021-07-09 11:12 UTC, young891221 requested changes
제가 질문에 대한 답변을 좀 늦게 드리는것 같아 죄송하네요 ㅠㅠ
코멘트 답변 확인 부탁드립니다!

2021-07-10 08:51 UTC, young891221 approved these changes
피드백 반영하시느라 고생 많으셨습니다 👍 
머지할게요. 다음 단계 진행해 주세요!

2021-07-10 08:51 UTC, merged