Step2 service refactoring
next-step/jwp-refactoring pull request #240
Opened 2021-07-15 06:52 UTC by mwkwon

리뷰어님 안녕하세요~^^
오랜만에 리뷰 요청 드리는거 같네요..ㅠㅠ
이번 미션 단계의 경우 지금까지 했던 미션중에 가장 힘들었던거같아요..ㅠㅠ
그럼 리뷰 잘 부탁 드립니다~~~~~~~~~^^
감사합니다^^

2021-07-16 02:20 UTC, kang-hyungu requested changes
안녕하세요 민욱님
몇 가지 피드백 남겼습니다.
수정해보시고 리뷰 재요청주세요.

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/enums/OrderStatus.java
> +package kitchenpos.enums;
enums 패키지가 따로 필요할까요?
enum도 도메인별로 분류하는게 좋지 않을까요?

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/exception/ProductException.java
> +public class ProductException extends IllegalArgumentException {
IllegalArgumentException를 상속하는게 맞나요?
모든 상품 예외가 IllegalArgument만 있을까요?

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/product/domain/Products.java
> +    public BigDecimal calcProductsPrice(List<MenuProductRequest> menuProductRequests) {
도메인 클래스에서 dto를 사용하면 안됩니다.

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/product/domain/Products.java
> +    public void checkProductsSize(int size) {
이 메서드가 의미가 있을까요?
size 값으로 menuRequest.getMenuProducts().size()만 전달하도록 강제 할 수 있는게 아닌데 Product size를 체크한다고 할 수 있을까요?

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public List<MenuResponse> list() {
트랜잭션을 readOnly로 설정해보면 어떨까요?
다른 서비스의 메서드들도 점검해보아요

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public Menu() {
```suggestion
    protected Menu() {
```

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public Menu(Long id, String name, BigDecimal price, Long menuGroupId) {
생성자 중복을 제거하기 위해 this 생성자를 활용해보아요

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +    private Long tableGroupId;
2단계 미션에서 간접참조로 바꿀 필요가 있을까요?

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +public class TableGroup {
테이블 그룹이라는 객체가 맡은 역할은 무엇인가요?
id와 createdDate 값만 있으면 테이블 그룹이 맡은 일을 잘 처리할 수 있을까요?

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/table/ui/TableRestController.java
> +    @PostMapping("/api/tables")
`/api/tables`가 반복적으로 나오네요
`@RequestMapping` 을 활용해서 중복을 제거해보아요

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public MenuResponse create(final MenuRequest menuRequest) {
객체 지향적으로 작성해보면 어떨까요?
간접 참조는 지금 단계에서는 진행하지 않는게 좋겠네요.

```java
    public MenuResponse create(final MenuRequest menuRequest) {
        // 유효성 검증을 먼저 수행한다
        checkExistsMenuGroup(menuRequest.getMenuGroupId());
        checkProductsSize(menuRequest.getMenuProducts());

        // 메뉴 객체를 생성하기 위해 필요한 객체를 조회한다
        ...

        // 메뉴 객체 생성에 필요한 request 값과 조회한 객체들을 메뉴 생성자로 전달한다.
        // Menu 생성자에서 MenuProduct 객체를 만든다.
        ...

        // 저장
        final Menu savedMenu = menuRepository.save(menu);

        // Menu는 MenuProducts를 인스턴스 변수로 가지고 있다.
        // 객체 관계를 최대한 활용한다.
        return MenuResponse.of(savedMenu);
    }
```

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/table/application/TableService.java
> +    public void checkValidOrderStatusCompletion(List<Long> orderTableIds) {
이미 orderTable 객체를 조회했는데 또 쿼리로 조회할 필요는 없어보입니다.
이 메서드는 제거하시고 OrderTable 객체에서 처리하도록 바꿔보세요.

2021-07-16 02:20 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public MenuResponse create(final MenuRequest menuRequest) {
다른 서비스들도 점검해보아요

2021-07-16 03:56 UTC, mwkwon commented on src/main/java/kitchenpos/enums/OrderStatus.java
> +package kitchenpos.enums;
수정 하였습니다~! 감사합니다^^

2021-07-16 03:57 UTC, mwkwon commented on src/main/java/kitchenpos/exception/ProductException.java
> +public class ProductException extends IllegalArgumentException {
RuntimeException으로 수정 완료하였습니다.!
감사합니다~^^

2021-07-16 03:57 UTC, mwkwon commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public List<MenuResponse> list() {
수정 완료하였습니다.
다 설정햇다고 생각햇는데 빠드렷네요..ㅠㅠ
감사합니다.^^

2021-07-16 03:57 UTC, mwkwon commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public Menu() {
수정 완료하였습니다~
감사합니다^^

2021-07-16 03:58 UTC, mwkwon commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public Menu(Long id, String name, BigDecimal price, Long menuGroupId) {
수정 완료하였습니다~
감사합니다^^

2021-07-16 04:14 UTC, mwkwon commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +    private Long tableGroupId;
수정 완료하였습니다.
감사합니다~^^

2021-07-16 04:25 UTC, mwkwon commented on src/main/java/kitchenpos/table/ui/TableRestController.java
> +    @PostMapping("/api/tables")
수정 하였습니다.
감사합니다~^^

2021-07-16 05:55 UTC, mwkwon commented on src/main/java/kitchenpos/table/application/TableService.java
> +    public void checkValidOrderStatusCompletion(List<Long> orderTableIds) {
수정 하였습니다.
감사합니다~^^

2021-07-16 05:55 UTC, mwkwon commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +public class TableGroup {
수정하였습니다.
감사합니다~^^

2021-07-17 01:02 UTC, kang-hyungu approved these changes
민욱님 피드백 반영 잘 해주셨네요.
추가로 남긴 피드백은 다음 단계 진행하면서 적용해주세요

2021-07-17 01:02 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +    public BigDecimal calcProductsPrice(Products products) {
dto가 너무 많은 일을 하고 있습니다.
다른 객체에서 처리하는게 좋겠네요

2021-07-17 01:02 UTC, kang-hyungu commented on src/main/java/kitchenpos/product/domain/Products.java
> +    public List<Product> getProducts() {
dto에서 필요한 값만 도메인 객체로 전달해서 계산하는게 어떨까요?

2021-07-17 01:02 UTC, merged