Step1 : 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #286
Opened 2021-12-09 22:06 UTC by tyranotyrano

안녕하세요😊 7주차 레거시 코드 리팩터링 미션 진행자 최영진입니다.
1단계 테스트를 통한 코드 보호 미션 리뷰 요청 드리겠습니다!
1단계 진행 중 궁금한 내용은 아래에 정리하였습니다.

Q1. 기능 요구사항을 작성할 때, Service 를 기준으로 작성하였습니다. 그리고 작성된 요구사항을 기준으로 Service 계층의 테스트 코드를 작성하였는데 1단계 미션은 우선 테스트 코드로 기존 로직을 보호하는 것이라고 생각해 리팩토링 요소가 보여도 우선 리팩토링을 진행하지 않고 테스트 코드를 작성하였습니다. 2단계에서 대부분의 리팩토링이 진행될 것 같은데, 실제 실무에서 레거시 코드를 리팩토링 할 때도 테스트 코드를 먼저 작성하고 리팩토링을 진행하는게 좋을까요? 추후 리팩토링 진행 시, setter 등을 제거할 때 테스트 코드도 같이 수정해야되는 상황이 된거 같아 리팩토링 대상에 테스트 코드도 포함된 것 같습니다.

2021-12-10 16:50 UTC, leeyohan93 requested changes
안녕하세요 영진님 ! 레거시 코드 리팩터링 미션 리뷰를 맡게된 이요한입니다 😄
테스트를 통한 코드 보호 구현을 잘해주셨네요. 👍
몇가지 코멘트를 남겨드렸으니 확인 부탁드릴게요 !
앞으로 미션간 잘 부탁드립니다 🙏

2021-12-10 16:50 UTC, leeyohan93 commented on README.md
>  ## 요구 사항
> Q1. 기능 요구사항을 작성할 때, Service 를 기준으로 작성하였습니다. 그리고 작성된 요구사항을 기준으로 Service 계층의 테스트 코드를 작성하였는데 1단계 미션은 우선 테스트 코드로 기존 로직을 보호하는 것이라고 생각해 리팩토링 요소가 보여도 우선 리팩토링을 진행하지 않고 테스트 코드를 작성하였습니다. 2단계에서 대부분의 리팩토링이 진행될 것 같은데, 실제 실무에서 레거시 코드를 리팩토링 할 때도 테스트 코드를 먼저 작성하고 리팩토링을 진행하는게 좋을까요? 추후 리팩토링 진행 시, setter 등을 제거할 때 테스트 코드도 같이 수정해야되는 상황이 된거 같아 리팩토링 대상에 테스트 코드도 포함된 것 같습니다.

저는 실무에서도 레거시 코드를 리팩토링할 때 테스트 코드를 먼저 필수적으로 작성해야한다고 생각합니다 😄 
테스트 없이 리팩토링을 진행하게 되면, 이전 코드와 동일한 동작을 한다는 보장을 받을 수 없습니다.
따라서 테스트를 먼저 작성하고 검증한 뒤에, 리팩토링을 통해 테스트와 함께 변경해나가야 한다고 생각합니다 :)

개인적으로 좀 더 생각해보면 레거시 코드에 테스트를 짜면서 리팩토링 될 테스트는 완전히 새로운 것은 아니라고 생각합니다.
왜냐하면 데이터를 준비하는 given절과 when절은 바뀌더라도 then절, 검증부는 바뀌지 않고 유지할 수도 있기 때문인데요 :)
물론 검증부 또한 바뀌어야 하는 경우가 있을 수 있습니다. 하지만 바뀌지 않는 경우가 대다수라고 생각하며 리팩토링 전과 후에 검증부의 변경이 없도록 비즈니스 로직이 담긴 도메인 코드는 사용하지 않고 하드코딩으로 작성하는 것을 권장합니다 :)
관련된 좋은 글이 있는데 함께 참고해주시면 좋을 것 같아요 :)

https://jojoldu.tistory.com/615

2021-12-10 16:50 UTC, leeyohan93 commented on README.md
> +- [x] 메뉴를 등록 할 수 있다.
상품이 없어도 메뉴를 생성할 수 있을까요?

2021-12-10 16:50 UTC, leeyohan93 commented on README.md
> +    - [x] 상품 가격은 존재하지 않거나(null) 이거나 음수(0원 미만) 일 수 없다.
사소하지만, 이렇게도 표현해볼 수도 있을 것 같아요 :)
개인적인 취향이니 참고만 부탁드릴게요 🙏 
```suggestion
    - [x] 상품 가격은 필수 정보이며 0원 이상이어야 한다.
```

2021-12-10 16:50 UTC, leeyohan93 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +@MockitoSettings(strictness = Strictness.LENIENT)
`strictness = Strictness.LENIENT`를 통해 불필요한 스터빙에서 발생하는 예외를 침묵시켜주셨네요 !
개인적으로 생각하기에는 각 테스트는 꼭 필요한 스터빙을 수행해야한다고 생각합니다.
그 이유는 어떤 스터빙이 해당 테스트에 필요한지 명확하지 않으면, 테스트를 읽게 되는 개발자는 어떤 스터빙된 코드를 사용하는지 도메인 코드의 내부 구현을 상세하게 들여다보아야 하기 때문입니다. 각 테스트가 명확한 스터빙을 가질 수 있도록 개선해보시는건 어떨까요 😄 

관련되어서 참고해보시면 좋은 링크도 남겨놓을게요  :)
https://jojoldu.tistory.com/611

2021-12-10 16:50 UTC, leeyohan93 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        when(menuDao.countByIdIn(Arrays.asList(불고기.getId()))).thenReturn(1L);
BDD(Behavior Driven Development) 스타일의 테스트 작성방법은 테스트 메소드에 기본으로 //given //when //then 이라고 주석을 달아두는 것인데요.

이에 따르면 when을 이용한 stubbing은 given when then 기법에 잘 맞아떨어지지 않습니다. 
왜냐하면 stubbing이 when이 아닌 given에 속하기 때문이에요.

그러므로 BDDMockito 클래스는 stub을 할 때 사용할 메소드로 BDDMockito.given(Object)를 제공하고 있는데요. 
이 method를 이용해 아래와 같이 BDD 스타일의 테스트를 만드는 방법도 있습니다 :)
참고만 부탁드릴게요 😄 

```
given(menuDao.countByIdIn(Arrays.asList(불고기.getId()))).willReturn(1L)

```

2021-12-10 16:50 UTC, leeyohan93 commented on src/test/java/kitchenpos/application/fixture/MenuFixture.java
> +public class MenuFixture {
테스트 픽스쳐를 만들어주셨네요 💯

2021-12-10 16:50 UTC, leeyohan93 commented on src/test/java/kitchenpos/application/fixture/MenuFixture.java
> +    public static Menu 불고기 = new Menu();
테스트 픽스쳐 객체를 static으로 설정해두면 하나의 테스트에서 이 상태를 변경한다고 가정했을때, 이 객체를 참조하는 모든 테스트가 영향을 받게 될 것 같은데요! 상태를 공유하지 않도록 개선해보면 어떨까요 :)

2021-12-11 02:26 UTC, tyranotyrano commented on README.md
> +- [x] 메뉴를 등록 할 수 있다.
메뉴를 구성하는 상품이 없으면 IllegalArgumentException 이 발생하게되고, README.md 에 **[x] 메뉴는 메뉴를 구성하는 상품이 존재하지 않으면 등록 할 수 없다.** 라는 내용으로 작성해 두었습니다. MenuServiceTest create5() 메소드에도 해당 테스트 코드를 구현하였습니다. 혹시 이 케이스 말고 다른 케이스가 존재하는 걸까요?

2021-12-11 02:27 UTC, tyranotyrano commented on README.md
> +    - [x] 상품 가격은 존재하지 않거나(null) 이거나 음수(0원 미만) 일 수 없다.
기능 요구사항에 개발적인 표현이나 요소가 들어가면 다른 분들이 이해하시는데 방해가 될 수 있으니 일반적인 용어로 바꾸는게 좋은 것 같습니다! 피드백 참고해서 수정해놓겠습니다! 감사합니다!

2021-12-11 02:30 UTC, tyranotyrano commented on src/test/java/kitchenpos/application/fixture/MenuFixture.java
> +    public static Menu 불고기 = new Menu();
피드백 감사합니다! 테스트의 독립성을 보장하기 위해 픽스처를 사용할 때는 테스트마다 새로운 픽스처를 생성하는 것이 더 맞는 방법인 것 같습니다. 픽스처 개선해서 다시 피드백 요청드리겠습니다! 감사합니다!👍

2021-12-11 03:37 UTC, tyranotyrano commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        when(menuDao.countByIdIn(Arrays.asList(불고기.getId()))).thenReturn(1L);
Mockito 를 사용하는 것이 익숙치 않아서 사용할 때 고민이 많이 되었는데, 명확하게 피드백 주셔서 감사합니다.
개인적으로 given, when, then 패턴을 좋아하는데 Mockito 로 Subbing 방식을 적용할때도 이 패턴을 지키면서 작성해야겠네요! 피드백 참고해서 수정하고 다시 피드백 요청드리겠습니다! 감사합니다!

2021-12-11 03:45 UTC, tyranotyrano commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +@MockitoSettings(strictness = Strictness.LENIENT)
테스트에 필요한 Mockito 처리를 한번에 setUp() 에서 처리하면 편할 것 같았는데, 피드백에 대해 생각해보니 테스트에 꼭 필요한 내용은 테스트안에서만 사용하도록 제한하고, 공통적인 요소 처리만 setUp() 에서 처리하는 게 좋을 것 같에요! 피드백 감사합니다! 수정해서 다시 피드백 요청드리겠습니다!

2021-12-11 20:21 UTC, leeyohan93 commented on README.md
> +- [x] 메뉴를 등록 할 수 있다.
이미 작성되었던 케이스이군요 ! 제가 놓친 케이스 같습니다 :)
확인 감사합니다 🙏

2021-12-11 20:24 UTC, leeyohan93 approved these changes
피드백 반영을 잘 해주셨네요 ! 👍 
이번 단계는 여기서 머지하도록 하겠습니다 :)
다음 단계도 화이팅해주세요 🔥

2021-12-11 20:24 UTC, merged