Step3 : 의존성 리팩터링
next-step/jwp-refactoring pull request #301
Opened 2021-12-16 19:22 UTC by tyranotyrano

안녕하세요😊 7주차 레거시 코드 리팩터링 미션 진행자 최영진입니다.
3단계 의존성 리팩터링 미션 리뷰 요청 드리겠습니다!
3단계 진행 중 궁금한 내용은 아래에 정리하였습니다.

---

Q.1 이번 미션을 진행하면서 도메인 Validator 를 외부 클래스로 추출하여 처리하였습니다. 이렇게 처리를 하고 나니, 도메인 객체를 생성하는 모든 곳에 Validator 의 유효성 검증 메소드를 호출해야하는 방식으로 바뀌었는데, 다른 개발자가 이런 개발 이력을 모르고 실수로 Validator 를 호출하지 않는다면 문제가 생기지 않을까요? 그리고 도메인 테스트 코드 작성 시에도 매번 Validator 의 유효성 검증 메소드를 호출해야하는데 이 방식이 효율적인지 잘 공감하기 어려운 것 같습니다. 이를 해결하기위해 도메인 생성을 위한 정적 팩토리 메소드를 두어 매개변수로 Validator 를 넣는 방법을 생각해 보았는데 이방법이 적절한지 잘 모르겠습니다. 혹시 이 문제에대해 어떻게 생각하시나요??

Q2. Validator 를 @Component Bean 으로 만들면서, 기존 ServiceTest 를 Mock 테스트에서 DataJpaTest 로 변경하였습니다. 아무래도 DataJpaTest 를 사용하니 성능면에서 다소 느린것을 체감할 수 있었는데 이부분을 개선할 수 있는 방법이 있을까요?

2021-12-17 14:28 UTC, leeyohan93 requested changes
3단계 미션도 잘 구현해주셨네요 👍 
질문에 대한 답변과 몇가지 코멘트를 남겨드렸으니 확인 부탁드릴게요 :)
좋은 주말 보내세요 🙏

2021-12-17 14:28 UTC, leeyohan93 commented on README.md
> +# 3단계 : 의존성 리팩토링
>Q.1 이번 미션을 진행하면서 도메인 Validator 를 외부 클래스로 추출하여 처리하였습니다. 이렇게 처리를 하고 나니, 도메인 객체를 생성하는 모든 곳에 Validator 의 유효성 검증 메소드를 호출해야하는 방식으로 바뀌었는데, 다른 개발자가 이런 개발 이력을 모르고 실수로 Validator 를 호출하지 않는다면 문제가 생기지 않을까요? 그리고 도메인 테스트 코드 작성 시에도 매번 Validator 의 유효성 검증 메소드를 호출해야하는데 이 방식이 효율적인지 잘 공감하기 어려운 것 같습니다. 이를 해결하기위해 도메인 생성을 위한 정적 팩토리 메소드를 두어 매개변수로 Validator 를 넣는 방법을 생각해 보았는데 이방법이 적절한지 잘 모르겠습니다. 혹시 이 문제에대해 어떻게 생각하시나요??

개인적으로 Validator를 통해 도메인에 대한 검증을 모으는 부분은 트레이드오프의 영역에 있다고 생각합니다.
말씀하신대로 Validator를 통해 호출해야한다는 공유가 이루어지지 않으면 협업에 문제가 생길 수 있지요.

다만 검증에 대한 책임을 모두 도메인 객체에 배치한다고 하면 도메인 객체의 응집도는 낮아 질 수 있습니다.
하나의 도매인 객체에서 비즈니스 로직과 검증 로직이 섞여있는 것이지요. 

실무를 하다보면 외부 API를 통한 검증과 같은 복잡한 검증 로직이 생기거나, 검증이 여러가지를 처리하기 때문에 검증을 하나의 클래스에 모으면서 어떠한 검증을 하는지 한눈에 알아보기 쉽도록하고, 도메인 객체의 응집도를 높여주는 것이 개인적으로는 더 좋았던 부분이 있었던 것 같습니다 :) 

추가적으로 개발 이력에 대한 부분은 팀 내 어느 누군가가 코드를 짜더라도 일관된 코드가 짜여져야 한다고 생각하기 때문에 팀 차원에서 풀어갈 수 있지 않을까 생각해봅니다 😄

2021-12-17 14:28 UTC, leeyohan93 commented on src/test/java/kitchenpos/domain/menu/MenuProductTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = Component.class))
Q2. Validator 를 @component Bean 으로 만들면서, 기존 ServiceTest 를 Mock 테스트에서 DataJpaTest 로 변경하였습니다. 아무래도 DataJpaTest 를 사용하니 성능면에서 다소 느린것을 체감할 수 있었는데 이부분을 개선할 수 있는 방법이 있을까요?

해당 부분에 대한 성능을 개선해보려면 필터를 추가하는 것보다 필요한 빈을 Import로 추가하는 방법도 있을 것 같아요 :)

아래 링크의 내용이 같은 상황은 아니지만 DataJpaTest에 대해 생각해볼 수 있는 포인트가 될 것 같아서 남겨놓을게요 😄 

https://www.inflearn.com/questions/42585

```suggestion
@DataJpaTest
@Import(value = MenuValidator.class)
```

2021-12-17 14:28 UTC, leeyohan93 commented on src/main/java/kitchenpos/exception/EmptyNameException.java
> +public class EmptyNameException extends RuntimeException {
커스텀 예외를 만들어주셨네요 !
어떤 기준을 통해 커스텀 예외를 만들어주시는지 궁금합니다 :)

2021-12-17 14:28 UTC, leeyohan93 commented on src/main/java/kitchenpos/application/menu/MenuValidator.java
> +    }
개인적으로 생성자를 제외한 테스트를 위한 로직, 메서드는 지양해야한다고 생각합니다 :)

외부에 제공되는 public 메서드는 항상 신중하게 만들어져야하며, 테스트를 위한 메서드의 추가는 해당 클래스에 대한 사용성과 가독성을 떨어뜨린다고 생각하고 있습니다. 다른 Validator들에도 비슷한 부분들이 있는데요! 함꼐 개선해보면 좋을 것 같습니다 :)

2021-12-17 14:28 UTC, leeyohan93 commented on src/main/java/kitchenpos/application/order/OrderService.java
> +    private final MenuRepository menuRepository;
사용하지 않는 코드와 의존성은 제거해주셔도 좋을 것 같습니다 :)

2021-12-17 14:28 UTC, leeyohan93 commented on src/main/java/kitchenpos/application/tablegroup/TableGroupService.java
> +        tableGroup.group(orderTableIds);
TableGroup에서 이벤트를 발행하여 OrderTable의 상태를 변경하도록 구현해주셨는데 아직 tablegroup 모듈에서는 ordertable을 의존하고 있네요! 아직 tablegroup 패키지과 table 패키지 사이에서 의존성의 사이클이 만들어지고 있는 것 같습니다. 
의존성의 흐름이 한 방향으로 흐르도록 개선해보면 좋을 것 같아요 :)

추가적으로 도메인들의 의존성의 흐름을 직접 그림으로 그려보시는 것이 파악하는데 많은 도움이 될 수 있을 것 같고
우아한 객체지향 영상의 1:38:19 에 나오는 도메인 단위 모듈화를 하는 것도 의존성을 파악하는데 도움이 될 것 같습니다 :)

2021-12-17 15:00 UTC, tyranotyrano commented on src/main/java/kitchenpos/exception/EmptyNameException.java
> +public class EmptyNameException extends RuntimeException {
지난 2단계에서 받은 피드백을 바탕으로 공용적으로 사용되는 도메인을 위주로 먼저 커스텀 예외를 구현해보았습니다.
어떤 기준을 잡고 커스텀 예외를 만들었다기보다는 쉽게 커스텀 예외로 분리해볼 수 있는 것들을 먼저 구현했습니다!

2021-12-17 15:09 UTC, tyranotyrano commented on src/main/java/kitchenpos/application/menu/MenuValidator.java
> +    }
테스트를 위한 생성자에가 도메인 내에 존재하는 경우도 있어서, 테스트를 위한 public 메서드도 큰 고민없이 만들었었습니다. 테스트 전용 public 메서드가 MenuValidator.validateMenuProduct(), OrderValidator.validateOrderLineItem() 이렇게 2개가 있는데, MenuProduct 에 대한 유효성 검증은 MenuValidator.validate() 에서 진행을 같이 하고 있고, OrderLineItem 에 대한 유효성 검증은 OrderValidator.validate() 에서 같이 진행을 하고 있으므로 2개 메소드 모두 제거해도 될 것 같습니다.

다만 추가로 좀더 고민을 해보았는데, 테스트에서 꼭 필요한 부분인데 외부에 public 으로 제공하기 어려운 메서드의 경우에는 test 패키지 내에 기존 Validator 클래스를 상속 or 별도의 TestValidator 를 두어 test 범위 한정으로 사용할 수 있을 것 같습니다! 피드백 감사드립니다!👍

2021-12-17 15:29 UTC, tyranotyrano commented on src/main/java/kitchenpos/application/order/OrderService.java
> +    private final MenuRepository menuRepository;
앗 넵! 제거 하도록 하겠습니다!👍

2021-12-18 12:44 UTC, leeyohan93 approved these changes
피드백을 잘 반영해주셨네요 ! 😄 
소소한 코멘트를 남겨드렸으니 확인부탁드리고 이번 단계는 머지하겠습니다 :)
다음 단계가 벌써 마지막 단계인데요 😄 
멀티 모듈에 관한 부분을 진행하기 이전에 코멘트 드린 부분에 대해 고민해보시면 좋을 것 같아요 🙏 
마지막 단계도 화이팅입낟 🔥

2021-12-18 12:44 UTC, leeyohan93 commented on src/main/java/kitchenpos/application/grouping/OrderTableGroupedEventHandler.java
> +package kitchenpos.application.grouping;
tablegroup 도메인 패키지가 존재하는데, grouping 패키지를 만드는 것은 조금 더 고려해볼 부분 같아요 🤔 
새로운 도메인 패키지를 만들때는 어떠한 도메인이 새로 만들어질 때라고 생각하는데요 !

이전에 드렸던 피드백에서 도메인 단위 모듈화와 함께 고민해보시면 좋을 것 같습니다 !
추가적으로 다음 단계에서는 레이어별로 멀티 모듈을 구성할 수도 있겠지만, 도메인 단위 모듈화를 진행할 수 도 있을 것 같아요.
만약 도메인 단위 모듈화를 진행하게 된다면 추후에 MSA 구조로 활용될 가능성도 있을 수 있겠네요 :)
어떤 식으로 구현해보실지 고민해보시면 좋을 것 같아요 😄 
https://github.com/next-step/jwp-refactoring/pull/301#discussion_r771428191

2021-12-18 12:44 UTC, merged