1단계 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #316
Opened 2021-12-19 04:14 UTC by y2o2u2n

안녕하세요, 리뷰어님 :)

코드와 `.http`, `.sql`을 본 뒤 요구 사항을 작성했고

요구 사항을 인수 테스트로 차례대로 작성해보았습니다.

이번주 미션 잘 부탁드리겠습니다 :)

2021-12-19 13:56 UTC, hhlyn0328 requested changes
안녕하세요 :) 
레거시 코드 리팩토링 리뷰어 홍혜린입니다! 😄 

1단계 테스트를 잘 작성해주셨네요! 
간단한 코멘트 남겨두었는데요 참고하여 추가 작성 후에 재요청 부탁드립니다

이번 미션 잘 부탁드려요 🙇

2021-12-19 13:56 UTC, hhlyn0328 commented on src/test/java/kitchenpos/ApplicationTest.java
> +	void contextLoads() {
`모든 Business Object에 대한 테스트 코드를 작성한다. @SpringBootTest를 이용한 통합 테스트 코드 또는 @ExtendWith(MockitoExtension.class)를 이용한 단위 테스트 코드를 작성한다.`

라는 요구사항에 맞춰, 단위 테스트도 작성 부탁드립니다 🙏

2021-12-19 17:58 UTC, y2o2u2n commented on src/test/java/kitchenpos/ApplicationTest.java
> +	void contextLoads() {
`Mockito`를 이용한 단위 테스트도 작성했습니다 :)
단위 테스트를 작성하니 테스트 픽스처를 관리하기 힘들어지는 것 같은데
아무래도 통합 테스트가 좀 더 편한 부분이 있다고 생각이 드네요...
테스트는 인수 테스트(통합 테스트 환경에서) 그리고 도메인에 대한 단위 테스트 정도면 충분할 것 같다고 생각이 되는데
리뷰어님께서는 서비스 코드에 대한 통합 테스트나 단위 테스트도 추가로 작성하시는지 궁금합니다 :)

2021-12-20 10:13 UTC, hhlyn0328 commented on src/test/java/kitchenpos/ApplicationTest.java
> +	void contextLoads() {
목적에 따라 다를것 같아요 
일반적인 개발을 진행한다면 인수테스트와 도메인 테스트만 작성할텐데요 

이번 미션과 같이 리팩토링을 진행한다면
service의 요청과 응답이, 기존과 동일하게 동작하는지 확인하기 위해 
테스트를 작성하여 보호하는 목적이라서 서비스 코드에 대한 테스트 코드도 작성할 것 같아요!

2021-12-20 10:14 UTC, hhlyn0328 approved these changes
피드백 반영을 잘 해주셨네요 💯 

질문 주셨던 부분에 대해서는 코멘트 남겨두었으니, 확인 부탁드려요!
그럼, 다음 단계 진행을 위해 머지하겠습니다 :)

2021-12-20 10:15 UTC, merged