Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #340
Opened 2021-12-21 16:45 UTC by lsm7179

안녕하세요. 리뷰어님! 😄
1단계 리뷰를 받고 시간이 좀 걸렸네요. 😂
1단계 [피드백답글](https://github.com/next-step/jwp-refactoring/pull/303#pullrequestreview-835744445) 달았습니다. 참고 부탁드립니다.~
이번 미션 진행하면서
"jdbc 사용하니 jpa로 바꿔야지 dto를 사용안하네? dto도 사용해야지! 도메인도 엔티티어노테이션걸어줘야지, 서비스테스트코드도 깨지니깐 수정해줘야 되고 일급콜렉션도 써야대!"라는 말들이 머릿속에 계속 맴돌았는데요.
하나 고칠때마다 어어? 그어지는 빨간줄, 테스트코드 실패에 수습하느라 정신이 없었습니다. 
사담이 길었는데요. 그래도 PR을 날리니깐 뿌듯하네요.

테스트코드는  fixture에 변수생성과 샘플을 만들어 최대한 사용하려고 하였습니다.
테스트 메소드 안에서만 사용해야할 변수는 변수생성을 이용하였습니다.

꼼꼼한 리뷰 부탁드립니다.
감사합니다.👍

2021-12-22 18:29 UTC, na-mul requested changes
안녕하세요 승민님!
정말 능숙하게 2단계도 잘 진행해주셨군요. 👍
덕분에 코멘트드릴 내용이 많지는 않지만, 그래도 꼭 짚고 넘어갔으면 하는 내용을 적어두었으니 참고 부탁드릴께요!
한번 검토하시고, 수정하셔서 다시 Request 부탁드리겠습니다! 고생하셨어요 🙇‍♂️

2021-12-22 18:29 UTC, na-mul commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    }
menuGroup 도메인이 별도의 패키지에 위치하고있다면, 이렇게 바로 `MenuGroupRepository`를 가져다쓰기보다는 `menuGroupService`를 호출하는 편이 조금 더 패키지 간 결합을 느슨하게 만드는 데 좋을 것 같습니다.

2021-12-22 18:29 UTC, na-mul commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    }
이 부분 역시 `ProductService`를 사용하는 편이 자연스러워보입니다.

2021-12-22 18:29 UTC, na-mul commented on src/main/java/kitchenpos/order/application/TableService.java
> +        savedOrderTable.changeEmpty(request.isEmpty());
changeEmpty가 수행되기 전에는 반드시 checkOrderStatus 메소드로 유효성 체크가 진행되어야 할 것입니다.
그렇다면 차라리 그러한 로직을 Service에 두지 말고 엔티티로 옮겨보면 어떨까요?
즉 changeEmpty 안에서 checkOrderStatus를 챙기게 하면 좋을 것 같습니다.

하지만 그렇게 하기 위해서는 Repository를 사용하지 않고도 Order들에 접근할 수 있어야할 것입니다.
이럴때는 JPA의 일대다 연관관계를 활용해보면 어떨까요?

2021-12-22 18:29 UTC, na-mul commented on src/main/java/kitchenpos/tableGroup/application/TableGroupService.java
> +
역시 이 부분도 OrderTable Entity에 일대다 연관관계를 걸어서 Enitity로 로직을 옮겨볼 수 있을 것 같스빈다. 
그렇다면 tableGroup.ungroup();만 호출되어도 유효성 체크가 ungroup 메소드 안쪽에서 이뤄지도록 할 수 있겠죠.

2021-12-22 18:29 UTC, na-mul commented on src/main/java/kitchenpos/tableGroup/application/TableGroupService.java
> +        return savedOrderTables;
TableService에 위치해도 괜찮을 로직으로 보입니다.

2021-12-22 18:29 UTC, na-mul commented on src/test/java/kitchenpos/fixture/OrderFixture.java
> +}
특히 복잡했을 텐데 Fixture로 잘 진행해주셨습니다. 👍🙇‍♂️

2021-12-22 18:29 UTC, na-mul commented on src/test/java/kitchenpos/order/domain/OrderTest.java
> +    }
특히 엔티티레벨까지 단위 테스트를 꼼꼼히 작성해주신 것이 매우 눈에 띄네요! 칭찬드립니다.

2021-12-22 18:29 UTC, na-mul commented on src/main/java/kitchenpos/menuGroup/domain/MenuGroup.java
> +public class MenuGroup {
menuGroup이 별도 패키지로 나뉠 정도로 커다란 기능을 하는지는 한번 검토해볼 필요가 있을 것입니다.
그리고 만약 이정도 크기라면 분리하는 것이 당연하다고 한다면, orderTable의 패키지도 order와 분리하는 것도 검토해볼만 할 것 같습니다.

2021-12-23 08:03 UTC, lsm7179 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    }
처음 미션을 진행할때 패키지분리부터 해서 이부분 고민을 덜 한거 같습니다.
고민해보니 menuGroup 도메인은 menu 패키지와 같이 넣었고 `menuGroupService`를 호출하도록 변경했습니다.
감사합니다.

2021-12-23 08:04 UTC, lsm7179 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    }
이부분도  `ProductService`를 호출하도록 변경했습니다. 👍

2021-12-23 08:06 UTC, lsm7179 commented on src/main/java/kitchenpos/order/application/TableService.java
> +        savedOrderTable.changeEmpty(request.isEmpty());
서비스계층이 좀 줄어들지 않아서 어떻게 해야될까 생각 해봤는데 잘 하지 못한거같습니다. ㅠ
알려주신 연관관계를 이용해서 비교적 쉽게 풀어낼수 있었습니다.
감사합니다.! 👍

2021-12-23 08:06 UTC, lsm7179 commented on src/main/java/kitchenpos/tableGroup/application/TableGroupService.java
> +
이 부분도 수정했습니다.

2021-12-23 08:08 UTC, lsm7179 commented on src/main/java/kitchenpos/menuGroup/domain/MenuGroup.java
> +public class MenuGroup {
처음에 menuGroup를 리팩토링 하다보니 별 고민 하지 않고 패키지부터 나눈게 문제였던거 같습니다.
menu와 같은 패키지로 변경 하였습니다.

감사합니다. :man-bowing:

2021-12-23 22:01 UTC, na-mul approved these changes
안녕하세요 승민님.
코멘트 내용 뿐만 아니라 더 꼼꼼히 코드를 수정해주셔서 깔끔하게 요구사항을 만족해주신 것 같아요. 👏
approve에 문제없을 것 같습니다! 좋은 코드 잘 보았습니다. 👍
고생 많이 하셨고, 이제 다음 단계를 부탁드립니다.

2021-12-23 22:01 UTC, na-mul commented on src/main/java/kitchenpos/order/domain/Orders.java
> +
일급컬랙션을 이용하신 것은 정말 칭찬드리고 싶네요! 👍

2021-12-23 22:01 UTC, na-mul commented on src/main/java/kitchenpos/product/domain/Product.java
> +        validatePrice(price);
메소드 명도 디테일하게 챙겨주셨군요! 🙇‍♂️

2021-12-23 22:01 UTC, na-mul commented on src/main/java/kitchenpos/tableGroup/application/TableGroupService.java
> +    private final TableService tableService;
덕분에 의존 관계를 훨씬 간결하게 줄여볼 수 있었네요.

2021-12-23 22:01 UTC, na-mul commented on src/test/java/kitchenpos/order/domain/OrdersTest.java
> +public class OrdersTest {
꼼꼼한 단위 테스트 추가도 인상적입니다. 👏

2021-12-23 22:01 UTC, na-mul commented on src/main/java/kitchenpos/order/domain/OrderTable.java
> +                    this.orders.add(order);
`order.updateOrderTable(this);`를 orders에서 해야할지 orderTable에서 해야할지도 고민이 살짝 되셨을 것 같은데, 

코드가 너무 복잡해지지 않는 선에서 간결하게 잘 처리해주셨습니다. 🙇‍♂️

2021-12-23 22:01 UTC, merged