Step1 : 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #358
Opened 2021-12-23 19:12 UTC by codeleesh

안녕하세요 리뷰어님! 

Step1 : 테스트를 통한 코드 보호 미션 리뷰 요청드립니다.

도메인과 서비스 클래스와 Sql, .http 등 정보 등을 이용해서 요구사항을 작성하는 재미를 느끼는 시간이었습니다.
또한 지금까지 진행해왔던 테스트 작성에 대해서 정리하면서 작성하는 시간이었습니다.

이번 미션을 진행하면서 두가지 아쉬운 부분은 
첫째, 인수테스트를 작성하지 못한 부분인데, 다음 미션에 맞추어 작성하려고 합니다.
둘째, 예외 처리의 대한 테스트를 작성하지 못하였는데, 이 또한 인수테스트를 통해서 작성하려고 합니다.

그럼 소중한 리뷰 기다리고 있겠습니다.
감사합니다.

2021-12-24 09:31 UTC, minsungryu requested changes
상호님 안녕하세요, 미션 함께 진행하게 되었는데 잘 부탁드립니다 🙂 
몇 가지 코멘트를 남겨드렸는데요
확인해주시고 다시 리뷰 요청 부탁드릴게요 :)

2021-12-24 09:31 UTC, minsungryu commented on src/main/java/kitchenpos/common/exceptions/EmptyException.java
> +        super(HttpStatus.BAD_REQUEST, NO_EMPTY);
(도메인과 관련되어보이는) 예외와 HTTP 상태코드가 강하게 결합되어있는데요, 이를 분리하는 것이 좋지 않을까요?

2021-12-24 09:31 UTC, minsungryu commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    }
의존성은 항상 저수준에서 고수준으로, 구체적인 것에서 추상적인 것으로 향해야 하지 않을까요?
핵심 업무 규칙을 다루는 도메인 객체가 세부적인 영속 계층 의존하게 되면 확장성이 떨어지고 변경에 취약하게 됩니다.
전반적으로 모든 도메인 객체에 비슷한 변경사항이 생겼는데요, 함께 살펴봐주시면 좋을 것 같습니다.

2021-12-24 09:31 UTC, minsungryu commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    @DisplayName("주문 상태를 변경한다.")
주문이 완료되는 것도 취소되는 것도 변경인데요, 테스트가 설명하고자 하는 바를 구체적으로 작성해주시면 어떨까요?
개발자들이 테스트를 유지보수하기 위해 다시 테스트 로직을 보는 것 또한 비용이 드는 작업이니 유지보수 측면에서 가독성도 잘 챙겨주시면 좋을 것 같습니다.

2021-12-24 09:33 UTC, minsungryu commented
상호님, 커밋 로그를 보니 테스트를 작성해주신 뒤 리팩토링을 해주셔서 좋은 것 같습니다 👍 
다만 이번 단계는 기존 코드를 파악하고 테스트 코드를 통해 검증하고 보호하는 차원이 강했다는 점에서
컨벤션 정리, 전반적인 코드 수정 등 추가적인 변경 사항이 들어가지 않아도 괜찮았을 것 같아서 추가로 코멘트 남깁니다!

2021-12-24 10:17 UTC, codeleesh commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    @DisplayName("주문 상태를 변경한다.")
네 맞습니다. 비용을 줄이기 위해서 좀 더 정확하게 적는 것이 중요할것 같습니다. 수정하겠습니다.

2021-12-24 10:20 UTC, codeleesh commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    }
네 진행할때는 편해보여서 진행하였는데, 해주신 말씀처럼 도메인 객체에서 영속 계층의 대해서 알 필요는 없을것 같습니다. 수정하겠습니다.

2021-12-24 10:54 UTC, codeleesh commented on src/main/java/kitchenpos/common/exceptions/EmptyException.java
> +        super(HttpStatus.BAD_REQUEST, NO_EMPTY);
네 외부에서 입력받아서 넘기는 부분으로 수정하면 될것 같습니다 감사합니다!

2021-12-24 10:56 UTC, codeleesh commented
> 상호님, 커밋 로그를 보니 테스트를 작성해주신 뒤 리팩토링을 해주셔서 좋은 것 같습니다 👍 다만 이번 단계는 기존 코드를 파악하고 테스트 코드를 통해 검증하고 보호하는 차원이 강했다는 점에서 컨벤션 정리, 전반적인 코드 수정 등 추가적인 변경 사항이 들어가지 않아도 괜찮았을 것 같아서 추가로 코멘트 남깁니다!

네 테스트는 먼저 작성하였습니다. 테스트 작성하면서 눈에 보이는 부분만 리팩토링 한다고 하였는데 욕심이 조금씩 생겨서 그랬습니다.!

2021-12-25 05:07 UTC, minsungryu approved these changes
상호님, 1단계 구현하시느라 고생 많으셨습니다!
PR은 merge할테니 다음 단계도 잘 부탁드려요 :)

2021-12-25 05:07 UTC, minsungryu commented on src/main/java/kitchenpos/application/MenuService.java
> +            throw new NoRequiredInputPriceException(HttpStatus.BAD_REQUEST);
서비스 역시 웹의 세부사항에 종속되면 안되지 않을까요?
컨트롤러 또는 어드바이스에서 통해 응답 상태 코드를 결정하면 좋을 것 같습니다.

2021-12-25 05:07 UTC, minsungryu commented on src/main/java/kitchenpos/common/exceptions/CustomException.java
> +    private final HttpStatus status;
예외와 HTTP상태 코드는 분리하는 것이 좋지 않을까요?

2021-12-25 05:07 UTC, merged

2021-12-29 17:36 UTC, codeleesh commented on src/main/java/kitchenpos/common/exceptions/CustomException.java
> +    private final HttpStatus status;
예외와 HTTP 상태 코드를 분리해야 하는 이유에 대해서 고민을 해보았는데요, 아직 잘 모르겠습니다.

사실 그전까지는 예외 메세지와 HTTP 상태코드를 enum으로 관리한적이 있었는데, 점점 추가가 되면서 관리 상태 포화가 되는 현상을 겪어서 번거롭지만 예외 클래스 당 종속적인 메시지를 사용하는 것이 더 직관적으로 느꼈습니다. 그래서 그 메시지에서 종속적인 HTTP 상태 코드를 넣어주는 것이 책임면에서 좋을것 같다고 생각을 하게 되었습니다.

혹시 분리를 해야 되는 내용에 대해서 공유해주실만한 내용이 있다면 부탁드립니다.

2021-12-29 17:36 UTC, codeleesh commented on src/main/java/kitchenpos/application/MenuService.java
> +            throw new NoRequiredInputPriceException(HttpStatus.BAD_REQUEST);
네 해당 부분은 어드바이스를 통해서 예외처리를 하는 것이 맞을 것 같습니다!

2021-12-30 07:11 UTC, minsungryu commented on src/main/java/kitchenpos/common/exceptions/CustomException.java
> +    private final HttpStatus status;
의존성은 항상 저수준에서 고수준으로 세부적인 것에서 추상적으로 향하도록 하면 좋습니다.

웹은 세부사항으로써 우리의 도메인의 핵심 로직에서 HTTP 상태코드에 대한 내용을 알고 의존하면 안됩니다.
우리 애플리케이션이 HTTP API 대신 gRPC를 사용하면 어떻게 되는걸까요?

헥사고날 아키텍처에 관련된 내용은 검색해보시면 자료가 많이 나오니 참고해보시면 좋을 것 같습니다.
로버트 마틴의 '클린 아키텍처'도 추천드려요~