Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #381
Opened 2021-12-25 21:30 UTC by jennie267

안녕하세요 민성님! 😁

2단계 서비스 리팩터링 리뷰요청드립니다 🙇‍♀️

역시 소문대로 많이 어려웠습니다... 😂
이번 미션은 특히 테스트 코드의 중요성을 엄청 느낀 미션이었습니다!! 👍
하나 수정할때마다 실패하는 테스트코드들 덕분에 그나마 여기까지 한것같습니다 😭
(테스트 코드가 없었더라면 어떻게됐을지.... 끔찍합니다 👀😫)

이제 미션 종료까지 일주일밖에 안남았는데요
그래서 초조해지고 마음이 조급해지는데, 그런 마음이 소스에서도 드러나는것같아서 조금 걱정이됩니다... 😂
그래도 마지막날까지 열심히하겠습니다!!! 🔥🔥🔥🔥

그럼 이번 리뷰도 잘 부탁드리겠습니다 🙇‍♀️
감사합니다!! 😁

2021-12-26 12:59 UTC, minsungryu requested changes
지수님 안녕하세요, 2단계 구현하느라 고생많으셨습니다.
변경사항이 많다보니 코멘트 양도 상당히 많아졌는데요
가벼운 마음으로 확인해주시고 다시 리뷰 요청주시면 좋을 것 같습니다~
궁금한 부분이 있으시다면 편하게 질문해주세요 :)

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +        return MenuGroupResponse.from(menuGroupRepository.save(request.toMenuGroup()));
한 줄로 작성해주시는 것도 좋지만 가독성을 위해서는 적절히 변수를 선언하고 개행하는 것도 필요하니 상황에 따라 적절히 고민해보시면 좋을 것 같습니다 :)
(이 부분은 코드가 적어서 이해하기엔 큰 문제는 없네요)

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +            Product product = productService.findById(menuProduct.getProduct());
제품이 100개가 있다면 100번의 조회 쿼리가 실행될텐데요, 성능에 악영향이 있지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +        checkTotalPrice(this.menuProducts.calculatorTotalPrice());
`calculateTotalPrice`는 은연중에 객체가 자료를 저장해두지 않고 메서드 호출시에 계산한다는 구현 세부사항을 노출하는데요
단순히 `getTotalPrice`로 메서드명을 변경해보는 것은 어떨까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +        return Objects.equals(name, menu.name) && Objects.equals(price, menu.price);
엔티티의 동등성은 기본키를 통해 구현하는 것은 어떨까요?
(다른 엔티티들도 같이 봐주시면 좋을 것 같아요)

아래 포스트를 읽어보시면 도움이 될 것 같습니다.
https://jaeyeolshin.github.io/2016-02-06/difference-between-entity-and-value-object/

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/menu/domain/Price.java
> +    private BigDecimal value;
`long` 형으로도 충분할 것 같은데 `BigDecimal`로 선언해주신 이유가 있을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +    private List<MenuProduct> menuProducts;
요청 객체가 도메인 객체에 직접적으로 의존하고 있어서 추이종속성이 생길 우려가 있어 보이는데요
별도의 DTO를 선언하는 것은 어떨까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        order.checkMenuCount(menuService.countByIdIn(menuIds));
메뉴가 존재하는지 검증하는 것이 Order의 책임이 맞을까요?
또한 메뉴 조회 `count`를 비교해서 검증한다는 구현 세부내용이 메서드 이름을 통해 노출되는데 이를 숨기는 것이 좋지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        order.changeOrderStatus(OrderStatus.COOKING);
`order.received()`(메서드 명은 임의로..) 와 같이 주문이 접수되었다고 알려주면 `OrderStatus.COOKING`를 인자로 넘기지 않아도 되지 않을까요?
물론 외부에서 직접 전달해주는 방법도 좋긴합니다 :)

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        final OrderTable orderTable = tableService.findById(request.getOrderTableId());
`OrderTable`이 존재하지 않는 경우에 대한 예외처리를 해주시면 좋지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/application/TableService.java
> +        orderTable.updateTableGroup(null);
이 메서드를 호출해주시는 이유가 있을까요?
앞서 말씀드린 추이종속성 관련해서 서비스에서 또는 별도 매핑 객체를 통해 엔티티를 만들어주셔도 괜찮을 것 같습니다.

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/application/TableService.java
> +    public OrderTableResponse changeEmpty(final Long orderTableId, final OrderTableRequest request) {
`OrderTableRequest`가 여러 서비스 메서드에서 사용되는걸로 보이는데요
가장 좋은 것은 상황에 맞는 DTO를 선언하는 것이겠지만 비용 문제로 같은 DTO를 재사용 하시는거라면 단순히 1~2개의 필드인 경우는 직접 인자를 받아도 좋지 않을까요?
(사실 이 경우 컨트롤러에서 별다른 작업 없이 인자를 바로 넘겨서 서비스 메서드를 호출되도록 개발되었을 것이라 실제 컨트롤러에서 `OrderTableRequest`를 상당부분 재사용할 것이고 이로인해 다른 개발자가 코드를 해석할 때 모호함을 느껴 별도의 비용이 발생할 수 있습니다.)

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/domain/Order.java
> +        checkOrderLineItems();
먼저 검사하는 것이 좋지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/domain/Order.java
> +            orderLineItem.updateOrder(this);
주문목록의 주문이 변경되는 경우도 있는걸까요?
setter를 지양해야 하지만 이 경우 update보다는 set이 적절할 수도 있겠다는 생각이 듭니다.

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/domain/Orders.java
> +    @OneToMany(mappedBy = "orderTable", orphanRemoval = true, cascade = CascadeType.ALL)
주문테이블이 삭제되면 주문도 삭제되는 것을 의도하신걸까요?
적절한 cascade 옵션에 대해 다시 고민해보면 좋을 것 같습니다.

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/domain/Orders.java
> +    public boolean checkMealStatus() {
`check`의 의미가 모호한데요 식사중인 테이블이 있는지 확인하는걸 더 잘 표현하는 메서드명은 어떨까요?
아래 cookingStatus도요!

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/domain/OrderTables.java
> +        orderTables = new ArrayList<OrderTable>();
다른 코드 어딘가에서 기존 리스트를 참조하고 있을 경우 의도하지 않은대로 동작할 것이 우려되는데요
리스트를 비워주는 것도 괜찮지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/main/java/kitchenpos/order/dto/OrderTableRequest.java
> +    public static OrderTableRequest from(OrderTable orderTable) {
from과 of의 차이가 있을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/menu/application/MenuServiceTest.java
> +        assertThat(저장된_메뉴).isEqualTo(MenuResponse.from(메뉴));
동등성으로 테스트를 검증하는 것도 좋은 방법인데요
응답 객체의 경우 동등성을 구현하는 것이 크게 의미가 없을 수도 있고(컬렉션을 사용하지 않는다거나)
테스트 검증부에서 이 단언문이 왜 성공하는지 코드를 열어봐야만 알 수 있을 것 같습니다.
경우에 따라서 필요한 필드를 조회해서 검증해도 좋을 것 같습니다 :)

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/menu/application/MenuServiceTest.java
> +    @DisplayName("등록된 메뉴를 셀 수 있다")
앞서 countByIdIn의 모호함에 대해 코멘트를 남겼었는데요,
마찬가지로 이 메서드를 검증하기위한 일종의 억지스러운(?) 테스트같은 느낌이 듭니다.
메뉴를 셀 수 있는게 중요한 것이 아니라 등록된 메뉴만 주문할 수 있는 것이 실제 업무 규칙에서 중요한 부분일텐데요
이런 부류의 코드는 `Order`관련 코드에서 테스트를 작성하고 여기서는 없어도 괜찮지 않을까 생각이 들었습니다.

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/menu/domain/MenuGroupTest.java
> +public class MenuGroupTest {
테스트를 작성하는 것은 중요하지만 양질의 테스트를 작성하는 것이 더 중요하다고 생각하는데요
단순히 객체 생성이 되는지는 비즈니스에도 코드 동작에도 영양가 있는 테스트라고 보기 어려울 것 같습니다.
테스트를 구현하고 유지보수하는 것도 비용인데요
더 좋은 테스트를 만들기 위해 시간을 들이는 것이 좋지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/menu/domain/MenuTest.java
> +    @DisplayName("메뉴 가격은 0원 이상이어야한다 - 예외처리")
`- 예외처리` 접미사는 어떤 이유로 붙여주신걸까요?
테스트 관련 설명과 코드에는 구현 세부사항이 노출되지 않는 것이 좋지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/menu/domain/PriceTest.java
> +    @DisplayName("가격끼리  잘 더해지는지 확인")
지금 테스트명도 괜찮지만 `가격을 더할 수 있다`와 같이 요구사항을 잘 설명할 수 있도록 개선해볼 수도 있지 않을까요?

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/order/application/OrderServiceTest.java
> +        Order 메뉴없는_주문 = Order.of(null, OrderStatus.COOKING);
반복적으로 null을 인자에 넘겨야한다면 해당 인자가 없는 정적 팩토리 메서드를 선언하는 것은 어떨까요?
null로 인해 해당 코드를 이해하는데 추가적으로 비용이 드는 것 같습니다.
또는 테스트를 위한 별도의 테스트 팩토리, 비공개 메서드를 통해서 코드를 명확하게 개선해볼 수도 있을 것 같습니다.

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/order/application/OrderServiceTest.java
> +        given(tableService.findById(nullable(Long.class))).willReturn(첫번째_테이블);
anyLong()도 사용할 수 있으니 참고해보시면 좋을 것 같습니다.
추가적으로 테스트 픽스처를 설치하는 과정에서 적절히 id를 지정해주는 방법도 있습니다.

2021-12-26 12:59 UTC, minsungryu commented on src/test/java/kitchenpos/order/application/OrderServiceTest.java
> +    @DisplayName("주문상태를 변경 할 수 있다")
주문 상태는 아무렇게나 변경이 가능한걸까요?
이 경우 주문완료 상태에서 다시 요리중 상태로 변경하는 것도 가능해보이는데요
(아래 불가능한 경우에 대한 테스트가 있긴하네요)
해당 기능이 공개 메서드로 제공되는 것이 괜찮을까요?
특정 기능을 통해 주문상태가 변경되는 것을 간접적으로 검증하는 것이 좋지 않을까요?

2021-12-27 14:41 UTC, jennie267 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +            Product product = productService.findById(menuProduct.getProduct());
이 부분은 고민 많이해서 수정했는데 괜찮게한건지 잘 모르겠습니다.. 😥
확인부탁드리겠습니다!

2021-12-27 14:43 UTC, jennie267 commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +        return Objects.equals(name, menu.name) && Objects.equals(price, menu.price);
엔티티는 기본키로 비교하는군요!! 👀
실무에서 엔티티라는 개념을 사용하지않다보니까 이번에 새로 배우게되는게 많네요!!! 🥰
참고링크까지... 👍
감사합니다!!

2021-12-27 14:46 UTC, jennie267 commented on src/main/java/kitchenpos/menu/domain/Price.java
> +    private BigDecimal value;
이번미션이 서비스 로직을 도메인영역으로 옮기는거라고 생각해서 기존에 있던 부분을 옮기는데에만 급급했네요..😥
기존에 `BigDecimal`로 되어있어서 `Price`를 그대로 만들었습니다 😂
수정했습니다!

2021-12-27 14:46 UTC, jennie267 commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +    private List<MenuProduct> menuProducts;
`MenuProductRequest` 를 추가하였습니다 😊

2021-12-27 14:47 UTC, jennie267 commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        order.checkMenuCount(menuService.countByIdIn(menuIds));
`dm`으로 문의했을때, 친절한 답변 감사합니다! 🙇‍♀️

2021-12-27 14:49 UTC, jennie267 commented on src/main/java/kitchenpos/order/application/TableService.java
> +        orderTable.updateTableGroup(null);
빠졌어야했는데 들어갔네요 삭제했습니다! 🙇‍♀️

2021-12-27 14:50 UTC, jennie267 commented on src/main/java/kitchenpos/order/domain/Orders.java
> +    @OneToMany(mappedBy = "orderTable", orphanRemoval = true, cascade = CascadeType.ALL)
우테캠을 통해서 JPA를 처음써보는거라 아직 익숙치않네요..😥
수정했습니다!

2021-12-27 14:54 UTC, jennie267 commented on src/main/java/kitchenpos/order/dto/OrderTableRequest.java
> +    public static OrderTableRequest from(OrderTable orderTable) {
매개변수가 1개일때는 `from`을 주로 쓰고 여러개일때는 `of`로 명명한다고 알고있어서 보통 네이밍을 그렇게 짓고있습니다! 👀
`이펙티브자바`라는 책에 해당 내용이 나와서 이렇게 지었는데 혹시 실제로는 `from`이랑 `of`랑 혼용해서 쓰면 안좋은패턴인건가요...?

(참고링크 - [아이템 1. 생성자 대신 정적 팩토리 메서드를 고려하라](https://slf4me.com/post/effective-java/01/) )

2021-12-27 14:55 UTC, jennie267 commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +        return MenuGroupResponse.from(menuGroupRepository.save(request.toMenuGroup()));
넵! 가독성도 고려하여 개발하겠습니다! 🙇‍♀️

2021-12-27 14:58 UTC, jennie267 commented on src/test/java/kitchenpos/menu/domain/MenuGroupTest.java
> +public class MenuGroupTest {
서비스에 있는 메서드와 도메인에 있는 메서드는 웬만하면 다 테스트코드를 작성하는게 좋은줄 알았습니다.... 😥
민성님의 리뷰대로 유지보수할때 방해가 될수있겠네요 😂
이제라도 알게됐으니 앞으로는 좋은 테스트를 만들도록 노력하겠습니다 🙇‍♀️👍

2021-12-27 14:58 UTC, jennie267 commented on src/test/java/kitchenpos/menu/domain/MenuTest.java
> +    @DisplayName("메뉴 가격은 0원 이상이어야한다 - 예외처리")
제거했습니다 😁

2021-12-27 15:00 UTC, jennie267 commented on src/test/java/kitchenpos/order/application/OrderServiceTest.java
> +    @DisplayName("주문상태를 변경 할 수 있다")
특정 기능을 통해 변경되도록 수정했습니다 🙇‍♀️

2021-12-28 03:58 UTC, minsungryu approved these changes
지수님, 2단계 완료하시느라 고생많으셨습니다!
많은 고민과 노력의 흔적이 느껴졌습니다.
다음 단계도 화이팅입니다!

2021-12-28 03:58 UTC, minsungryu commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    private Menu(String name, Long price, MenuGroup menuGroup) {
가격은 nullable한 값인가요?
가격이 필수라면 long으로 선언해보는 것은 어떨까요?
물론 Long -> long 변환시 NPE가 발생하지 않도록 주의해야 하긴 합니다!

2021-12-28 03:58 UTC, minsungryu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        order.received();
별도의 메서드 호출이 필요없이 createOrder 시점에 status를 지정해줘도 되지 않을까요?

2021-12-28 03:58 UTC, minsungryu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        return OrderResponse.from(orderRepository.save(order));
dirty check 기능이 있기 때문에 별도로 save 메서드를 호출하지 않아도 되지 않을까요?

2021-12-28 03:58 UTC, minsungryu commented on src/main/java/kitchenpos/order/domain/Order.java
> +    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
orphanRemoval은 Order와 OrderLineItem의 관계를 어떻게 해석하는지에 따라 다를 것 같은데요
cascade의 경우는 MERGE도 함께 고려해주면 좋지 않을까요?

2021-12-28 03:58 UTC, minsungryu commented on src/main/java/kitchenpos/order/domain/Order.java
> +        checkCompletionStatus();
상태를 변경할 때는 완료뿐 아니라 식사중인 주문이 조리중으로 바뀌면 안되지 않을까요?

2021-12-28 03:58 UTC, minsungryu commented on src/test/java/kitchenpos/menu/domain/MenuProductTest.java
> +    @DisplayName("메뉴 상품의 수량 반영 가격을 확인한다")
`상품의 가격은 메뉴의 가격과 수량을 곱한 값이다`라는 설명이 이해하기 더 쉽지 않을까요?

2021-12-28 03:58 UTC, minsungryu commented on src/test/java/kitchenpos/menu/domain/PriceTest.java
> +    @DisplayName("수량에 따라 총 가격이 잘 만들어지는지 확인한다")
`잘 만들어진다`의 의미가 구체적이어도 좋지 않을까요?
다만 이 테스트는 Price객체에 관한 것이니 `가격은 곱셈이 가능하다`와 같은 설명이 적절할 수 도 있을 것 같습니다.
값 객체인 Price 테스트를 만들면서 업무 규칙 관한 내용이 스며든 것 같아서 언급해보았습니다.

2021-12-28 03:58 UTC, merged

2021-12-28 13:54 UTC, jennie267 commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        order.received();
이미 createOrder에서 status를 지정해주고있는데 `received()`를 만들어서 중복으로 지정해주고있었네요...!! 👀
수정하겠습니다!
꼼꼼히 봐주셔서 감사합니다 😁👍👍

2021-12-28 14:26 UTC, jennie267 commented on src/main/java/kitchenpos/order/domain/Order.java
> +        checkCompletionStatus();
OrderService에 `식사중으로 상태변경`, `계산완료로 상태변경` 이 두 케이스밖에 없어서 조리중으로 변경될거라는 생각을 못했네요! 😥
추후 어떻게 기능이 추가될지 모르니까 말씀해주신것처럼 `Order`에 validation을 추가하는게 맞다고생각합니다  👍
수정하겠습니다 ! 🙇‍♀️