Step3 : 양방향을 단방향
next-step/jwp-refactoring pull request #4
Opened 2021-01-07 16:06 UTC by cionman

안녕하세요, 

6주차 3단계 양방향을 단방향 미션 풀리퀘스트 요청 드립니다.

지난 미션에서 price 객체 포장에 관한 코멘트를 MenuRequest안에 price를 객체 포장하라고 말씀하신것으로 오해했던것 같습니다. Menu와 Product내에 price 값을 객체로 포장하였습니다.

그리고 이외에 마지막에 남겨주신 피드백도 반영했습니다.

이번 미션에서 패키지간의 양방향의존 관계는 ArchUnit으로 찾아서 순환참조가 없음을 검증을 했는데, 클래스간의 양방향을 찾는 방법은 Intellij의 UML을 확인해서 찾는 방법으로 확인을 했습니다. 

그러나 이 방법은 특정 패키지 안에 클래스들만 UML로 확인할 수 있어서 패키지를 넘어선 클래스간의 UML은 나오지 않아 확인을 못했습니다. 아래 스크린샷은 domain 패키지내에 UML 스크린샷이고 나머지 패키지도 확인을 했습니다. 계층을 나누어서 코드를 작성하기에 패키지를 넘어선 클래스간에 양방향은 없으리라 생각은 됩니다만 100프로 확실치는 않네요 ㅎ  혹시 이와 관련되어 방향을 알려주시면 다시 반영하겠습니다.

감사합니다.

![UML](https://user-images.githubusercontent.com/4695150/103914434-2d57ea00-514d-11eb-9ef2-a59b9fdf743d.png)

2021-01-08 06:25 UTC, seok-2-o requested changes
오히려 제가 많이 배우는것 같군요 💯 
`ArchUnit` 와 `IntelliJ UML` 활용을 정말 멋지게 해주셨네요 👍 

설계상 궁금한점이 있어 코멘트 남겨놓았습니다. 답변 달아주시거나 리펙토링 진행해보면 좋을 것 같아요.

2021-01-08 06:25 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/Menu.java
> +	public void addMenuProduct(List<MenuProduct> menuProducts) {
한번에 여러개를 넣는방식을 선택하셨네요.
메뉴를 조회한 후 상품을 추가하려고하면 어떻게 해야할까요?

2021-01-08 06:25 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/MenuPrice.java
> +public class MenuPrice {
Bigdecimal과 유사하게 add 메소드도 구현할 수 있을것 같아요.

2021-01-08 06:25 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/MenuPrice.java
> +	public boolean isPositive(BigDecimal totalPrice) {
Greater than 표현이 더 적합하지 않을까요
isPositive는 양수인지 체크할때 많이 쓰는것 같아요.

2021-01-08 06:25 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +	public BigDecimal getPrice() {
이왕 MenuPrice  를 만들었다면 도메인 레이어에서는 계속 활용하는건 어떤가요?

2021-01-08 06:25 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/ProductPrice.java
> +public class ProductPrice {
별도로 만들어주셧네요
메뉴 가격과 상품 가격은 다른 컨텍스트라고 생각하시나요? 🤔

2021-01-08 06:25 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/Menu.java
> +	public void addMenuProduct(List<MenuProduct> menuProducts) {
메뉴를 한번 만든 후 변경이 불가능하다면 
제가 드린 코멘트이긴 하지만 add 메소드를 제공하는 것 자체에 대해 다시 고민해봐야 할 것 같아요.

2021-01-08 07:28 UTC, cionman commented on src/main/java/kitchenpos/domain/ProductPrice.java
> +public class ProductPrice {
메뉴 가격과 상품 가격,  요구사항에 없는 상상이지만, 메뉴 가격의 경우 사용자에게 노출되는 가격이 될 것이고, 상품 가격은 식당을 운영하는 내부에서 관리하는 가격이 될 것 같습니다. 저의 견해는 다른 컨텍스트의 의미 부여가 충분히 이루어지지 않을까 싶습니다.

그리고 현재도 MenuPrice의 메서드는 총합 가격을 받아 메뉴 가격과 비교하여  boolean을 전달해주는 메서드가 따로 있거든요

2021-01-08 07:29 UTC, cionman commented on src/main/java/kitchenpos/domain/MenuPrice.java
> +	public boolean isPositive(BigDecimal totalPrice) {
음 넵 그렇기는 하네요 피드백 반영하겠습니다!

2021-01-08 07:48 UTC, cionman commented on src/main/java/kitchenpos/domain/MenuPrice.java
> +	public boolean isPositive(BigDecimal totalPrice) {
피드백 반영되었습니다.

2021-01-08 07:50 UTC, cionman commented on src/main/java/kitchenpos/domain/MenuPrice.java
> +public class MenuPrice {
피드백 반영하였습니다. 감사합니다.

2021-01-08 07:53 UTC, cionman commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +	public BigDecimal getPrice() {
이 부분도 MenuPrice로 반환하도록 변경하였습니다. 피드백 감사합니다~

2021-01-08 08:20 UTC, cionman commented on src/main/java/kitchenpos/domain/Menu.java
> +	public void addMenuProduct(List<MenuProduct> menuProducts) {
https://github.com/next-step/jwp-refactoring/pull/3#discussion_r553201965

지난 스텝에서 남겨주신 코멘트를 이제야 보았습니다. 제시해주신 방법으로는 안되지 않을까 싶습니다.
addMenuProduct를 하나씩만 add 시킨다고 했을때, `products.getTotalPrice()` 는 add 되는 시점에서의 전체 상품 가격이어서요, 전체 상품 가격의 합과 비교해야만 하는 요구사항이어서 안될듯 합니다.

```

public class Menu {
private long price;
private MenuProducts products

public void add(MenuProduct product) {
    if(product.getPrice() + products.getTotalPrice() > price) {
       throw new Exception();
    }
    products.add(product);
}

}
```

2021-01-08 08:26 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/Menu.java
> +	public void addMenuProduct(List<MenuProduct> menuProducts) {
저장된 상품들의 합 + 저장할 상품의 합을 계산하고 상품을 넣어주면 가능 하지 않을까요?

2021-01-08 08:28 UTC, cionman commented on src/main/java/kitchenpos/domain/Menu.java
> +	public void addMenuProduct(List<MenuProduct> menuProducts) {
MenuProduct add 부분을 전체가 아닌 하나씩 add하는 방식으로 변경하고, Menu가격과 상품가격 총합을 검증하는 부분 서비스에서 수행하도록 수정 반영 되었습니다.

2021-01-08 08:29 UTC, cionman commented
피드백 반영과 코멘트 남겨두었습니다. 다양한 의견과 리뷰 감사드립니다~

2021-01-08 08:31 UTC, cionman commented on src/main/java/kitchenpos/domain/Menu.java
> +	public void addMenuProduct(List<MenuProduct> menuProducts) {
앗 남겨주신 코멘트를 이제보았네요 ㅜ

2021-01-08 08:33 UTC, cionman commented on src/main/java/kitchenpos/domain/Menu.java
> +	public void addMenuProduct(List<MenuProduct> menuProducts) {
저장할 상품의 합의 경우 `product.getPrice()` 현재 저장할 product의 price만이기때문에,  아직 저장하지 못한 상품의 합을 함께 넣어주어야하고, add 시킬때마다 해당 부분을 계산해야되서 불필요한 계산들이 product 계산할때마다 불필요한 연산이 수행되지 않을까요?

2021-01-09 04:32 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요 👍 

제가 미션을 오해해서 잘못된 정보로 혼란을 드린점 다시한번 죄송합니다.

소소한 제 생각남겨놓았으니 다음 미션에서 함께 고민해보면 좋을것 같아요.

이어서 다음 미션 진행해주세요.

2021-01-09 04:32 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/MenuPrice.java
> +		return new MenuPrice(price.add(otherPrice.price));
소소하지만 값 객체에 대한 증/감연산에 적용 할 수 있는 소소한 패턴입니다.
```
if(other.price.equals(Bigdecimal.ZERO)) {
        return this;
}
```

2021-01-09 04:32 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +	private Long menuId;
👍

2021-01-09 04:32 UTC, seok-2-o commented on src/main/java/kitchenpos/domain/ProductPrice.java
> +public class ProductPrice {
개인적으로는 MenuPrice 와 ProductPrice 는 비교나 연산등이 빈번하게 발생하므로 같은 클래스로 만들어줘도 장점이 많을 것 같아요.

2021-01-09 04:32 UTC, seok-2-o commented on src/main/java/kitchenpos/application/MenuService.java
>  	private void addMenuProduct(MenuRequest menuRequest, Menu savedMenu) {
> 자바 빈즈 패턴에서는 객체 하나를 만드려면 메서드를 여러개 호출해야 하고, 객체가 완전히 생성되긱 전까지 일관성(Consistency) 이 무너진 상태에 놓이게 된다. - 이펙티브 자바

지금 케이스가 위 케이스가 비슷한 것 같아요

Builder 패턴을 통해서 Menu 를 만들어 보는건 어떤가요?

2021-01-09 04:32 UTC, merged

2021-01-09 05:58 UTC, cionman commented on src/main/java/kitchenpos/application/MenuService.java
>  	private void addMenuProduct(MenuRequest menuRequest, Menu savedMenu) {
음 MenuProduct를 만들때 menu id를 입력 해주어야하는 부분도 있어서 어렵지 않을까 생각됩니다.