🚀 3단계 - 의존성 리팩터링
next-step/jwp-refactoring pull request #416
Opened 2021-12-28 16:54 UTC by chapitak

안녕하세요. 오늘도 리뷰 부탁드립니다. 
일단 양방향 의존관계를 분리하는데 초점을 맞췄습니다. 
1. Menu와 MenuProduct 클래스 사이에 존재하던 양방향 의존관계를 단방향으로 정리했습니다. 
2. Order와 OrderTable 클래스 사이에 존재하던 양방향 의존관계를 단방향으로 정리했습니다. OrderValidator 클래스를 생성하여 검증 로직의 일부를 담당하도록 햇습니다. 
3. TableGroup과 OrderTable 클래스 사이에 존재하던 양방향 의존관계를 단방향으로 정리했습니다. 
4. Order와 OrderLineItem 클래스 사이에 존재하던 양방향 의존관계를 단방향으로 정리했습니다. 
5. 패키지 간 의존성 순환 문제를 해결하기 위해 OrderValidator 클래스의 패키지를 이동하고 인터페이스를 추출하였습니다.
머리가 지끈거리네요. 매일 고생이 많으세요. 오늘도 감사합니다

2021-12-29 13:44 UTC, chapitak commented
PR 올려만 놓고 리뷰 요청을 안드렸었네요 ㅠㅠ  이럴수가

2021-12-30 10:18 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨어요 👍 
코멘트 남겨두었으니 확인 부탁드릴게요 :)

2021-12-30 10:18 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/domain/OrderValidatorImpl.java
> +    public void canUngroupOrChange(Long id) {
해당 검증을 Validator로 분리해주신 이유가 있을까요?

2021-12-30 10:18 UTC, jaeyeonling commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +        this.orderTables.forEach(orderTable -> orderValidator.canUngroupOrChange(orderTable.getId()));
https://github.com/next-step/jwp-refactoring/pull/376#discussion_r775192740 에 대한 케이스에 해당될 것 같네요 ㅎㅎ 
깔끔한 코드를 작성하다 보면 성능 이슈와 충돌이 날 경우가 있는데, 어떠한 기준을 가지면 좋을지에 대해서도 고민해보면 좋을 것 같습니다 :)

2021-12-30 10:18 UTC, jaeyeonling commented on src/main/java/kitchenpos/tablegroup/domain/TableGroupValidator.java
> +public class TableGroupValidator {
해당 클래스는 사용하지 않는 코드일까요? ㅎㅎ

2021-12-30 10:18 UTC, jaeyeonling commented on src/test/java/kitchenpos/domain/OrderTableTest.java
> +    OrderValidatorImpl orderValidator;
OrderValidator 인터페이스를 활용하여 Mockito를 사용하지 않고 Fake하게 만들어볼 수 있을 것 같아요 ㅎㅎ

2021-12-30 10:18 UTC, jaeyeonling commented on src/main/java/kitchenpos/menu/domain/MenuProducts.java
>  public class MenuProducts {
`메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.`라는 요구사항이 지켜지고 있을까요?

2021-12-30 12:51 UTC, chapitak commented on src/main/java/kitchenpos/order/domain/OrderValidatorImpl.java
> +    public void canUngroupOrChange(Long id) {
기존 step2에서 validateChangeEmpty 메서드는, OrderTable에서 참조하고있는 Order를 탐색하며 Ungroup 또는 Change가 가능한지를 탐색하는 형식이었습니다. 이를 OrderTable에서 Order의 의존성을 제거하면서, OrderRepository DB에 접근하여 불러오는 역할을 OrderValidator로 추출하였습니다. 과정의 참고자료인 조영호 님의 영상에서 이와 같은 방식으로 의존성을 제거하는 사례가 나와서 적용해보고싶어서 적용하였습니다.

2021-12-30 12:51 UTC, chapitak commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +        this.orderTables.forEach(orderTable -> orderValidator.canUngroupOrChange(orderTable.getId()));
이것도 한 번에 가능한 문제인데.. 같은 실수를 반복하였습니다

2021-12-30 12:51 UTC, chapitak commented on src/main/java/kitchenpos/tablegroup/domain/TableGroupValidator.java
> +public class TableGroupValidator {
사실입니다

2021-12-30 12:52 UTC, chapitak commented on src/test/java/kitchenpos/domain/OrderTableTest.java
> +    OrderValidatorImpl orderValidator;
이런 방법이 있었군요. 너무 재미있습니다.

2021-12-30 12:52 UTC, chapitak commented on src/main/java/kitchenpos/menu/domain/MenuProducts.java
>  public class MenuProducts {
OrderLineItem이 Menu를 간접참조하도록 변경하였습니다

2021-12-31 11:37 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/domain/OrderValidatorImpl.java
> +    public void canUngroupOrChange(Long id) {
의존성을 제거하는 관점에서는 잘 구현해주셨습니다 👍 
꼭 Validator가 아니여도 별도 클래스를 통해 의존성을 제거해볼 수 있을텐데요!
두 객체 간 의존성이 필요한 기능들이 있는데, 그 역할을 담당하는 클래스를 통해 해결을 해볼 수도 있을 것 같아요 ㅎㅎ 
꼭 반영해주실 필요는 없고 고민만 해주셔도 좋을 것 같아요 😄

2021-12-31 11:38 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
도움될만한 내용 남겨두었으니 확인 부탁드리고, 다음 단계 진행해주세요 😄

2021-12-31 11:38 UTC, merged