Step4. 멀티 모듈 적용
next-step/jwp-refactoring pull request #443
Opened 2021-12-30 17:59 UTC by seunghoona

안녕하세요 리뷰어님 

리팩토링의 마지막 단계 4단계에 돌입했네요 ! 

처음 모듈화를 진행할 때 두 가지를 생각했습니다. 
재상용성인가 ? 운영의 편의성인가.

1. 재 사용성으로 간다면 각각의 도메인 분리가 가능하겠지만,
2. 운영 측 입장에서 본다면 `가끔 전화가 오거나 하면 소스를 빠르게 파악하는 필요가 있기도합니다`
3. 그렇다 보니 Domain을 하나로 묶는 것이 좋다고 생각하였고 
###  api 모듈에는 contoller, dto , 인수테스트 를 넣었습니다.
- 이 과정에서 mock 으로 테스트 짜던 부분들을 Domain쪽으로 이동하게 되었습니다.
- 물론 테스트 하기 어려운 영역은 mock으로 감싸게 되었지만 대부분 중복되는 부분은 삭제하게 되었습니다.

----- 

위 과정을 진행 하기 전 도메인 별로 분리를 계획했습니다. 

- 해당 과정은 `READMe`에 남기게 되었는데 어떻게 생각하시나요 
-  어떻게 생각 하시는지 질문합니다.

2021-12-31 11:29 UTC, na-mul commented
> 운영 입장에서 만약 소스를 확인 해야 한다면 여러 개의 모듈을 열어 봐야 한다면 힘들다는 생각이 들었습니다 .
> 만약 모듈 별로 탐색해야 한다면 심각하게 지연이 발생할 수 있다는 생각이 들었습니다.

적절한 모듈로 나누게 되면 중복이 줄어들어 오히려 확인해야할 소스가 줄어듭니다. 
동일한 core 모듈이 web 서버에도 쓰이고, batch 서버에도 쓰이고 그런 식이죠.

다만 모듈을 사용했을 때의 단점은, web 서버만을 위한 소스를 수정할 수 없다는 것입니다.
core 모듈을 변경하면 web 서버 뿐만아니라 batch 서버에도 영향이 가죠.

결국 소스 중복으로 오히려 이슈 대응 시간은 줄어들지만,
소스 수정 시, 한번에 영향 받는 서버가 늘어나기에 배포 시점에 QA 비용은 증가하는 단점이 있습니다.

2021-12-31 11:34 UTC, na-mul requested changes
안녕하세요, 승후님!
4단계 정말 잘 진행해주셨습니다.
과정 종료가 얼마 남지 않아 조바심이 나실 법도 한데, 
깊은 고민도 많이 녹여서 진행해주신 점 정말 칭찬드려요!
코멘트 남긴 내용에 대해 검토해주시고 다시 Request 부탁드립니다!

2021-12-31 11:34 UTC, na-mul commented on module-api/src/main/java/kitchenpos/ModuleApiApplication.java
> +public class ModuleApiApplication {
`@SpringBootApplication` 어노테이션을 붙여줘야 할 것으로 보여요!

2021-12-31 11:34 UTC, na-mul commented on module-domain/src/main/java/kitchenpos/ModuleDomainApplication.java
>  }
module-domain은 단독으로 구동시킬 일이 없어보여요!
이 메인 클래스는 삭제되어도 될 것으로 보입니다.

2021-12-31 11:34 UTC, na-mul commented on README.md
> +- 분리 전 **OrderTable 와 Order 는 패키지를 분리한 상태였습니다.**
지연이 발생하고, 실패 시 재시도 등을 처리하기 위해 보통 메시지 큐를 사용하게 됩니다.
(rabbitMq, kafka, Amazon SNS-SQS등)

지연이 발생해도, 큐가 완충 역할을 하여 지연 시간 동안 대기열을 만들어 유실되 지 않도록 해줍니다.
또한 로직 실패 시에는 큐에서 이벤트를 빼지 않고 놔둠으로서 다시 재시도할 수 있도록 하죠.

다만 말씀하신대로 build.gradle에 Order를 포함하는 방식으로 해서, 모듈은 분리해서 개발했지만, 배포 시에는 필요한 모듈들이 모두 하나의 어플리케이션에 전부 들어있을 수 있도록 의존성을 설정하면 됩니다.

이번 미션을 이벤트 소싱 패턴까지 확장하게 되면 너무 커지기 때문에, 단순하게 진행해주신 것이 오히려 낫다는 생각입니다.
고생하셨습니다!!

2021-12-31 11:34 UTC, na-mul commented on build.gradle
> +        implementation 'org.springframework.boot:spring-boot-starter-actuator'
이러한 의존성은 api 모듈에만 필요하지 domain이나 common 모듈에는 필요하지 않을 것입니다. 
해당 의존성을 공통 의존성에서 제거하고 꼭 필요한 곳 (아마 api겠죠?)에 설정해주세요!

2021-12-31 11:34 UTC, na-mul commented on build.gradle
> +        implementation 'org.springframework.boot:spring-boot-starter-web'
아마 spring-boot-starter-web 또한 domain에서는 필요하지 않은 의존성일거에요

2021-12-31 15:21 UTC, seunghoona commented on module-domain/src/main/java/kitchenpos/ModuleDomainApplication.java
>  }
단독으로 `실행`해야하는게 아닌가` 하는 생각에 붙였는데 잘못 생각했네요 !

2021-12-31 15:22 UTC, seunghoona commented on README.md
> +- 분리 전 **OrderTable 와 Order 는 패키지를 분리한 상태였습니다.**
`이벤트 소싱` 이란 용어도 이번에 처음 듣게되었는데요. 
따로 깊이 있게 공부해봐야겠네요 ! 
공부할 방향성이 생겨서 좋아요 ㅎㅎ

2022-01-01 00:17 UTC, na-mul approved these changes
안녕하세요, 승후님.
마지막 단계 깔끔히 잘 진행해주셨습니다.
이것으로 승후님의 모든 미션이 종료되었네요. 😄
이번 과정 정말 많이 수고하셨습니다!!! 👏👏👏👏
뜻 깊은 2021년 되셨기를 바라며, 2022년에도 승후님의 높은 성장을 응원하겠습니다. 👍👍

2022-01-01 00:17 UTC, na-mul commented on build.gradle
>      }
코멘트의 내용을 잘 반영해주셨네요. 

리뷰 요청에 항상 상세하게 느낀 바를 적어주셔서 저도 매우 도움이 되었습니다.
어떤 방향으로 리뷰를 드리면 좋을 지 더 고민하게 되었고, 제 리뷰에 대한 보람도 느낄 수 있었죠!

승후님과의 리뷰 즐거웠습니다!

2022-01-01 00:18 UTC, merged