Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #46
Opened 2021-01-19 18:43 UTC by PilhwanKim

코드 리뷰 미리 감사드립니다.

프로젝트 전체를 리펙토링하는거라서 분량이 많네요.

## 2단계 - 서비스 리팩터링 To Do List

- spring data jpa 설정
- 패키지 구조를 도메인 별로 개편
- DTO와 엔티티 분리
- 엔티티 새로 등록 및 변경
  - 테이블, 상품 변경
  - 테이블 그룹, 메뉴 그룹 변경
  - 주문, 메뉴 변경
- 엔티티간 연관관계 설정
- dao -> jpa repository 변경 
- service 리펙토링
  - 테이블 서비스 -> 엔티티
  - 매뉴 서비스 -> 엔티티
  - 주문 서비스 -> 엔티티
- controller 리팩토링
- 전체 구조 리펙토링

2021-01-20 14:05 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public List<MenuResponse> list() {
읽기 작업만 하는 경우 아래와 같이 추가해주면 어떨까요?

```suggestion
    @Transactional(readOnly = true)
    public List<MenuResponse> list() {
```

붙이지 않아도 로직 구현에 크게 상관은 없지만 드라이버에 따라 Writer, Reader 부하 분산을 할 수 있어서 저는 작은 규모의 프로젝트여도 습관처럼 붙이고 있습니다.

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        menu.validateSumPrice(sumPrice);
이 부분은 호출을 안하면 누락될 것 같은데, `Menu`의 생성자나 정적 팩토리 메소드에 추가하면 어떨까요?

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    }
생성자가 public으로 열려있어 아래 제약 조건이 누락되어 생성될 수 있겠네요

```
등록된 메뉴그룹이 선택되어 있어야 한다.
```

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public Menu(Long id, String name, BigDecimal price, MenuGroup menuGroup) {
id는 JPA에 의해 관리되어 생성되는데 이 부분을 생성자에서 주입할 수 있게되면 데이터 정합성에 문제가 생길수 있을 것 같아요.

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    private Long seq;
strategy도 동일하게 `IDENTITY`인데

위에서는 id, 여기서는 seq라는 변수명을 가지고 있어 헷갈리는 것 같아요.

자동 생성되는 아이디 이름은 통일해도 괜찮지 않을까요?

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    public MenuProduct(Long seq, Menu menu, Product product, long quantity) {
위에도 동일한 코멘트를 남겼지만, JPA를 사용하는데 id를 생성자를 통해 제어할 수 있으면 문제가 생길 수 있을 것 같아요.

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/dto/MenuProductResponse.java
> +        }
`MenuProduct`의 데이터베이스 상 제약 조건에 `product_id NOT NULL`이 지정되어 있습니다.

`!= null`을 체크하기보다는 null인 경우 예외를 던져야 할 것 같아요.

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +        return createMenuProducts;
stream.map을 이용해 불변으로 처리해보면 어떨까요?

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menu/dto/MenuResponse.java
> +        if (menuGroup != null) {
위와 동일하게 null인 경우는 데이터 정합성이 깨진 경우라 `!= null` 체크보다는 `null`인 경우를 찾아 예외를 반환해야 할 것 같아요.

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/order/domain/Order.java
> +    private OrderStatus orderStatus;
OrderStatus의 초기값을 default 값으로 넣어주면 어떨까요?

2021-01-20 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/order/dto/OrderRequest.java
> +                            .orElseThrow(IllegalArgumentException::new);
`Menu` 내부의 데이터를 꺼내기보다 메소드로 만들어 사용하면 어떨까요?

2021-01-20 14:05 UTC, kyucumber commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    ProductRepository productRepository;
테스트 내부 인스턴스 변수들도 접근 제한자를 붙여주면 어떨까요?

2021-01-20 14:05 UTC, kyucumber commented on src/test/java/kitchenpos/application/MenuServiceTest.java
>      @Mock
Mocking을 통해 서비스 레이어 테스트를 잘 작성해주셨습니다. 👍

2021-01-20 14:05 UTC, kyucumber commented on src/test/java/kitchenpos/application/TableServiceTest.java
>      void changeEmpty3() {
여러 케이스들을 꼼꼼하게 잘 체크해주셨네요 👍 

작성할 테스트의 양이 상당히 많은데 고생 많으셨습니다 ㅠㅠ

2021-01-20 14:05 UTC, kyucumber commented on src/test/java/kitchenpos/ui/TableGroupRestControllerTest.java
> -                        new OrderTable(2L ,2L, 0, true),
생성자에 아이디를 수정할 수 있도록 하는 부분에 대해 코멘트를 남겨드렸었는데

테스트 전반적으로 너무 많아서 수정하시려면 조금 어려움이 있을 듯 합니다 ㅠㅠ

적당히 참고만 해주시고 전부 다 반영하실 필요는 없습니다.

다만 JPA를 사용할 때 id를 외부에서 임의로 변경하거나 지정해 생성할 수 있는건 상당히 위험하니 참고만 해주시면 감사하겠습니다.


이미 DB에 1번의 아이디를 가진 Menu가 있는데 1번 아이디의 Menu가 생성되어 save에 전달되면 기존 1번 아이디의 Menu의 내용이 전부 바뀌어 버리거나 할 수 있어요.

2021-01-20 23:38 UTC, PilhwanKim commented on src/test/java/kitchenpos/ui/TableGroupRestControllerTest.java
> -                        new OrderTable(2L ,2L, 0, true),
아 넵 꼭 참고하겠습니다. 생각해보면 JPA 영속성이 ID기준인데 너무 test 위주로 남발한거 같네요.

2021-01-20 23:39 UTC, PilhwanKim commented on src/test/java/kitchenpos/application/TableServiceTest.java
>      void changeEmpty3() {
대신에 리팩토링할때는 든든했습니다.

2021-01-20 23:40 UTC, PilhwanKim commented on src/test/java/kitchenpos/application/MenuServiceTest.java
>      @Mock
any()를 대처할 만한 방법을 고민하다가 결국 verify로 대쳐했는데 잘 한거 같네요.

2021-01-20 23:42 UTC, PilhwanKim commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    ProductRepository productRepository;
오 넵~ 요런부분도 신경써야 하겠네요~! 보수적으로 접근해서 private 붙이겠습니다.

2021-01-20 23:44 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public List<MenuResponse> list() {
오! 맞어.. 이런건 습관이 들어야 할거 같네요. 정말 꿀리뷰네요. 감사합니다.

2021-01-20 23:46 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    }
으앗 :)  스텝마지막에 자체리뷰를 소홀이 한 흔적이 보이네요. :( 바로 반영하겠습니다.

2021-01-20 23:47 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    private Long seq;
엇 요건 sql 파일에 create table내용에 맞춰서 엔티티를 만들었었는데, 일단..dm으로 질문할게요

2021-01-20 23:48 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    public MenuProduct(Long seq, Menu menu, Product product, long quantity) {
헛 메인은 거의 이부분이군요. 넵 ㅠㅠ

2021-01-20 23:49 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +        return createMenuProducts;
넵~깔끔하게 정리할게요.

2021-01-20 23:50 UTC, PilhwanKim commented on src/main/java/kitchenpos/order/dto/OrderRequest.java
> +                            .orElseThrow(IllegalArgumentException::new);
저런식의 get끼리 비교도 리펙토링 대상으로 생각해야겠네요. 감사합니다.

2021-01-21 00:03 UTC, PilhwanKim commented on src/main/java/kitchenpos/order/domain/Order.java
> +    private OrderStatus orderStatus;
null 방지도 되고.. 생성할 때 실수를 없애기 위한 거군요. 넵!

2021-01-21 00:13 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/dto/MenuProductResponse.java
> +        }
엇 맞네요. not null 이라서 저럴 필요가 없었구나....
바로 고치겠습니다.

2021-01-21 00:27 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        menu.validateSumPrice(sumPrice);
오... 맞네요. 그리고 그렇게 하니깐 더 깔끔한 코드가 완성되었네요. 감사합니다.

2021-01-21 00:33 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/dto/MenuResponse.java
> +        if (menuGroup != null) {
넵 반영~!

2021-01-21 03:59 UTC, PilhwanKim commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    private Long seq;
DM 응답 감사합니다.

2021-01-21 14:42 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다~

다음 단계 진행을 위해 머지할게요

2021-01-21 14:42 UTC, merged