1단계 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #465
Opened 2022-06-16 12:16 UTC by chj1768

안녕하세요 리뷰어님 🙇 
1단계 PR 요청 드립니다. 
잘 부탁 드립니다.

2022-06-16 15:00 UTC, dhmin5693 commented
미션의 주제는 `레거시 코드 리팩토링`이에요. 리팩토링에 가장 중요한 건 무엇일까요?
기존 스펙을 정확히 이해하는 것입니다.
따라서 코드를 정확히 이해하고 검증하는 1단계 미션이 이번 미션에서 가장 중요하다고 할 수 있겠습니다.

저도 스펙을 하나하나 이해하기 위해 들여다보니 코드량이 워낙 많고 지루해서 조금 답답하더라구요.
이번 미션 자체가 답답하고 지루함을 유발할 수 있으니 미리 양해를 바랍니다. 😅

팁을 하나 드리자면 테스트를 작성하실 때 가장 상단의 실패 케이스부터 작성해주세요.
그리고 케이스 하나가 작성이 완료되면 test coverage를 확인합니다.
(인텔리제이 우측 상단에서 run 버튼 옆에 있는 방패 버튼입니다)

그러면 내 코드가 어디까지 검증했는지를 IDE를 통해 알 수 있어요.
테스트 코드가 지나간 부분은 녹색, 그렇지 않은 부분은 빨간색으로 표기됩니다.

![스크린샷 2022-06-16 23 59 09](https://user-images.githubusercontent.com/15965611/174099474-3cc33957-51f4-40ec-bd8b-f56df4842d82.png)

성공 케이스부터 작성하면 해당 로직의 대부분이 녹색으로 먼저 표기가 될거라 확인하기 어렵습니다.
그래서 실패 케이스부터 작성하시는걸 추천드렸어요.

2022-06-16 15:02 UTC, dhmin5693 requested changes
안녕하세요 현지님 🙇‍♂️
정식 미션에서 뵙게 되었네요. 반갑습니다.
이번 미션 완수까지 성심성의껏 도와드리도록 하겠습니다.

가급적 1단계 미션은 가급적 빠르게 merge를 해드리는 편이지만,
1단계가 이번 미션 중 가장 중요하다고 생각하기 때문에 조금 꼼꼼하게 리뷰를 남겨두었어요.

확인 후 다시 요청 부탁드릴게요. 🙏

2022-06-16 15:02 UTC, dhmin5693 commented on README.md
>  ## 요구 사항
잘 작성해주셨네요! 👍 

markdown이 렌더링되면 구분용으로 띄워두셨던 부분이 붙어서 나오게 됩니다.
별도의 소제목 등을 활용하여 도메인별 분류를 해주시면 더 좋을 것 같아요.

2022-06-16 15:02 UTC, dhmin5693 commented on README.md
> +  - 메뉴 구성품들의 가격 총합보다 메뉴 가격이 크거나 같으면 메뉴로 추가할 수 없다.
`메뉴 구성품`은 용어 사전에 없는 단어입니다.
`메뉴 상품`으로 대체하거나 용어 사전에 추가해주시면 확인하는 입장에서 용어를 헷갈리지 않을거에요.

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        Menu menu = new Menu();
테스트 준비를 위해 인스턴스를 생성하는 코드가 반복이 되고 있습니다.
`MenuFixture` 같은 별도의 클래스에서 관리해보시는건 어떤가요?

2022-06-16 15:02 UTC, dhmin5693 commented on README.md
> +  - 주문 항목은 1개 이상 있어야 한다.
`주문 항목`에 대한 설명도 용어 사전에 추가해주세요!

2022-06-16 15:02 UTC, dhmin5693 commented on README.md
> +  - 주문 테이블 조회 결과가 없으면 실패한다.
`주문 테이블 조회 결과가 없으면 실패한다` 
이 문구를 보고 스펙을 추측하기엔 어려워보여요.
그리고 주문 테이블이 비었을 때에 대한 설명이 누락되어 있으며 그 스펙은 테스트로도 작성이 되어 있지 않습니다.

`orderTableDao.findById` 를 활용하시는 걸 보고 이 문구를 작성하셨을 것 같아요.
코드에서 추측할 수 있는 정보를 나열해보겠습니다.

1. 주문은 테이블에서 이루어지며, 주문 테이블이라고도 한다.
2. 테이블은 현실 세계에서 `손님이 앉는 자리`를 의미한다.
3. 가게에서 사용할 수 있는 테이블은 주문을 받기 전에 시스템에 미리 등록되어 있어야 한다.

조금 더 이해하기 쉬운 문구로 대체해주세요.

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        assertThat(orderService.create(order)).isInstanceOf(Order.class);
`orderService.create(order)` 의 결과는 더 많은 것을 검증할 수 있습니다.

`Order` 가 생성되면 반드시 저장되는 정보가 여럿 있다는게 스펙으로 정해져 있어요.
스펙 상 데이터를 확실히 가지고 있는지를 검증해주세요.

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        Assertions.assertDoesNotThrow(() -> orderService.changeOrderStatus(0L, order));
이 메소드에서 검증한 요소는 `주문 변경을 시도했고 오류없이 종료되었다` 라고 볼 수 있습니다.
실제로 값이 잘 바뀌었는지도 검증해주세요,

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    @DisplayName("제품을 생성할 수 있다.")
용어 사전에 쓰인 용어로 통일해주세요.
용어가 혼용되면 타인이 이해하기 쉽지 않습니다.

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    @DisplayName("제품 가격이 자연수가 아니면 생성할 수 없다.")
자연수도 틀린 말은 아니지만 이 프로젝트 내에서 가격의 스펙을 지칭하는 문구를 하나만 쓰는 건에 대해서 어떻게 생각하시나요?

1. 자연수
2. null이거나 음수

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        assertThat(result).isNotNull();
여기도 상품에 저장된 데이터를 검증해줄 수 있지 않을까요?
`상품 생성 결과가 null이 아님`만 검증되어 있어요.

2022-06-16 15:02 UTC, dhmin5693 commented on README.md
> +- [X] 테이블 그룹을 생성할 수 있다.
`테이블 그룹에 포함하려는 주문 테이블은 시스템에 등록되어 있는 테이블만 가능하다`
이 스펙이 빠진 것 같아요. 테스트에도 추가해주세요.

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +    void ungroup() {
테이블 그룹에 속한 주문 테이블이 전부 소속 해제가 되는지 검증되지 않았습니다. (TableGroupService 의 84-85 라인)
중요한 스펙이므로 꼭 검증해주세요.

2022-06-16 15:02 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +    @DisplayName("orderTableId 가 조회되지 않으면 실패한다.")
displayName엔 가급적 원인과 결과를 포함하여 적어주세요.
현재 `조회되지 않으면 실패한다`로 설명이 되어 있는데요,
처음 보는 사람은 무엇이 실패하는지를 알려면 코드를 한줄 한줄 해석해야 하거든요.

테스트 코드는 검증과 함께 코드의 스펙을 이해할 수 있는 이정표의 역할도 수행해야 합니다.

2022-06-17 15:50 UTC, chj1768 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +    void ungroup() {
[e16d84a](https://github.com/next-step/jwp-refactoring/pull/465/commits/e16d84a8f53f9a093498a63826b15671efe745d1) 에서 검증 요소를 추가했습니다.

2022-06-17 16:45 UTC, chj1768 commented
@dhmin5693 
주신 코멘트별로 변경 커밋을 남기려고 했는데, 이번 PR 에는 전체적으로 변경한 부분들이 많아 일괄 변경사항 말씀드려요~ 🙇 

리뷰 반영 사항 목록

- 별도의 소제목 등을 활용하여 도메인별 분류
- 용어사전 기반의 일관된 키워드 사용하도록 수정
- test fixture 테스트별 추출
- 변경과 관련된 확인 테스트(생성, 수정)에 대한 검증 보완
-  누락되거나 중복된 스펙 테스트상 추가, 수정

2022-06-17 17:48 UTC, dhmin5693 commented on README.md
>  ## 요구 사항
잘 분리해주셨군요.
저번 피드백 때 남기지 않았는데, 가급적이면 기술적인 내용은 스펙에서 제외하는게 좋을 것 같아요.
이 문서는 개발자가 아닌 분들도 본다는 가정 하에 작성해주세요.

그런 느낌으로 `NULL` 보다는 "비어 있는" 같은 문구를 추천드립니다.

2022-06-17 17:54 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        Menu menu = new Menu();
조금 잘못 이해하신 것 같습니다.

테스트는 기본이 메소드마다 격리가 되고 있어서 가능성은 적으나
지금처럼 `Menu` 가 필드로 가게 되면 모든 테스트에서 공유하게 되어 예상치 못한 실패가 발생할 수 있어요.

테스트를 작성할 때 주로 하는 실수 중 하나가 setup 에 환경 설정 외의 작업을 추가하는 것입니다.
무슨 말이냐면, 각 테스트가 공유받을 수 있도록 필드로 내놓는건 테스트의 환경으로만 제한하고 setup에서 그 환경과 관련된 내용을 채워주는 것이죠.

각 테스트마다 필드 변수 `Menu`를 수정하고 있으며 그 필드를 검증까지 하고 있는데요,
이런 경우엔 보통 높은 확률로 테스트의 환경이 아니라 테스트의 조건에 해당합니다.
테스트의 조건은 확실히 격리시켜 다른 테스트에 영향을 미치지 않게끔 해주세요.

2022-06-17 17:59 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    @DisplayName("제품 가격이 자연수가 아니면 생성할 수 없다.")
위에 남겨두었듯 아무리 테스트라도 설명문은 개발자가 아닌 사람도 볼 수 있다고 생각하고
**가능하면** 기술적인 문구를 제외하는 방향으로 작성해주세요 :)

2022-06-17 18:01 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        assertThat(result).isNotNull();
아직 수정이 안된 것으로 보이는데요, 혹시 다른 아이디어가 있으셨던 것이라면 댓글을 남겨주세요 🙇‍♂️

2022-06-17 18:08 UTC, dhmin5693 commented on README.md
> +- [X] 테이블 그룹을 생성할 수 있다.
이름이 `테이블 그룹`에서 `단체 지정`으로 변경되었으나 해당 스펙이 추가되어 있지 않은 것 같습니다.

말로 설명하는 부분이기 때문에 확실한 정답이랄게 없습니다.
저는 `이미 등록되어 있는`이 중요하다고 생각했는데 보는 관점에 따라서 다를 수 있겠죠.
이를테면 여기서 사용하는 테이블은 기본적으로 `등록되어 있는` 상태를 가정할 수도 있으니까요.

현지님의 생각을 답글로 남겨주시면 감사하겠습니다 🙏

2022-06-17 18:15 UTC, dhmin5693 approved these changes
피드백 반영하시느라 고생 많으셨습니다.
1단계는 넘어가도 될 것 같아 merge하도록 하겠습니다.

다만 이전 피드백이 다 반영되지는 않은 것 같아요.
반영된 피드백은 resolve 처리했으니 아닌 것만 확인해주세요.
다음 미션 전에 반영 부탁드립니다. 🙏

그럼 다음 미션에서 뵈어요~ 👋

2022-06-17 18:15 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +class OrderServiceTest {
`OrderService` 에 검증되지 않은 스펙이 하나 있습니다. (60라인)
저번에 말씀드렸듯 test coverage를 활용해주시면 편리합니다.

2022-06-17 18:15 UTC, merged

2022-06-18 06:47 UTC, chj1768 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        assertThat(result).isNotNull();
ProductService 의 create 메서드 인데요. 요 테스트는 이 메서드의 happy case 확인 목적 입니다. 
요청한 product 의 가격 조건을 만족하면 그대로 저장되는 로직으로 보이는데요, 혹시 어떤 데이터를 추가 검증하면 좋을까요?? 👀 
```
@Transactional
    public Product create(final Product product) {
        final BigDecimal price = product.getPrice();

        if (Objects.isNull(price) || price.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException();
        }

        return productDao.save(product);
    }
```

2022-06-18 06:53 UTC, chj1768 commented on README.md
> +- [X] 테이블 그룹을 생성할 수 있다.
TableGroupService 부분의 요 로직 스펙 검증을 말씀주신게 맞을까요~? 
```
final List<OrderTable> savedOrderTables = orderTableDao.findAllByIdIn(orderTableIds);

        if (orderTables.size() != savedOrderTables.size()) {
            throw new IllegalArgumentException();
        }
```
요 부분이 맞다면
`요청한 주문 테이블 수와 실제 저장된 주문 테이블 갯수가 같아야 한다.` 로 케이스가 검증이 되어 있는데요, 혹시 다른 부분이면 말씀 부탁드릴게요 😭 (제가 다른 부분을 보고 있나 싶어요 ㅠㅠ)

2022-06-18 07:02 UTC, chj1768 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    @DisplayName("제품 가격이 자연수가 아니면 생성할 수 없다.")
https://github.com/next-step/jwp-refactoring/pull/465#discussion_r900390210
요 부분과 더불어 궁금한 점이 있어서 코멘트 남깁니다!!
`레거시 코드 리팩토링` 미션에서도 설명문(ReadMe) 열람 대상자가 개발자가 아닌 사람들도 모두 포함한 형태가 되어야 할까요~? 
이 미션은 개발자가 레거시 코드를 리팩토링 하고자 하는 상황에서 루틴하게 수행하는 사이클이라고 느껴 졌어요. 
서비스상에서의 결과는 동일하지만, 소스상의 내부 구조를 개선하는 일이니까 오히려 협업하는 개발자들에게 테스트 커버리지나, 소스상의 스펙 구현 키워드, 현재까지의 리팩토링 작업 상태를 잘 전달할 수 있는 문서의 형태가 되어야 하지 않을까? 생각이 들었습니다.
작업자인 저의 단순 생각입니다. 의견이 궁금합니다. 🙏

2022-06-18 07:11 UTC, chj1768 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        Menu menu = new Menu();
네 이해했습니다. 다음 미션에서 같이 고려해보겠습니다. 
현재 제가 작성한 테스트 코드의 상황으로는 
MenuFactory 클래스를 구성하게 된다면 테스트 케이스별로 
`Menu menu = new Menu();`
요 부분만 
`Menu menu = MenuFactory.create() ` 
의 형태로 대체되지 않을까 싶습니다. 필드별 setter 를 이용해서 테스트 케이스별 예외/성공 상황을 조작하고 있기 때문에요.
다음 단계에서 getter/setter 의 사용이 제거되면서 테스트 코드도 같이 영향 받아 변화할 수 있다는 생각이 들어요. 
챙겨서 개선 진행해 보겠습니다. 🙇 🙇

2022-06-18 07:15 UTC, chj1768 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +class OrderServiceTest {
```
 if (orderTable.isEmpty()) {
            throw new IllegalArgumentException();
        }
```
요 부분이군요. 확인했습니다. 다음 번에 추가해두겠습니다. 👍

2022-06-19 03:39 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        assertThat(result).isNotNull();
상품이 잘 저장되었다는건 상품의 이름, 가격 등이 의도한 대로 잘 저장되었느냐를 확인해야 하지 않을까요?

2022-06-19 11:08 UTC, chj1768 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        assertThat(result).isNotNull();
🙆‍♀️ 네 알겠습니다.