2단계 - 서비스 리팩터링
next-step/jwp-refactoring pull request #479
Opened 2022-06-22 17:13 UTC by chj1768

안녕하세요 리뷰어님. 
2단계 리뷰 요청 드립니다. 
자신이 없네요. ㅠㅠ 잘 부탁 드립니다.

2022-06-23 14:33 UTC, dhmin5693 requested changes
현지님 안녕하세요!

이번 미션은 전체적으로 양이 너무 많아서 복잡하고 머리아픈데도 잘 해주셨네요 :)
너무 자신없어 하실 필요는 없어요. 충분히 잘해주고 계십니다.

미션에서 요구하는 사항들에 대한 코멘트 위주로 몇 개 작성해보았어요.
확인 후 다시 요청주세요.

2022-06-23 14:33 UTC, dhmin5693 commented on README.md
> +    - 메뉴 가격이 비어 있거나 음수면 메뉴로 추가할 수 없다.
부정문보다는 긍정문을 읽을 때 뇌가 인식하기 쉽다고 하네요.
개발과는 관련 없지만 README와 같은 스펙문서(?) 작성 시 도움이 될까 하여 첨부해봅니다 :)
http://www.lecturernews.com/news/articleView.html?idxno=44207

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/application/MenuGroupService.java
>  package kitchenpos.application;
도메인 별로 패키지를 분리해주세요.

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/application/MenuService.java
>          BigDecimal sum = BigDecimal.ZERO;
저는 이 프로젝트에서 `BigDecimal`을 쓸 필요는 없다고 생각해요.
`BigDecimal`은 일반 숫자형에 비해 쓰기도 어렵고 이게 꼭 필요한 만큼 큰 숫자는 다루지 않을 프로젝트거든요.
가격(price)를 포함한 모든 숫자는 `Long` 으로 표현하는건 어떨까요?

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/dto/MenuRequest.java
> +    public void check(BigDecimal price) {
이 메소드는 서비스 내에서 비즈니스 로직을 검증하기 위해 쓰이고 있어요.
dto는 validation 외의 비즈니스 로직을 포함하지 않아야 합니다.

이 역할은 다른 클래스로 옮겨보는게 어떨까요?

메소드명도 조금 더 내용을 드러낼 수 있으면 좋을 것 같아요.

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/dto/MenuProductRequest.java
> +    public MenuProductRequest(@JsonProperty("productId") long productId, @JsonProperty("quantity") long quantity) {
`@JsonCreator`, `@JsonProperty` 를 사용한 이유가 궁금합니다.

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    public TableGroupResponse create(final TableGroupRequest request) {
프로그래밍 요구사항을 지켜주세요!
> 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +            if (!savedOrderTable.isEmpty() || savedOrderTable.hasTableGroup()) {
여기도 요구사항을 지켜주세요.
> indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/application/MenuService.java
> +        MenuGroup menuGroup = menuGroupRepository.findById(request.getMenuGroupId()).orElseThrow(IllegalArgumentException::new);
프로젝트 전체적으로 `IllegalArgumentException` 이 너무 과도하게 사용되고 있어요.
일부는 적절한 예외를 정의해서 사용하는건 어떨까요?
예외를 쉽게 이해할만한 적절한 메시지도 함께 던지면 더 좋습니다.

2022-06-23 14:33 UTC, dhmin5693 commented on src/main/java/kitchenpos/application/TableGroupService.java
>          if (CollectionUtils.isEmpty(orderTables) || orderTables.size() < 2) {
프로그래밍 요구사항을 지켜주세요.
> 모든 원시 값과 문자열을 포장한다.

2022-06-23 14:33 UTC, dhmin5693 commented on src/test/java/kitchenpos/application/OrdersServiceTest.java
> +    void create() {
실패하는 테스트입니다. 성공하도록 변경해주세요.

2022-06-23 18:49 UTC, chj1768 commented on src/main/java/kitchenpos/application/MenuService.java
> +        MenuGroup menuGroup = menuGroupRepository.findById(request.getMenuGroupId()).orElseThrow(IllegalArgumentException::new);
[e1779ed](https://github.com/next-step/jwp-refactoring/pull/479/commits/e1779ed3993980d1d232b2063cbd01f8bc4c2560)
에서 상황별 exception 을 분리했어요. 
```
repository 조회 시 조회되지 못한 경우 -> NoSuchElementEx 
이름, 가격 validation 실패 -> InvalidPriceEx, InvalidNameEx
그 외 IllegalArgumentException 사용. 적절한 메시지 내용 추가 
```

2022-06-23 18:50 UTC, chj1768 commented on src/main/java/kitchenpos/application/TableGroupService.java
>          if (CollectionUtils.isEmpty(orderTables) || orderTables.size() < 2) {
[44f539e](https://github.com/next-step/jwp-refactoring/pull/479/commits/44f539ed61057467ae72cde09d85955170d95b7a) 에서 해당 서비스 로직을 변경해봤어요. 
https://github.com/next-step/jwp-refactoring/pull/479#discussion_r905085559
https://github.com/next-step/jwp-refactoring/pull/479#discussion_r905085046
요 코멘트 사항도 포함하여 수정되었습니다. 🙇

2022-06-23 18:50 UTC, chj1768 commented on src/test/java/kitchenpos/application/OrdersServiceTest.java
> +    void create() {
[2b7f90d](https://github.com/next-step/jwp-refactoring/pull/479/commits/2b7f90dcf4482d4c700b0c5e592dd1a38242ed3a) 에서 변경해주었어요.

2022-06-23 18:54 UTC, chj1768 commented on src/main/java/kitchenpos/dto/MenuProductRequest.java
> +    public MenuProductRequest(@JsonProperty("productId") long productId, @JsonProperty("quantity") long quantity) {
json 포맷으로 메시지 de/serialize 시 내부적으로 사용하는 jackson 라이브러리 에서 디폴트 생성자를 요구 하더라구요. 
어노테이션으로 지정해주게 되면 별도의 디폴트 생성자 없이 해당 생성자를 이용 가능해서 사용해 보았습니다.

2022-06-23 18:54 UTC, chj1768 commented on src/main/java/kitchenpos/dto/MenuRequest.java
> +    public void check(BigDecimal price) {
[82a2835](https://github.com/next-step/jwp-refactoring/pull/479/commits/82a2835ff2efa192e4827761a9374a2155f88a8e) 요 커밋에서 가격 검증 로직을 옮겼어요~

2022-06-23 18:55 UTC, chj1768 commented on src/main/java/kitchenpos/application/MenuGroupService.java
>  package kitchenpos.application;
[614df4d](https://github.com/next-step/jwp-refactoring/pull/479/commits/614df4d027aafb5b59a7037ad34c4af2309bf314) 에서 전체적으로 변경해 주었습니다.

2022-06-23 18:56 UTC, chj1768 commented on README.md
> +    - 메뉴 가격이 비어 있거나 음수면 메뉴로 추가할 수 없다.
[2bb19d4](https://github.com/next-step/jwp-refactoring/pull/479/commits/2bb19d45ad785e4dbcf879f1654b12825780926d) 에서 자연수 로 키워드 변경해 보았습니다.

2022-06-23 18:57 UTC, chj1768 commented on src/main/java/kitchenpos/application/MenuService.java
>          BigDecimal sum = BigDecimal.ZERO;
좋습니다. [db0fe26](https://github.com/next-step/jwp-refactoring/pull/479/commits/db0fe266ecde455b9a000cbb6838b1214143e3c0) 에서 전체적으로 변경해 보았습니다.

2022-06-24 13:36 UTC, dhmin5693 commented on src/main/java/kitchenpos/dto/MenuProductRequest.java
> +    public MenuProductRequest(@JsonProperty("productId") long productId, @JsonProperty("quantity") long quantity) {
그렇군요 :)
저는 모든 필드에 `@JsonProperty`를 쓰는게 더 귀찮다고 생각해서 기본 생성자를 쓸 것 같아요.

2022-06-24 14:15 UTC, dhmin5693 requested changes
새벽 3시라니... 늦은 시간까지 정말 열심히 해주셨네요 :)

바로 merge하고 싶은데 저번에 남겨드린 코멘트 중 프로그래밍 요구사항이 딱 하나가 충족되지 않고 있습니다 ㅠㅠ
그래서 수정하시는 겸 생각해볼만 코멘트 몇 개 남겨두었으니 같이 확인 부탁드릴게요!

2022-06-24 14:15 UTC, dhmin5693 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +        this.createdDate = LocalDateTime.now();
기본 생성자에 넣기보다는 audit 기능을 사용해보는건 어떤가요?

2022-06-24 14:15 UTC, dhmin5693 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +            if (!orderTable.isEmpty() || orderTable.hasTableGroup()) {
여기도 2depth 로 구성되어 있어요.

2022-06-24 14:15 UTC, dhmin5693 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +        return new TableGroup();
`TableGroup` 의 스펙 자체가 orderTable 2개 이상을 요구하고 있습니다.
empty는 불필요하지 않을까요?

2022-06-24 14:15 UTC, dhmin5693 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +    public static TableGroup group(OrderTables orderTables) {
여기 있는 로직들은 `TableGroup`의 스펙 상 생성자에 위치하는게 더 적절할 것 같아요.
이 메소드를 생성자로 바꾸면 어떨까요?

2022-06-26 11:46 UTC, chj1768 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +            if (!orderTable.isEmpty() || orderTable.hasTableGroup()) {
[50c2a8a](https://github.com/next-step/jwp-refactoring/pull/479/commits/50c2a8a0c99f56f2ea155ce3a05640800ee61e28) 
요 부분 수정되었습니다~

2022-06-26 11:47 UTC, chj1768 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +        this.createdDate = LocalDateTime.now();
[50c2a8a](https://github.com/next-step/jwp-refactoring/pull/479/commits/50c2a8a0c99f56f2ea155ce3a05640800ee61e28) 에서 같이 적용했어요.

2022-06-26 11:51 UTC, chj1768 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +    public static TableGroup group(OrderTables orderTables) {
어떤 상황에서 생성자가 적절하고, 어떤 상황에서는 static 팩토리 메서드가 적절할지 궁금해요. 
요 말씀을 주신 이유는
https://github.com/next-step/jwp-refactoring/pull/479#discussion_r906082850
empty 상황이 불필요하기 때문에 생성자를 일원화할수 있기 때문일까요?

2022-06-26 12:24 UTC, dhmin5693 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +    public static TableGroup group(OrderTables orderTables) {
정적 팩토리 메소드를 잘 정리한 글입니다. 한번 읽어보세요 :)
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method

---

제가 피드백 드린 이유를 말씀드릴게요.

첫 번째로 group이라는 이름이 이 메소드를 잘 나타내지 못한다고 생각했어요.
`OrderTables` 를 모은다는 의미는 잘 전달이 되는데, 결국 그렇게 하는 이유는 `TableGroup`의 생성이거든요.
group으로는 인스턴스를 생성한다는 의미를 주기 어렵다고 느꼈습니다.
그래서 보통은 from이나 of, create 같은 명칭을 많이 사용합니다.

두 번째로는 `group` 의 로직이 그 객체를 정의한다는 느낌을 주고 있어서입니다.
저는 공통적이고 필수적인 로직은 생성자에 넣고 정적 팩토리 메소드에는 파싱 정도만 남겨둡니다.
팩토리에는 정말 최소한의 로직만 넣어두는 거죠.
팩토리는 정말 다양한 경로로 생성하게끔 만들어 둘 수 있습니다. 그렇기 때문에 팩토리에서 객체를 생성하는 경로는 최소한으로 줄여둡니다.
객체를 정의한다고 말할 수 있는 생성자를 통하게 만드는게 객체 설계 면에서 더 합리적이라고 생각하기 때문입니다.

지금은 팩토리 메소드에서 객체를 정의하고 있는데요,
`List<OrderTable> ordertables`를 매개변수로 받는 팩토리 메소드를 하나 더 만든다면 로직이 중복되지 않을까요?

두 가지를 말씀드렸지만 써놓고 보니 두 번째 이유가 전부고 첫번째는 부가적인 내용인 것 같네요.
약간은 주관적인 기준이라 잘 이해가 안되셨을 수도 있겠군요.

2022-06-26 12:29 UTC, dhmin5693 approved these changes
피드백 잘 반영해주셨네요. 다음 미션 진행해주세요 :)
질문에 대한 답변 남겨두었으니 확인 부탁드립니다.
고생하셨습니다.

2022-06-26 12:29 UTC, dhmin5693 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +        return new TableGroup();
여기는 꼭 제거해주세요.
객체를 불완전하게 만드는 통로가 됩니다.

2022-06-26 12:29 UTC, dhmin5693 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +    public static TableGroup group(OrderTables orderTables) {
정적 팩토리 메소드를 잘 정리한 글입니다. 한번 읽어보세요 :)
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method

---

제가 피드백 드린 이유를 말씀드릴게요.

첫 번째로 group이라는 이름이 이 메소드를 잘 나타내지 못한다고 생각했어요.
`OrderTables` 를 모은다는 의미는 잘 전달이 되는데, 결국 그렇게 하는 이유는 `TableGroup`의 생성이거든요.
group으로는 인스턴스를 생성한다는 의미를 주기 어렵다고 느꼈습니다.
그래서 보통은 from이나 of, create 같은 명칭을 많이 사용합니다.

두 번째로는 `group` 의 로직이 그 객체를 정의한다는 느낌을 주고 있어서입니다.
저는 공통적이고 필수적인 로직은 생성자에 넣고 정적 팩토리 메소드에는 파싱 정도만 남겨둡니다.
팩토리에는 정말 최소한의 로직만 넣어두는 거죠.
팩토리는 정말 다양한 경로로 생성하게끔 만들어 둘 수 있습니다. 그렇기 때문에 팩토리에서 객체를 생성하는 경로는 최소한으로 줄여둡니다.
객체를 정의한다고 말할 수 있는 생성자를 통하게 만드는게 객체 설계 면에서 더 합리적이라고 생각하기 때문입니다.

지금은 팩토리 메소드에서 객체를 정의하고 있는데요,
`List<OrderTable> ordertables`를 매개변수로 받는 팩토리 메소드를 하나 더 만든다면 로직이 중복되지 않을까요?

두 가지를 말씀드렸지만 써놓고 보니 두 번째 이유가 전부고 첫번째는 부가적인 내용인 것 같네요.
약간은 주관적인 기준이라 잘 이해가 안되셨을 수도 있겠군요.

2022-06-26 12:29 UTC, merged

2022-06-26 12:36 UTC, chj1768 commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +    public static TableGroup group(OrderTables orderTables) {
@dhmin5693 
주신 피드백 이해했습니다. 말씀주신 이유도 공감합니다. 🙇  
상세하게 설명해 주셔서 감사해요. 다음 PR 에서 같이 적용해보겠습니다.