[Step2] 서비스 리팩터링
next-step/jwp-refactoring pull request #49
Opened 2021-01-20 10:41 UTC by slamdunk7575

안녕하세요😃  현구님.

이번 미션인 리팩토링은 연관된 도메인들 끼리 묶고
`서비스 레이어`의 `비지니스 로직`을 `Domain`으로 최대한 옮기도록 하였습니다. 
리팩토링 하면서 포비가 말씀하신 것처럼 극단적으로 원시값을 포장하고 일급 컬렉션을 적용해보며 
상태와 행위를 관리하도록 해봤습니다.😄 

공부하는 김에 이번엔 테스트를 `@SpringBootTest`를 사용해봤는데요.
DB에 접근하여 데이터를 눈으로 확인할 수는 있지만,` ApplicationContext`가 매번 올라가면서 시간을 소모하고
DB 데이터를 관리해야 한다는 점을 느꼈고 상황에 따라 `Mocking`을 통한 테스트와 같이 활용을 해야할 거 같습니다.😅 

프로젝트 구조 전체를 리팩토링 하는거라 양이 많네요.
사소한 부분이라도 코멘트 남겨주시면 열심히 반영해보겠습니다.  
리뷰 잘 부탁드립니다~ 감사합니다.🙇

2021-01-21 13:36 UTC, kang-hyungu requested changes
경준님 구현하신 코드 확인했습니다
도메인 코드 깔끔하게 구현 잘 하셨어요 👍 
몇 가지 간단한 피드백 남겼으니 참고해서 반영해보아요
궁금한 점 생기면 dm 주시거나 코멘트 남겨주세요

2021-01-21 13:36 UTC, kang-hyungu commented on src/main/java/kitchenpos/common/Price.java
> +    public Price() {
public으로 생성자를 열어둘 이유가 없다면 protected로 변경하는게 좋겠네요

2021-01-21 13:36 UTC, kang-hyungu commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        for (MenuProductRequest menuProduct : menuProductRequests) {
productRepository.findAllById를 사용하면 쿼리 호출 횟수를 줄일 수 있지 않을까요

2021-01-21 13:36 UTC, kang-hyungu commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        return OrderResponse.of(orderRepository.save(savedOrder));
orderRepository.save는 사용하지 않아도 자동으로 update 구문 동작하지 않나요?

2021-01-21 13:36 UTC, kang-hyungu commented on src/main/java/kitchenpos/order/application/TableGroupService.java
> +        tableGroupRepository.save(tableGroup);
이부분도 save를 따로 안해도 update 구문이 동작할거에요

2021-01-21 13:36 UTC, kang-hyungu commented on src/main/java/kitchenpos/order/domain/OrderTables.java
> +        if (orderTables.stream().anyMatch(OrderTable::isNotComplete)) {
orderTables.stream().anyMatch(OrderTable::isNotComplete)
이부분은 변수나 메서드로 따로 빼는게 좋겠네요

2021-01-21 13:36 UTC, kang-hyungu commented on src/main/java/kitchenpos/order/domain/Order.java
> +        private OrderTable checkValidTable(OrderTable orderTable) {
유효성 검사는 builder가 아닌 생성자에서 처리하는게 맞지 않을까요?
유효성 검사는 builder에서 맡을 역할은 아니라고 생각됩니다.

2021-01-21 14:39 UTC, slamdunk7575 commented on src/main/java/kitchenpos/common/Price.java
> +    public Price() {
앗 수정하겠습니다 👀

2021-01-21 14:57 UTC, slamdunk7575 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        for (MenuProductRequest menuProduct : menuProductRequests) {
`findAllById`로 한번에 조회해서 쿼리를 줄일 수 있겠네요. 꼼꼼한 리뷰 감사합니다 👍

2021-01-21 15:08 UTC, slamdunk7575 commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        return OrderResponse.of(orderRepository.save(savedOrder));
`Dirty Checking `하여 반영되겠네요. 왜 이걸 생각을 못 했는지..
꼼꼼한 리뷰 감사합니다 👍

2021-01-21 15:08 UTC, slamdunk7575 commented on src/main/java/kitchenpos/order/domain/OrderTables.java
> +        if (orderTables.stream().anyMatch(OrderTable::isNotComplete)) {
수정하겠습니다 👍

2021-01-21 15:18 UTC, slamdunk7575 commented on src/main/java/kitchenpos/order/domain/Order.java
> +        private OrderTable checkValidTable(OrderTable orderTable) {
현구님 말씀대로 `Builder`는 객체를 만드는 역할만 담당하고
생성자에서 `유효성 검사`를 하는게 맞겠네요. 👍

2021-01-22 11:40 UTC, kang-hyungu approved these changes
경준님 피드백 반영 잘 하셨어요 👍 
다음 미션 진행을 위해 pr은 머지 처리할게요
수고하셨습니다

2021-01-22 11:40 UTC, merged