1단계 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #501
Opened 2022-06-26 10:05 UTC by handh0413

재석 리뷰어님 안녕하세요 😀
이번 미션과 관련하여 리뷰 요청을 드리게 된 한동희라고 합니다.
잘 부탁드립니다!

이번 단계에서는 테스트 코드를 추가하여 기존 기능을 검증할 수 있도록 하였습니다.
이번 단계에서는 기능이 서비스 레이어에 집중되어 있는 상태라서,
도메인 클래스에 대한 테스트 코드는 별도 작성하지 못했습니다.
그래서 인수 테스트를 작성하여 시스템 프로세스를 검증할 수 있는 방향으로 진행하였습니다.

시간 여유 되실 때 리뷰 부탁드립니다. 🙏
감사합니다!

2022-06-26 10:43 UTC, seok-2-o requested changes
안녕하세요. 이번 미션을 함께하게 된 이재석입니다.

인수테스트를 잘 작성해주셨네요. 다만 이번 미션의 요구사항은 아래와 같습니다.
> 정리한 키친포스의 요구 사항을 토대로 테스트 코드를 작성한다. 모든 Business Object에 대한 테스트 코드를 작성한다. @SpringBootTest를 이용한 통합 테스트 코드 또는 @ExtendWith(MockitoExtension.class)를 이용한 단위 테스트 코드를 작성한다.
인수 테스트 코드 작성은 권장하지만 필수는 아니다. 미션을 진행함에 있어 아래 문서를 적극 활용한다.

어려우시더라도 비지니스 레이어에 대한 테스트 작성을 시도해보시는것을 권장드립니다.

저와 의견이 다르거나 궁금한점 어려운 점 있으면 편하게 말씀해주세요.
그럼 잘 부탁드리겠습니다.

2022-06-26 10:43 UTC, seok-2-o commented on README.md
> +### 상품(Project)
요구사항 정의 👍

2022-06-26 10:43 UTC, seok-2-o commented on README.md
> +### 상품(Project)
```suggestion
### 상품(Product)
```

2022-06-26 16:38 UTC, handh0413 commented on README.md
> +### 상품(Project)
바로 수정하겠습니다! 감사합니다

2022-06-26 16:38 UTC, handh0413 commented on README.md
> +### 상품(Project)
감사합니다!

2022-06-27 09:00 UTC, handh0413 commented
미션 진행 방법에 있어서 이해를 못해서 Mock을 이용한 테스트를 누락하였습니다. 😭
추가로 작성해서 리뷰 요청 드립니다!
시간 여유 되실 때 한번 리뷰 부탁드립니다! 🙏

2022-06-27 11:23 UTC, seok-2-o approved these changes
테스트코드 작성잘해주셨네요 👍 
이번에 작성하신 테스트를 바탕으로 다음 미션에서 코드가 얼마나 보호되는지
함께 진행해보아요 🔥

2022-06-27 11:23 UTC, seok-2-o commented on src/test/java/kitchenpos/menu/service/MenuServiceTest.java
> +public class MenuServiceTest {
stub 을 이용한 Service 계층 단위 테스트는 테스트가 구현부를 상세하게 의존하기 때문에 구현 코드의 변경에 민감하게 반응할 것 같아요. 또한 모킹으로 인하여 실제 프러덕션 코드가 수정되어도 버그를 인지하지 못할 수 있을 것 같아요. 지금과 같은 테스트코드에는 어떤 의미가 있을까요?

2022-06-27 11:23 UTC, seok-2-o commented on src/test/java/kitchenpos/menugroup/application/MenuGroupServiceTest.java
> +        assertThat(created.getId()).isNotNull();
assertAll() 을 활용하면 중간에 테스트가 실패하더라도 모든 테스트를 수행한 뒤 결과를 받아볼 수 있어요.

2022-06-27 11:23 UTC, merged

2022-06-30 11:24 UTC, handh0413 commented on src/test/java/kitchenpos/menu/service/MenuServiceTest.java
> +public class MenuServiceTest {
서비스 계층에 있던 로직들이 도메인으로 넘어가게되면서 기존에 만들어놓은 모킹 기반 테스트 코드를 빈번하게 수정해야 하는 일이 많이 있었습니다. 이런 부분들이 단점으로 느껴졌지만.. 2단계를 진행하면서 테스트 코드 덕분에 많은 도움을 받아서 단점만 있는 것은 아니라고 생각합니다. 코드 변화에 영향을 크게 받지 않는 테스트 방법을 고민해봐야겠습니다.

2022-06-30 11:26 UTC, handh0413 commented on src/test/java/kitchenpos/menugroup/application/MenuGroupServiceTest.java
> +        assertThat(created.getId()).isNotNull();
공유해주셔서 감사합니다!