Step3- 의존성 리팩터링
next-step/jwp-refactoring pull request #510
Opened 2022-06-27 09:45 UTC by june2

안녕하세요. 영훈님~

3단계 미션 완료해서 pr드립니다.! 리뷰부탁드려요

---
## 기능 정리

- 클래스 다이어그램
![image](https://user-images.githubusercontent.com/5827617/175910976-2f560a1a-3b32-4396-b28b-2b866054c726.png)

- 객체 간 단방향 관계로 변경
    - menuValidator 생성
    - orderValidator 생성
- 직접 참조 -> 간접 참조 개선   
  - MenuProduct -> Product id 참조 변경
  - OrderTable -> TableGroup id 참조 변경
- 단체 지정(tableGorup) 이벤트 처리
   - 단체 지정 등록
   - 단체 지정 해제

--- 
## 질문
- event 처리를 하다보니 단위테스트 작성이 불가해보이는데 이부분은 어떻게 처리 할수 있나요??

2022-06-28 22:41 UTC, chae-yh requested changes
준영님 안녕하세요! step3 도 전체적으로 코드 잘 작성해주셨습니다!
다만, 질문해주신 내용과 조금만 더 고민해주시면 좋을만한 내용이 있어 코멘트 드리니 확인 부탁드립니다!

감사합니다 : )

2022-06-28 22:41 UTC, chae-yh commented on README.md
> +- 3단계 (의존성 리팩터링)
기능 구현 목록 작성 좋습니다 👍 
클래스 다이어그램 그려준 것도 인상깊네요 ㅎㅎ

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +//    }
사용하지 않는다면 지워도 좋을 것 같습니다!

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/table/event/GroupByEventHandler.java
> +public class GroupByEventHandler {
질문 주신 내용 여기서 답변 드리겠습니다!
`
event 처리를 하다보니 단위테스트 작성이 불가해보이는데 이부분은 어떻게 처리 할수 있나요??
`

Handler 의 단위 테스트의 경우 GroupByEvent를 만들어 groupByEvent 메서드에 데이터를 전달하는 형식으로 테스트 작성이 가능할 것 같습니다. 외부 의존성이 이슈가 된다면 Mocking으로 해결할 수 있을 것으로 보입니다.
특히 여기 메서드는 데이터를 update 하는 테스트로 보이는데, 실제 데이터가 반영된 것을 기준으로도 테스트가 가능할 것으로 보입니다!

혹시 문의 주신 부분이 이것이 맞을까요...? 우선 위와 같이, 저는 데이터 전달 형식이 api 혹은 event 라고 하더라도 단위 테스트 작성과는 영향이 없다고 생각합니다. 혹시 제가 다르게 이해하고 있거나 다른 의견이 있으시면 말씀부탁드립니다!

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/table/event/GroupByEventHandler.java
> +    public void groupByEvent(GroupByEvent event) {
여기에도 하나의 트랙잭션에서 실행되어야 할 것 같아, Transactional 이 있으면 좋을 것 같습니다!

2022-06-28 22:41 UTC, chae-yh commented on README.md
> +    - OrderTable -> TableGroup id 참조 변경
Menu가 만들어질 때 product의 영향이 없어야 하므로, 간접 참조로 바꾸신 것 같습니다. 또한 Order가 만들어질 때 Menu의 변화에 영향을 받아선 안되므로 간접참조가 맞아 보입니다
Table과 TableGroup사이는 직접 참조도 괜찮아보이는데 혹시 간접 참고로 하신 이유가 있으실까요...? 맞다 / 틀리다의 개념보다는 의견이 궁금하여 여쭤봅니다!

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/menu/domain/MenuValidator.java
> +public class MenuValidator {
재밌는 개념으로 도메인 잘 추출 해주셨네요 ㅎㅎ

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/table/event/GroupByEventHandler.java
> +    @EventListener
현재 구조에서는 특별히 이슈가 없을 것 같습니다만, 해당 이벤트를 publish하는 메서드에도 @Transactional이 걸려있습니다. publish 하는 쪽의 트랜잭션과 같이 묶어야 한다면 @TransactionalEventListener 도 사용해볼 수 있을 것 같습니다!

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/table/event/UngroupEventHandler.java
> +    public void onUngroupEvent(UngroupEvent event) {
여기도 @Transactional이 있으면 좋을 것 같습니다!

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/tablegroup/application/TableGroupService.java
> +    @Transactional
여기서는 데이터베이스 작업이 하나도 없는데 @Transactional가 필요한가요...?

2022-06-28 22:41 UTC, chae-yh commented on src/test/java/kitchenpos/tablegroup/application/TableGroupServiceTest.java
> +public class TableGroupServiceTest {
TableGroupService에 대한 단위 테스트 좋네요 👍 다만 ungroup 같은 경우 이벤트를 발행하는 역할밖에 없는데, 테스트를 해당 handler 테스트에 추가하거나 실제로는 domain로직을 확인하는 부분이므로, domain 테스트를 추가하여 해당 테스트에 넣는 것은 어떨까요...?

2022-06-28 22:41 UTC, chae-yh commented on src/main/java/kitchenpos/tablegroup/event/GroupByEvent.java
> +package kitchenpos.tablegroup.event;
Event와 해당 Handler를 event 패키지에 두셨는데, 관련하여 의견 여쭤보고 싶은 부분이 있습니다. 저희가 전통적인 layered architecture(domain-service-controller)를 이용하여 학습을 하고 있는데, 이 경우는 어떤 패키지에 넣으면 좋을까요...?

2022-06-29 00:33 UTC, june2 commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +//    }
넵 주석삭제를 깜빡했네요 ㅜ

2022-06-29 00:34 UTC, june2 commented on src/main/java/kitchenpos/table/event/GroupByEventHandler.java
> +    public void groupByEvent(GroupByEvent event) {
넵 이벤트쪽에 트랜잭션이 다 빠졋네요 ㅜ 추가하겠습니다.

2022-06-29 00:45 UTC, june2 commented on src/main/java/kitchenpos/tablegroup/application/TableGroupService.java
> +    @Transactional
네, 이벤트핸들러로 메소드 옮기면서 db작업이 사라졌네요. @transactional 삭제하겠습니다.

2022-06-29 00:51 UTC, june2 commented on src/main/java/kitchenpos/table/event/GroupByEventHandler.java
> +    @EventListener
넵 해당 개념 리서치해보고 적용했습니다.
https://sunghs.tistory.com/139

2022-06-29 05:54 UTC, june2 commented on src/main/java/kitchenpos/tablegroup/event/GroupByEvent.java
> +package kitchenpos.tablegroup.event;
네~ 고민을 하다가 전통적인 layered에 포함을 시키지 않고 event package를 추가하였습니다.

추가하게 된 배경은  아래와 같에요!
1. event비동기 처리가 된다는 것을 명확하게 알수 있게하기위함이었습니다.
2. folder structure 사례를 참고를 많이 해봤는데요. event / eventHandler 이렇게 2개 패키지명으로 따로 관리하는 프로젝트가 다수 였는데요. 2가지로 세분화하기보다 event라는 패키지명으로 관리하는 부분이 명확하고간결할거 같다고 생각을 했습니다. 

만약 layered architecture 구조로 관리가 되어야한다면, 기존 service layer에 존재했던 코드를 분리 시킨거이기에 service layer에 위치해야 되지 않을까 싶습니다.!

2022-06-29 05:58 UTC, june2 commented on src/test/java/kitchenpos/tablegroup/application/TableGroupServiceTest.java
> +public class TableGroupServiceTest {
`event 처리를 하다보니 단위테스트 작성이 불가해보이는데 이부분은 어떻게 처리 할수 있나요??`

아! 이부분의 질문이 여기서 해결됬습니다. 
event를 분리하다보니 실패 케이스에대한 유효성검증 로직은 eventHandler에서 비동기로 처리되다보니
TableGroupServiceT에서 실패케이스 단위테스트 작성이 불가해 보였습니다.

피드백 주신대로 해당 evenHandler에서 단위테스트코드 작성을 하면 될거같네요!!

2022-06-29 06:18 UTC, june2 commented on README.md
> +    - OrderTable -> TableGroup id 참조 변경
네, OrderTable 생성시에는 다른 도메인과 다르게 영향을 끼치는 부분이 없으므로 직접참조로 해야할까 고민을 했었는데요. 

간접참고로 변경한 이유를 정리해서 말씀드리자면, 
1. table 단체지정 등록/해제시 이벤트를 발생시켜 비동기로 처리가 되다보니 간접참조로 의존성을 낮춰야겠다 생각했습니다. 
2. 패키지 레벨로서도 분리를 시켜서 다음단계 멀티 모듈적용 미션에서 해당 컨텍스트를 독린된 모듈로 만들어야겠다 생각했습니다.

2022-06-29 17:37 UTC, chae-yh approved these changes
준영님 안녕하세요! 피드백 잘 반영해주셨습니다 👍 미션 목적을 잘 달성해주셨다고 생각하여 이만 merge 하겠습니다. 

이제 마지막 step 만 남았네요! 파이팅 입니다 : )

2022-06-29 17:37 UTC, chae-yh commented on src/test/java/kitchenpos/table/event/GroupByEventHandlerTest.java
> +public class GroupByEventHandlerTest {
피드백 반영 및 handler에 대한 테스트 코드도 좋습니다 👍

2022-06-29 17:37 UTC, merged