Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #522
Opened 2022-06-28 17:44 UTC by geunhwanlee

안녕하세요!

이번 미션은 굉장히 할 게 많았네요😂

가장 힘들었던 점은
서비스 계층을 리팩터링 하면서 비즈니스 로직이 도메인 계층으로 이동하면서 굉장히 많은 코드가 변경 되었는데
1단계 때 작성했던 서비스 테스트코드는 테스트 더블을 사용한 고립 테스트였기 때문에 서비스 계층의 구현에 의존적이고
그렇기 때문에 서비스 테스트코드 역시 굉장히 많이 변경해야 하는 점이 힘들었습니다😭

그 과정에서 기존의 서비스계층이 테스트코드에 보호받지 못하고
오히려 테스트코드와 서비스계층을 같이 리팩터링하는 느낌을 받았습니다..🤔

오히려 통합 테스트코드를 작성하는 것이 더 낫지 않았을까.. 라는 생각을 했습니다

이슬님은 어떻게 생각하시는지 궁금합니다🙏

그럼 2단계 미션 잘 부탁드립니다!🙇🏻‍♂️

2022-06-29 13:16 UTC, parkeeseul requested changes
2단계 미션 질 진행해 주셨네요! 👍 
몇 가지 코멘트와 질문주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드립니다!
미션 화이팅 입니다 🔥

2022-06-29 13:16 UTC, parkeeseul commented on README.md
>  ## 요구 사항
> Q. 가장 힘들었던 점은
> 서비스 계층을 리팩터링 하면서 비즈니스 로직이 도메인 계층으로 이동하면서 굉장히 많은 코드가 변경 되었는데
> 1단계 때 작성했던 서비스 테스트코드는 테스트 더블을 사용한 고립 테스트였기 때문에 서비스 계층의 구현에 의존적이고
> 그렇기 때문에 서비스 테스트코드 역시 굉장히 많이 변경해야 하는 점이 힘들었습니다😭
> 
> 그 과정에서 기존의 서비스계층이 테스트코드에 보호받지 못하고
> 오히려 테스트코드와 서비스계층을 같이 리팩터링하는 느낌을 받았습니다..🤔
> 
> 오히려 통합 테스트코드를 작성하는 것이 더 낫지 않았을까.. 라는 생각을 했습니다
> 
> 이슬님은 어떻게 생각하시는지 궁금합니다🙏
> 

A. 좋은 고민을 해주셨네요! 👍 
말씀하신 것 처럼 Mock 객체를 사용해 테스트 코드를 작성하게 되면 
테스트 코드를 작성할때 구현을 알고 있어야 하기 때문에 코드가 수정되게 되면 테스트 코드 또한 수정을 해 줘야하는데요
때문에 저는 Fake 객체를 사용해 테스트 코드를 작성하는 편입니다.
Fake 객체로 테스트 코드를 작성해 보시면 좋을 것 같아요 😄

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/application/MenuGroupService.java
>      public List<MenuGroup> list() {
@Transactional(readOnly = true) 를 사용하면 어떠한 이점이 있을까요? 😄 
```suggestion
    @Transactional(readOnly = true)
    public List<MenuGroup> list() {
```

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/application/MenuService.java
> +        menuValidator.checkPrice(menu);
메뉴를 생성할때는 항상 Price 항상 검증해 줘야 하는데요,
해당 로직을 Menu에 위치하게 되면 menuValidator.checkPrice(menu); 를 호출할 필요 없이
Menu를 생성할때마다 검증할 수 있을 것 같아요 😄 
어떻게 생각하시나요?

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/application/TableGroupService.java
> +                .collect(toList());
orderTableIds 의 수 대로 매번 디비에서 조회를 하고 있는데요,
하나씩 조회하는 것 보다는 한번에 조회하는 것이 성능에 이점이 있을 것 같아요 😄

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +        menu.getMenuProducts().getMenuProducts().add(this);
```suggestion
        menu.addMenuProduct(this);
```
getter 를 사용하기 보다는 위와 같이 해보면 어떨까요? 😄

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/domain/Order.java
> +            throw new IllegalArgumentException();
에러 메세지를 정의해 줘도 좋을 것 같아요 😄

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/domain/OrderLineItem.java
> +            this.order.getOrderLineItems().getOrderLineItems().remove(this);
```suggestion
            this.order.removeOrderLineItem(this);
```
위와 같이 해보면 어떨까요? 😄

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/domain/OrderTable.java
> +        if (numberOfGuests < 0) {
매직넘버를 사용하기 보다는 상수화를 통해 값에 의미를 부여해 보면 어떨까요? 😄

2022-06-29 13:16 UTC, parkeeseul commented on src/main/java/kitchenpos/domain/Price.java
> +        return value < 0;
이 부분도 상수화를 해보면 좋을 것 같아요 😄

2022-06-29 13:16 UTC, parkeeseul commented on src/test/java/kitchenpos/application/MenuServiceTest.java
>  class MenuServiceTest {
Service 들에서 많은 테스트들을 제거해 주셨는데
제거해 주신 이유가 있으신가요? 🤔

2022-06-29 13:53 UTC, geunhwanlee commented on README.md
>  ## 요구 사항
좋은 의견 감사합니다
Fake 객체도 한번 사용해 봐야겠네요!

2022-06-29 13:56 UTC, geunhwanlee commented on src/main/java/kitchenpos/application/MenuGroupService.java
>      public List<MenuGroup> list() {
JPA에 readOnly hint를 전달하게 됩니다!

트랜잭션이 종료될 때 flush가 일어나지 않아서
의도치 않은 업데이트 쿼리가 나가지 않게 하고
변경감지 비용이 발생하지 않아 성능 상 이점이 있습니다😀

readOnly 힌트를 빠트렸네요! 감사합니다🙇🏻‍♂️

2022-06-29 14:10 UTC, geunhwanlee commented on src/main/java/kitchenpos/application/MenuService.java
> +        menuValidator.checkPrice(menu);
이 부분에 대해 고민을 많이 했었는데요😂
MenuProduct가 Product에 대한 의존성을 가지고 있지 않고 id만을 가지고있기 때문에
메뉴의 가격을 검증할 때 필요한 Product의 가격 정보를 얻기 위해선 ProductRepository의 의존성이 필요했습니다.🤔

Menu에서 검증하기 위해선 Menu 생성 시 Product 의존성을 주입시켜 주는 방법과
Menu - MenuProduct - Product 로의 연관관계 맵핑을 만들어 주는 방법이 있을 것 같습니다

이슬님이 생각하시는 좋은 방법이 있다면 알려주시면 감사하겠습니다🙇🏻‍♂️

2022-06-29 14:16 UTC, geunhwanlee commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +        menu.getMenuProducts().getMenuProducts().add(this);
양방향 연관관계를 맺기 위해 편의상 컬렉션에 직접 접근하여 add를 호출하게 작성하였습니다!

현재 addMenuProduct를 호출하게 되면 메서드끼리 서로 호출하여 무한루프에 빠질 것 같은데..

메서드 순환참조를 하고 조건식으로 무한루프에서 빠져나오는게 더 나을까요..?🤔

2022-06-29 14:24 UTC, geunhwanlee commented on src/main/java/kitchenpos/domain/OrderTable.java
> +        if (numberOfGuests < 0) {
넵!

2022-06-29 14:24 UTC, geunhwanlee commented on src/main/java/kitchenpos/domain/Price.java
> +        return value < 0;
👍🏻

2022-06-29 14:25 UTC, geunhwanlee commented on src/main/java/kitchenpos/domain/Order.java
> +            throw new IllegalArgumentException();
넵🫡

2022-06-29 14:25 UTC, geunhwanlee commented on src/main/java/kitchenpos/application/TableGroupService.java
> +                .collect(toList());
그렇네요! 감사합니다🙇🏻‍♂️

2022-06-29 14:43 UTC, geunhwanlee commented on src/test/java/kitchenpos/application/MenuServiceTest.java
>  class MenuServiceTest {
Service의 테스트는 Mock 객체를 통한 격리테스트로 작성 하였는데
Service의 역할이 다른 도메인 객체로 이동하면서 테스트 역시 다른 도메인 객체의 테스트에서 처리하도록 하였습니다.

그렇게 한 이유는 서비스레이어를 리팩터링하는 과정에서
1. 일부는 더 이상 Service에서 테스트할 수 없는 테스트코드가 있었고
2. 일부는 Service에서 테스트하기 위해 Domain의 구현을 고려한 복잡한 Stubbing을 해야 했기 때문입니다..😭
3. 그리고 Service가 가지고있는 많은 로직과 책임을 줄였기 때문에
더 이상 Service의 테스트 코드에 큰 비중을 둘 필요가 없다고 생각했기 때문입니다

이슬님은 어떻게 하는게 더 좋다고 생각하시는지 궁금합니다🙏

2022-06-29 18:02 UTC, geunhwanlee commented on src/main/java/kitchenpos/application/MenuService.java
> +        menuValidator.checkPrice(menu);
현재 Menu와 Product는 id로 느슨한 결합을 유지하고 있습니다..😭

Menu 가격을 검증하기 위해선 Product의 가격이 필요하기 때문에 도메인 서비스 영역으로 분리한 것인데..

혹시 좋은 방법이 있으면 알려주시면 감사하겠습니다!🙏

2022-06-30 10:49 UTC, parkeeseul commented on src/main/java/kitchenpos/application/MenuService.java
> +        menuValidator.checkPrice(menu);
아하 이부분은 제가 잘못 확인 했네요! 🙏 
혼선을 드려 죄송합니다

2022-06-30 11:29 UTC, parkeeseul commented on src/main/java/kitchenpos/domain/Price.java
> +    private static final long MINIMUM_PRICE = 0;
`Price.MINIMUM_PRICE` VS `Price.MIN`
어떻게 생각하시나요? 😄

2022-06-30 11:29 UTC, parkeeseul commented on src/test/java/kitchenpos/application/MenuServiceTest.java
>  class MenuServiceTest {
의견 공유해 주셔서 감사합니다 😄 
저는 service 대한 통합 테스트를 작성하는 편이라서 어떠한 의도로 service test 를 작성해 주셨는지 궁금해서 질문을 드렸습니다
슬라이드 테스트 목적으로 작성해 주셨다면 잘 작성해 주신 것이라 생각합니다 😄
이 부분은 정답이 있다기 보다는 의도나 중요하게 생각하는 부분이 다르다면 다를 수 있을 것 같아요!

2022-06-30 11:30 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨녜요! 👍 
추가 코멘트와 질문 주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드리고
추가적인 수정 사항은 다음 단계와 함께 반영해주시면 좋을 것 같아요!
다음 단계 진행해 주세요! 화이팅 입니다 🔥

2022-06-30 11:31 UTC, merged

2022-06-30 23:20 UTC, geunhwanlee commented on src/main/java/kitchenpos/domain/Price.java
> +    private static final long MINIMUM_PRICE = 0;
훨씬 명확하고 깔끔하네요!

꼼꼼하게 봐주셔서 감사합니다🙇🏻‍♂️