Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #527
Opened 2022-06-29 06:58 UTC by ssamzag

안녕하세요 김준홍 리뷰어님! 
2단계 서비스 리팩터링 리뷰 요청드립니다.

이번 미션을 진행하면서 dto 와 도메인이 많아지다 보니 정신이 나갈 것 같아서 패키지를 분리했습니다.  크게 menu/order/product/table 4가지로 나눠봤는데 맞게 분리한 건지 모르겠네요. 
그리고 일부 도메인은 연관관계로 지어지다보니 안 쓰이는 repository도 몇 개 삭제 했습니다.

인수 테스트는 작성 진행 중입니다. 완성하는 대로 푸쉬 할게요!

이번 리뷰도 잘 부탁드립니다! 😄

2022-06-30 16:21 UTC, Junhong-Kim requested changes
2단계 미션 잘 구현해주셨습니다 👍
리뷰 내용 확인하시고 다시 요청해주시면 감사드립니다. ☺️

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        Menu menu = request.toMenu();
`Request` 객체는 요청 값을 받아 유효성 검사만하면 좋을 것 같아요.
인스턴스를 생성하는 책임은 해당 클래스에게 위임하여 인스턴스 생성에 대한 일관성이 있으면 좋을 것 같아요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        menuRepository.flush();
`flush()`를 직접해주신 이유가 어떤걸까요?

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public List<MenuResponse> list() {
메서드 순서도 컨벤션 중의 하나입니다.
public 메서드는 private 메서드 위에 정의해주세요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        return productRepository.findByIdIn(menu.getProductIds());
In 절에 `productId`를 넘기고 있는데 존재하지 않는 `productId`가 있는지 검증이 필요합니다.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        menu.validate(findProductIds(menu));
인스턴스 생성시 검증할 수 있어보여요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +            sum = sum.plus(product.getPrice().multiply(menuProducts.getMenuProductQuantity(product.getId())));
`규칙 4: 한 줄에 점을 하나만 찍는다.` 규칙을 지키는 코드로 수정해보면 좋을 것 같아요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +                    this.addMenuProduct(menuProductRequest.toMenuProduct(this)));
앞서 코멘트 드린 것처럼 `Reuqest` 객체는 요청 값을 받아 검증만 하면 좋을 것 같아요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/domain/Name.java
> +    }
인스턴스는 되도록 생성과 동시에 초기화해서 완전한 상태로 만들면 좋을 것 같아요.
기본 값을 할당하는 기본 생성자가 불필요하지 않을지 고민해보면 좋을 것 같습니다.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        Order order = request.toOrder();
앞서 코멘트 드렸던 것처럼 유사한 형태의 코드들이 있는데 수정하면 좋을 것 같습니다.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +                .orElseThrow(IllegalArgumentException::new);
다른 도메인에서 중복되어 사용되네요.
Repository 대신 Service 클래스를 주입받아 사용하면 어떤 장점이 있을지 고민해보고 수정하면 좋을 것 같아요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +                .orElseThrow(IllegalArgumentException::new);
재사용 가능하도록 메서드를 추출하면 좋을 것 같아요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/order/dto/OrderRequest.java
> +    }
전체적으로 `Request` 객체에 비즈니스 로직이 포함되어있어요.
이 부분들을 도메인 클래스로 옮기면 좋을 것 같아요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/main/java/kitchenpos/table/application/TableService.java
> +                orderTableId, Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL))) {
`Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL)` 이 부분은 enum 클래스를 활용해볼 수 있을 것 같아요.

2022-06-30 16:21 UTC, Junhong-Kim commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
>  package kitchenpos.application;
Service 리팩터링을 통해서 비즈니스 로직이 Service에서 도메인 클래스로 옮겨졌습니다.
도메인 테스트 코드도 작성해주세요.

2022-07-01 02:51 UTC, ssamzag commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        Menu menu = request.toMenu();
Request 객체는 유효성 체크정도만 하는 게 좋다는 것이군요! 
알겠습니다 수정하도록 할게요

2022-07-01 02:54 UTC, ssamzag commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        menuRepository.flush();
아 삭제하도록 할게요!

2022-07-01 03:00 UTC, ssamzag commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public List<MenuResponse> list() {
메서드가 호출자 바로 아래에 위치하는 게 아니었나보군요.
그럼 모든 public 을 위로 올리고 호출되는 private 을 순서대로 놓으면 되는걸까요?

2022-07-01 03:01 UTC, ssamzag commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        return productRepository.findByIdIn(menu.getProductIds());
네 추가해 놓도록 할게요!

2022-07-01 03:02 UTC, ssamzag commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        menu.validate(findProductIds(menu));
인스턴스 생성자에서 체크하도록 바꿀게요!

2022-07-01 03:02 UTC, ssamzag commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +            sum = sum.plus(product.getPrice().multiply(menuProducts.getMenuProductQuantity(product.getId())));
수정하도록 하겠습니다!

2022-07-01 03:03 UTC, ssamzag commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +                    this.addMenuProduct(menuProductRequest.toMenuProduct(this)));
넵~

2022-07-01 03:05 UTC, ssamzag commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        Order order = request.toOrder();
지하철 미션의 Request 들이 toXX로 되어있어서 참고한 건데 잘못된 거였나보네요. 
깔끔하게 모든 걸 생성자에서 책임지도록 수정할게요~ 👍

2022-07-01 03:06 UTC, ssamzag commented on src/main/java/kitchenpos/order/application/OrderService.java
> +                .orElseThrow(IllegalArgumentException::new);
Service 에서 주입받아 사용하도록 수정할게요!

2022-07-01 03:07 UTC, ssamzag commented on src/main/java/kitchenpos/order/application/OrderService.java
> +                .orElseThrow(IllegalArgumentException::new);
추후 다른 서비스에서 재사용 가능하다는 큰 장점이 있겠네요! 
수정하도록 할게요

2022-07-01 03:08 UTC, ssamzag commented on src/main/java/kitchenpos/order/dto/OrderRequest.java
> +    }
도메인으로 옮기겠습니다! 😄

2022-07-01 03:21 UTC, ssamzag commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
>  package kitchenpos.application;
도메인 테스트도 작성하도록 할게요

2022-07-01 06:50 UTC, ssamzag commented on src/main/java/kitchenpos/menu/domain/Name.java
> +    }
네 고민해 보겠습니다

2022-07-01 07:29 UTC, ssamzag commented on src/main/java/kitchenpos/table/application/TableService.java
> +                orderTableId, Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL))) {
enum 클래스를 활용해 볼게요!

2022-07-02 07:07 UTC, Junhong-Kim requested changes
피드백 잘 반영해주셨는데 좀 더 수정해볼 만한 내용 코멘트 남겼습니다!
리뷰 내용 확인하시고 다시 요청해주시면 감사드립니다. ☺️

2022-07-02 07:07 UTC, Junhong-Kim commented on src/main/java/kitchenpos/embeddableEntity/Empty.java
> +package kitchenpos.embeddableEntity;
여러 엔티티에서 재사용될 수 있는 클래스로 보이는데 `common` 패키지 도메인으로 관리하면 어떨까요?

2022-07-02 07:07 UTC, Junhong-Kim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        if (products.size() != productIdHashSet.size()) {
`List<Product>`를 일급 컬렉션으로 만든 후 메시지를 보내어 의미를 표현하면 좋을 것 같아요.

2022-07-02 07:07 UTC, Junhong-Kim commented on src/test/java/kitchenpos/acceptance/application/AcceptanceTest.java
> +package kitchenpos.acceptance.application;
피드백을 반영하는 과정에서 다른 테스트들이 실패하게 된 것 같아요 🥲
테스트 코드 전체를 실행해보고 실패하고 있는 테스트들에 대해 수정해주세요.

2022-07-02 07:07 UTC, Junhong-Kim commented on src/test/java/kitchenpos/menu/domain/MenuProductsTest.java
> +    }
`@DisplayName`을 활용하면 좋을 것 같아요.

2022-07-02 07:07 UTC, Junhong-Kim commented on src/test/java/kitchenpos/menu/domain/MenuTest.java
> +import java.math.BigDecimal;
불필요한 import가 있진 않은지 확인하면 좋을 것 같아요.

2022-07-02 07:10 UTC, ssamzag commented on src/main/java/kitchenpos/embeddableEntity/Empty.java
> +package kitchenpos.embeddableEntity;
common 패키지 개념으로 embeddableEntity 패키지를 만들었는데 common 으로 바꾸겠습니다! 😄

2022-07-02 07:11 UTC, ssamzag commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        if (products.size() != productIdHashSet.size()) {
네 이것도 일급컬렉션으로 만들도록 할게요!

2022-07-02 07:12 UTC, ssamzag commented on src/test/java/kitchenpos/menu/domain/MenuProductsTest.java
> +    }
DisplayName을 빼먹었네요. 추가하도록 할게요.

2022-07-02 07:12 UTC, ssamzag commented on src/test/java/kitchenpos/menu/domain/MenuTest.java
> +import java.math.BigDecimal;
전체적으로 확인해 볼게요!

2022-07-02 07:53 UTC, Junhong-Kim approved these changes
피드백 잘 반영해주셨네요 👍
이번 단계는 이만 merge 하겠습니다.
다음 단계도 화이팅입니다! ☺️

2022-07-02 07:53 UTC, merged