Step3 - 의존성 리팩토링
next-step/jwp-refactoring pull request #528
Opened 2022-06-29 08:43 UTC by KangSeongHyo

안녕하세요~ 이번 미션도 쉽지 않네요..

3단계 의존성 리팩토링 리뷰 부탁드립니다.

감사합니다.

2022-06-30 03:24 UTC, seok-2-o requested changes
미션 잘진행해주셨네요.
몇가지 고민거리와 요구사항을 만족하지 못하는부분에 코멘트 남겨놓았으니
확인후 수정해주세요.

2022-06-30 03:24 UTC, seok-2-o commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
> +    private Long menuId;
메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.

메뉴의 이름이 바뀌는 경우 이미 발생한 주문에서 메뉴의 이름과 가격이 변경되는것이 바람직할까요?

2022-06-30 03:24 UTC, seok-2-o commented on src/main/java/kitchenpos/order/application/OrderService.java
>          }
OrderLineItems 내부로 캡슐화할 수 있찌 않을까요
```java
OrderLineItems.create(reqeust, menus)

2022-06-30 03:24 UTC, seok-2-o commented on src/main/java/kitchenpos/menu/domain/Menus.java
> +    public Menu getMenuBy(Long menuId) {
아이디로 찾는 기능만 제공한다면 Map<Long, Menu> 로 구성한다면 어떤 장점이 있을까요?

2022-06-30 03:24 UTC, seok-2-o commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        eventPublisher.publishEvent(new OrderCreateEvent(order.getOrderTableId()));
유효성 검증을 이벤트로 진행하면 어떤 장점이 있나요? 이벤트는 동기로 동작하나요 비동기로 동작하나요?

2022-06-30 08:52 UTC, KangSeongHyo commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
> +    private Long menuId;
앗.. 이부분 제가 잘못 이해했었군요.. 해당부분 주문 시점에 내역을 가지고 있을 수 있도록
수정해보았습니다.

2022-06-30 08:53 UTC, KangSeongHyo commented on src/main/java/kitchenpos/order/application/OrderService.java
>          }
아 아직 캡슐화가 익숙하지 않는 것 같네요 좀 더 연습을 해야겠네요 반영했습니다~!

2022-06-30 08:55 UTC, KangSeongHyo commented on src/main/java/kitchenpos/menu/domain/Menus.java
> +    public Menu getMenuBy(Long menuId) {
Map으로 하면 cache 처럼 사용할 수 있을것 같습니다. 이부분은 변경했는데 
혹시 return type을 Map<Long, Menu> 이렇게 변경하는 부분일까요?

2022-06-30 08:57 UTC, KangSeongHyo commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        eventPublisher.publishEvent(new OrderCreateEvent(order.getOrderTableId()));
이벤트의 경우 따로 설정하지 않는 경우 동기방식으로 처리되었습니다.
처음에는 OrderValidator로 생성하였는데 package간 cycle이 발생해서 
Handler로 분리를 했었는데 이렇게 의존을 제거 할 수 있는 부분이 장점이 아닌가 싶습니다.

2022-07-01 03:15 UTC, seok-2-o commented on src/main/java/kitchenpos/menu/domain/Menus.java
> +    public Menu getMenuBy(Long menuId) {
아니요 `List<Menu> -> Map<Long, Menu>` 로 변경하면 좋지 않을까 생각하여 제안드렸습니다.

2022-07-01 03:17 UTC, seok-2-o approved these changes
피드백 반영잘해주셨네요 👍 
이어서 다음 미션 진행해주세요.

2022-07-01 03:17 UTC, seok-2-o commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +        return new Price(productPrice.getPrice() * quantity.getQuantity());
getter를 최대한 사용하지 않고 값을 계산하는 방법은 없을까요?

2022-07-01 03:17 UTC, merged