Step1 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #532
Opened 2022-06-29 18:06 UTC by kmmin78

안녕하세요, 리뷰어님! 🙇‍♂️

7주차 - 레거시 코드 리팩토링 PR 드립니다.

현재 구현된 코드에 대해 인수테스트 코드를 작성하였습니다.

앞으로 잘 부탁드립니다! 😊

2022-06-30 14:00 UTC, Junhong-Kim requested changes
안녕하세요. 
레거시 코드 리팩터링 미션을 함께하게된 리뷰어 김준홍입니다! ☺️
리뷰 내용 확인하시고 다시 요청해주시면 감사드립니다.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 메뉴의 가격이 음수일 수 없다.
요구사항 작성시 처음보는 사람도 읽기 쉽게 `메뉴의 가격은 0원 이상이어야 한다.`로 작성하면 좀 더 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 정상 생성
정상 생성되는 것도 요구사항으로 볼 수 있을까요?
`메뉴 생성` 요구사항과 중복되는 것 같습니다.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +    - [x] 상품 생성
애플리케이션이 제공하는 기능을 `상품을 생성할 수 있다.`와 같이 문장으로 쓰면 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 메뉴의 가격이 상품의 총 합보다 클 수 없다.
`상품의 총 합` 보다는 `각 상품 가격의 합`과 같이 의미를 명확하게 하면 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 존재하지 않는 메뉴그룹으로 지정할 수 없다.
`메뉴는 메뉴 그룹에 포함되어야한다.`와 같이 쉽게 읽히는 문장이 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 주문 라인 아이템이 없으면 실패한다.
`주문 라인 아이템`은 `주문 항목`이라고 표현하면 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 주문 라인 아이템이 없으면 실패한다.
대부분 요구사항을 기술적 용어에 밀접하게 작성해주신 것 같아요.
`주문 항목은 1건 이상이어야 한다.` 와 같이 작성하도록 요구사항을 다시 한번 점검해보면 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +    - [x] 테이블 그룹 생성
`테이블 그룹`은 `단체 테이블`이라고 보면 좋을 것 같네요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 요청한 주문 테이블 중 저장되지 않은 것이 존재하면 실패한다.
`저장되지 않은 것`, `실패`라는 용어는 기술적인 용어에 가까워보여요.

2022-06-30 14:00 UTC, Junhong-Kim commented on README.md
> +        - [x] 요청한 주문 테이블이 비어있지 않거나 이미 그룹핑 되었으면 실패한다.
각각의 요구사항으로 분리하면 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on src/test/java/kitchenpos/acceptance/AcceptanceTest.java
> +package kitchenpos.acceptance;
인수 테스트 잘 작성해주셨네요 👍
다만, 다음 단계에서 Service 리팩터링이 진행될 예정인데요.
리팩터링을 안정적으로 할 수 있도록 Service 테스트 코드를 작성해서 보호하면 좋을 것 같아요.

2022-06-30 14:00 UTC, Junhong-Kim commented on src/test/java/kitchenpos/acceptance/MenuAcceptanceTest.java
> +                new MenuProduct(양념_아이디, 1)
엔티티 클래스를 통해 직접 인스턴스를 생성하는 것보다는 `Test Fixture`를 생성해서 사용하면 재사용성을 높일 수 있을 것 같아요.

2022-07-02 17:04 UTC, kmmin78 commented on README.md
> +        - [x] 주문 라인 아이템이 없으면 실패한다.
다듬어주셔서 감사합니다. 
누가 읽어도 이해하기 쉽도록 작성하는게 쉽지가 않군요 🥲

2022-07-02 17:30 UTC, kmmin78 commented on src/test/java/kitchenpos/acceptance/AcceptanceTest.java
> +package kitchenpos.acceptance;
좋은 의견 감사합니다. 🙂 
근데 궁금한 점이 생겼습니다.
인수테스트를 통해서 Service 코드의 동작도 보호하고 있다고 생각하는데요!
막상 단위테스트를 작성하려고 보니, 인수테스트에서 이미 커버하고 있는 내용을 동일하게 재작성하는 것 같습니다.
그럼에도 불구하고 Service의 단위 테스트가 필요한 걸까요?

2022-07-02 17:36 UTC, kmmin78 commented on src/test/java/kitchenpos/acceptance/AcceptanceTest.java
> +package kitchenpos.acceptance;
물론 서비스에 있는 비즈니스 로직을 도메인으로 옮기는 과정에서 도메인 단위테스트를 작성하는 것은 필요할 것 같지만, Service 테스트에서 Mocking을 하면서까지 중복되는 테스트를 작성하는 것이 필요한 작업인지 의문이 들었습니다!

2022-07-03 13:57 UTC, Junhong-Kim commented on README.md
>  ## 요구 사항
피드백 잘 반영해주셨네요 👍

2022-07-03 13:57 UTC, Junhong-Kim commented on src/test/java/kitchenpos/__fixture__/MenuProductTestFixture.java
> +public class MenuProductTestFixture {
피드백 반영 👍

2022-07-03 13:57 UTC, Junhong-Kim commented on src/test/java/kitchenpos/acceptance/AcceptanceTest.java
> +package kitchenpos.acceptance;
도메인은 Service 보다 작은 단위의 핵심 로직을 담당하기 때문에 테스트 코드가 필요하다고 생각합니다.
그리고 Service는 도메인 클래스를 사용해서 기능을 제공하기 때문에 이에대한 테스트도 존재하는게 좋을 것 같습니다.

리팩토링 과정에서 Service 테스트 코드가 실패하게 되면,
도메인 로직이 잘못되어 Service가 실패된 것인지 도메인 로직은 정상인데 Service가 잘못되어 실패하게된 것인지 파악할 수 있습니다.

말씀해주신 것처럼 일부 중복되는 내용의 테스트가 작성될 수 있지만,
현재는 테스트 코드로 보호 후 리팩터링을 연습하는 과정으로 도메인과 Service 테스트 코드 모두 작성하면 좋을 것 같아요 ☺️

2022-07-03 14:00 UTC, Junhong-Kim requested changes
피드백 잘 반영해주셨습니다 👍
PR로 질문 남겨주신 사항은 대댓글로 답변드렸습니다.
리뷰 내용 확인하시고 다시 요청해주시면 감사드립니다. ☺️

2022-07-03 18:00 UTC, kmmin78 commented
준홍님, 서비스 단위 테스트 작성해서 다시 요청드립니다! 🙂

2022-07-04 15:17 UTC, Junhong-Kim approved these changes
피드백 잘 반영해주셨네요 👍
소소한 코멘트 남겼는데 다음 단계 시작 전 반영해보면 좋을 것 같아요.

이번 단계는 이만 merge 하겠습니다.
다음 단계도 화이팅입니다! ☺️

2022-07-04 15:17 UTC, Junhong-Kim commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        final TableGroup 테이블_그룹 = 테이블_그룹_생성(1L, LocalDateTime.now(), 주문_테이블, 주문_테이블2);
가변인자 `...`을 사용하는 것보다 인자로 넘겨줄 객체 목록을 `List`로 변환하면 메서드 인자 개수를 늘리지 않아도 될 것 같아요.
```java
테이블_그룹_생성(1L, LocalDateTime.now(), Arrays.asList(주문_테이블, 주문_테이블2));
```

2022-07-04 15:18 UTC, merged