Step3 - 의존성 리팩터링
next-step/jwp-refactoring pull request #535
Opened 2022-06-30 04:37 UTC by toughchb

안녕하세요 리뷰어님 
3단계 미션 pr 드립니다.

정말 이번 리팩토링 미션은 매 미션마다 어렵네요
context마다 id를 이용 하여 끊어냈고 event를 이용 하여 협력이 필요한 객체에게 검증할 수 있게 하였습니다.

제가 event 기반으로 프로그래밍 하는것이 처음이라 방법을 못찾은것이 있는데
OrderTableGroupEventHandler, OrderTableUngroupEventHandler 에서 handling시에 transaction 동작들을 하게 되어 transaction에 대해 보장하기 위헤 @TransactionalEventListener를 사용하여 event를 처리 하려 했습니다.

그런데 event가 trancsaction에 의존적이다 보니 해당 listener로는 event를 이용한 검증중에 예외가 발생 할때 순차적으로 예외상황에 대해 catch가 되지 않아 구글링한 결과 아래와 같은 링크를 찾게 되었고 일반적인 @EventListener를 사용하여 처리 할 수 밖에 없었습니다.
혹시 다른 처리 방법이 있는지 궁금 합니다.

https://stackoverflow.com/questions/65700617/how-to-make-event-listener-synchronous-to-publish-of-application-event-in-spring

의존성에 대해서는 아래와 같이 사이클에 대해 처리를 하였습니다.
![image](https://user-images.githubusercontent.com/9781649/176592775-b6c1b529-554f-444a-9540-9627dd628618.png)

시간 나실때 리뷰 부탁 드립니다.
감사합니다.

2022-07-01 01:53 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨어요 👍 
코멘트 남겨두었으니 확인 부탁드릴게요~~

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/table/application/OrderTableGroupEventHandler.java
> +    public void handle(TableGroupEvent event) {
Q. 제가 event 기반으로 프로그래밍 하는것이 처음이라 방법을 못찾은것이 있는데
OrderTableGroupEventHandler, OrderTableUngroupEventHandler 에서 handling시에 transaction 동작들을 하게 되어 transaction에 대해 보장하기 위헤 @TransactionalEventListener를 사용하여 event를 처리 하려 했습니다.

그런데 event가 trancsaction에 의존적이다 보니 해당 listener로는 event를 이용한 검증중에 예외가 발생 할때 순차적으로 예외상황에 대해 catch가 되지 않아 구글링한 결과 아래와 같은 링크를 찾게 되었고 일반적인 @eventlistener를 사용하여 처리 할 수 밖에 없었습니다.
혹시 다른 처리 방법이 있는지 궁금 합니다.

A. 
`@TransactionalEventListener`의 이름으로 봤을 때 트랜잭션이 필요한 경우 사용할 것 같지만, 실제로는 phase를 나눠 처리할 때 사용합니다 ㅎㅎ 
그래서 지금처럼 `@EventListner`로 처리해주시면 됩니다!
만약 `@Async`로 처리할 경우 실행 시점을 명확하게 하기 위해 `@TransactionalEventListener` 옵션을 `BEFORE_COMMIT`으로 바꾸는 방법이 있지만, DB 커넥션을 계속 물고 있기 때문에 안티패턴에 해당합니다!

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/common/domain/Name.java
> +package kitchenpos.common.domain;
Name, NumberOfGuests, Price 등은 공통된 도메인 같지만, 특정 컨텍스트에 해당하는 도메인인데요.
위와 같은 관점으로 봤을 때 common에 위치하는 것이 어색하게 느껴지고, 공통으로 사용하는 것에 대한 장점보다 단점이 커보이는데 어떻게 생각하시나요?

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/menu/application/CreateOrderMenuValidationHandler.java
> +        if (!menuRepository.existsAllByIdIn(event.getMenuIds())){
```suggestion
        if (!menuRepository.existsAllByIdIn(event.getMenuIds())) {
```

매의 눈 @_@

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/menu/application/CreateOrderMenuValidationHandler.java
> +    public void validateOrderTable(CreateOrderEvent event) {
이벤트로 분리를 잘 해주셨습니다 👍 
이벤트로 분리할 경우 의존성을 끊어낼 수 있다는 장점이 존재하지만, 코드의 의도를 파악하기 힘들다는 단점이 있는데요.
특히 검증에 대한 부분만을 분리하는 경우 단점이 커지는 경우가 많으니 한번 더 고민해보시면 좋을 것 같아요 ㅎㅎ 
이벤트 기반으로 하는 것이 처음이라 하셔서 트레이드 오프에 대한 선택을 할 때 도움이 되시면 좋을 것 같습니다 :)

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/menu/application/MenuValidator.java
> +                .valueOf(request.getPrice()))
```suggestion
        if (new Price(request.getPrice())
```

Price를 생성할 수 있는 방법을 확장해보면 어떨까요?

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        eventPublisher.publishEvent(new CreateOrderEvent(request.getOrderTableId(), request.getMenuIds()));
```suggestion
        eventPublisher.publishEvent(new OrderCreatedEvent(request.getOrderTableId(), request.getMenuIds()));
```

주문이 생성되어 발생했다라는 사실을 네이밍을 통해 명확하게 남겨줄 수 있을 것 같습니다!

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        findOrder.changeOrderStatus(OrderStatus.valueOf(request.getOrderStatus()));
```suggestion
        findOrder.changeOrderStatus(request.getOrderStatus());
```

Request에서 값을 처리해주는 경우도 있고, Service에서 해주는 경우도 있는데 각 선택의 기준이 있을까요?

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/domain/OrderRepository.java
> +    boolean existsByOrderTableIdInAndOrderStatusIn(List<Long> orderTableIds, List<OrderStatus> order);
```suggestion
    boolean existsByOrderTableIdInAndOrderStatusIn(List<Long> orderTableIds, List<OrderStatus> orderStatuses);
```

변수명이 변경되지 않은 것 같네요~

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/event/TableGroupEvent.java
> +    List<Long> orderTableIds;
```suggestion
    private final Long tableGroupId;
    private final List<Long> orderTableIds;
```

접근제어자를 생략한 것은 의도된 내용일까요?

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/table/application/CreateOrderTableValidationHandler.java
> +    @EventListener(CreateOrderEvent.class)
```suggestion
    @EventListener
```

매개변수로 타입을 알 수 있기 때문에 매번 추가하지 않으셔도 됩니다 ㅎㅎ

2022-07-01 01:53 UTC, jaeyeonling commented on src/main/java/kitchenpos/table/application/OrderTableUngroupEventHandler.java
> +                Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL))){
```suggestion
                Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL))) {
```

컨벤션을 위반하셨습니다. IntelliJ Auto Formatting 기능을 사용하는 습관을 들여보아요.

The auto-formatting shortcut in IntelliJ

- For windows Ctrl + Alt + L.
- For ubuntu Ctrl + Alt + windows + L.
- For Mac Command + Option + L.

2022-07-01 01:53 UTC, jaeyeonling commented on docs/step3.md
> +- 메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.
해당 요구사항은 구현이 됐을지 고민해보아요 ㅎㅎ

2022-07-01 01:55 UTC, toughchb commented on src/main/java/kitchenpos/table/application/OrderTableUngroupEventHandler.java
> +                Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL))){
아이고 ㅠㅠ 좀더 습관적으로 코드 포매팅을 하겠습니다

2022-07-01 01:56 UTC, toughchb commented on src/main/java/kitchenpos/menu/application/CreateOrderMenuValidationHandler.java
> +        if (!menuRepository.existsAllByIdIn(event.getMenuIds())){
ㅠㅠ 포매팅을 좀더 신경 쓰겠습니다

2022-07-01 02:07 UTC, toughchb commented on src/main/java/kitchenpos/menu/application/MenuValidator.java
> +                .valueOf(request.getPrice()))
생성자 추가하겠습니다

2022-07-01 02:08 UTC, toughchb commented on src/main/java/kitchenpos/order/event/TableGroupEvent.java
> +    List<Long> orderTableIds;
실수가 많네요 좀더 신경 쓰겠습니다

2022-07-01 02:18 UTC, toughchb commented on src/main/java/kitchenpos/order/domain/OrderRepository.java
> +    boolean existsByOrderTableIdInAndOrderStatusIn(List<Long> orderTableIds, List<OrderStatus> order);
수정 하겠습니다!

2022-07-01 05:53 UTC, toughchb commented on src/main/java/kitchenpos/menu/application/CreateOrderMenuValidationHandler.java
> +    public void validateOrderTable(CreateOrderEvent event) {
좀더 학습해보겠습니다!

2022-07-01 05:53 UTC, toughchb commented on src/main/java/kitchenpos/table/application/CreateOrderTableValidationHandler.java
> +    @EventListener(CreateOrderEvent.class)
수정하겠습니다!

2022-07-01 05:53 UTC, toughchb commented on docs/step3.md
> +- 메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.
OrderLineItem에 컬럼을 추가하여 해결하였습니다

2022-07-01 16:04 UTC, toughchb commented on src/main/java/kitchenpos/table/application/OrderTableUngroupEventHandler.java
> +                Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL))){
아이고 ㅠㅠ 아까 다시 리뷰 요청 할때 고친줄 알았는데 아니었네요 다시 포매팅 하여 수정 하였습니다!

2022-07-01 16:06 UTC, toughchb commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        eventPublisher.publishEvent(new CreateOrderEvent(request.getOrderTableId(), request.getMenuIds()));
이 리뷰를 놓쳤네요 수정하겠습니다!

2022-07-01 16:28 UTC, toughchb commented
코드 컨벤션을 하도 위반해서 전체 코드 일일히 포매팅 진행 하였습니다.
다시 한번 보기 불편한 코드를 만들어드려 죄송 합니다 😢

2022-07-01 22:57 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨습니다 👍 
추가적인 코멘트 남겨두었으니 확인 부탁드릴게요~

2022-07-01 22:57 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/event/TableUngroupEvent.java
> +    Long tableGroupId;
https://github.com/next-step/jwp-refactoring/pull/535#discussion_r911530678 해당 코멘트를 확인해주세요~

2022-07-01 22:57 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/dto/OrderLineItemRequest.java
> +    private Long menuPrice;
`메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.` 라는 요구사항은 해당 서비스를 사용하는 클라이언트 입장에서 수정 없이 내부적으로 구현만 변경되면 좋을 것 같아요 :)
해당 요구사항의 특징은 컨텍스트 간 의존성을 완벽하게 분리하는 것에 있습니다!

2022-07-01 22:57 UTC, jaeyeonling commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +    private static final int MIN_ORDER_TABLE_COUNT = 2;
사용하지 않은 변수는 제거해도 괜찮겠네요!

2022-07-03 02:23 UTC, jaeyeonling approved these changes
다음 단계 진행하시면서 DM으로 나눴던 부분 반영 부탁드려요 😄

2022-07-03 02:23 UTC, jaeyeonling commented on src/main/java/kitchenpos/order/event/TableUngroupEvent.java
> +        private final Long tableGroupId;
```suggestion
    private final Long tableGroupId;
```

인덴트가 맞지 않네요 @_@

2022-07-03 02:23 UTC, merged