3단계 - 의존성 리팩터링
next-step/jwp-refactoring pull request #537
Opened 2022-06-30 12:16 UTC by iamjunsulee

안녕하세요. 리뷰어님

빈 테이블이면서 단체 지정된 테이블이 아닌 경우 단체 지정 가능
빈 테이블이면 주문 불가
즉, 단체 지정은 빈 테이블만 가능하나 주문의 경우 빈 테이블은 할 수 없다. 
따라서 단체 지정 해제를 위해서 주문 상태를 확인할 필요가 없다... 라고 생각해서 
TableGroupService 에서 OrderRepository 로의 의존성을 제거했는데.. 잘한건지 모르겠네요..😅😅

리뷰 부탁드려요 !

2022-06-30 14:05 UTC, shared-moon requested changes
준수님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요!
코멘트를 몇 개 남겨 두었는데, 확인 후 다시 리뷰 요청 부탁드려요!

2022-06-30 14:05 UTC, shared-moon commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public void validate(MenuValidator menuValidator) {
유효성 검사라는 책임을 MenuValidator가 가져갔는데 Menu에 validate가 있을 필요가 있을까요 ?

2022-06-30 14:05 UTC, shared-moon commented on src/main/java/kitchenpos/order/application/OrderValidator.java
> +    private Map<Long, Menu> toMap(List<Long> menuIds) {
메서드 이름이 너무 포괄적이네요. 겉에서 봤을 땐 이 메서드가 무슨 일을 하는지 직관적으로 알기 어려워 보여요. groupById 정도로 어떤 게 키가 되는지 정도는 명시가 되면 좋을 것 같아요!

2022-06-30 14:05 UTC, shared-moon commented on src/main/java/kitchenpos/order/application/OrderValidator.java
> +                .collect(Collectors.toMap(Menu::getId, menu -> menu, (a, b) -> b));
valueMapper로 자기자신을 넘겨줄때에는 `Function.identity()` 요런걸 사용하실 수 있어요!

2022-06-30 14:05 UTC, shared-moon commented on src/main/java/kitchenpos/order/domain/Order.java
> +        this.orderStatus = OrderStatus.COOKING;
validate에서 상태를 변경해주는 건 뭔가 어색하네요!

2022-06-30 14:05 UTC, shared-moon commented on src/main/java/kitchenpos/product/domain/Price.java
> +    public long mapToLongValue() {
다른데서 쓰이고 있는 map~~ 과 일관성이 좀 깨지는 느낌이네요, 헷갈릴 수 있어보여요

2022-06-30 14:05 UTC, shared-moon commented on src/main/java/kitchenpos/table/application/Validator.java
> +public interface Validator {
이 인터페이스 현재는 약간 의미가 없어보이네요 ?

2022-06-30 14:06 UTC, shared-moon commented
의존성 관리는 잘 해결 하신 것 같아요! 마지막 미션 전에 정리하자는 의미로 리뷰 재요청 드렸습니다 :)

2022-06-30 14:53 UTC, iamjunsulee commented on src/main/java/kitchenpos/table/application/Validator.java
> +public interface Validator {
OrderValidator --> OrderTableRepository
TableService --> OrderRepository
이렇게 패키지 간에 의존성이 있어서 의존성 역전을 위해서 인터페이스로 만든 부분인데  잘못됐을까요?😥

2022-06-30 14:54 UTC, iamjunsulee commented on src/main/java/kitchenpos/product/domain/Price.java
> +    public long mapToLongValue() {
Price 객체 내부에 더 잘어울리는 네이밍으로 변경하겠습니다.

2022-06-30 14:55 UTC, iamjunsulee commented on src/main/java/kitchenpos/order/domain/Order.java
> +        this.orderStatus = OrderStatus.COOKING;
validate 를 통과해야 진짜 주문이 완성된다고 생각해서 해당 시간과 상태를 변경했던 것 같아요..
부자연스럽네요. 수정하겠습니다.

2022-06-30 14:56 UTC, iamjunsulee commented on src/main/java/kitchenpos/order/application/OrderValidator.java
> +                .collect(Collectors.toMap(Menu::getId, menu -> menu, (a, b) -> b));
아 이런게 있었군요 ! 👍👍

2022-06-30 14:56 UTC, iamjunsulee commented on src/main/java/kitchenpos/order/application/OrderValidator.java
> +    private Map<Long, Menu> toMap(List<Long> menuIds) {
좀 더 직관적으로 이름 변경하겠습니다 !

2022-06-30 14:59 UTC, iamjunsulee commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public void validate(MenuValidator menuValidator) {
굳이 없어도 될 것 같네요 !

2022-07-01 15:32 UTC, shared-moon commented on src/main/java/kitchenpos/table/application/Validator.java
> +public interface Validator {
음 .. 지금 처리하신 건 약간 의존성 사이클을 끊었다기보다는 숨겨놓은 느낌이에요! 인터페이스가 오직 OrderValidator만을 위해 만들어져있는것도 조금 위험해 보이구요! (Validator를 상속받은 다른 녀석이 나타났는데 심지어 이름이 같으면 바로 문제가 생길테니까요! )

이왕에 validator라는 중간 레이어를 만드셨으니, 패키지를 조금 조정 해 보는 건 어떨까요 ?

현재는 도메인 별로 패키지를 분리 해 두셨는데, 기능 별로 분리를 해본다던지 하는 식으로 시도 해 보면 좋을 것 같습니다!

4단계 미션 진행하면서 같이 고민해보면 될 것 같아요 :)

2022-07-01 15:33 UTC, shared-moon approved these changes
준수님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
미션은 여기서 머지 하도록 하겠습니다!
고생 많으셨어요 :)

2022-07-01 15:33 UTC, merged

2022-07-02 01:26 UTC, iamjunsulee commented on src/main/java/kitchenpos/table/application/Validator.java
> +public interface Validator {
아 애그리거트로 분류를 하고 참조방식을 바꿨지만 패키지 구분은 그대로이긴하네요...😥😥
패키지도 관련 애그리거트끼리 묶어 보겠습니다. ! 감사합니다 !