Step1 1단계 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #546
Opened 2022-07-01 07:30 UTC by hyunhyun

1단계 - 테스트를 통한 코드 보호 pr 요청드립니다. 리뷰 요청드립니다.
현재 레거시 코드를 기준으로 테스트 코드를 작성했는데, 이후 리팩토링 과정에서 해당 테스트코드도 많이 수정이 될거 같더라구요.
mock 객체를 이용하다 보니 테스트가 덜 되는 부분도 있을것도 같아서 해당 테스트코드가 이후 리팩토링 할때 토대 역할을 제대로 할지 
조금 생각이 들었던거 같습니다. 현재 테스트코드 처럼 하면 될지 코멘트 요청드립니다~~!! 감사합니다~

2022-07-01 16:54 UTC, ohtaeg requested changes
안녕하세요 정현님!
이번 레거시 코드 리팩토링 미션을 같이 함께 할 리뷰어 오태경이라고 합니다 👋 
함께하게 되어 영광이며 잘 부탁드립니다 🙇 

1단계 미션을 잘해주셨어요 👍 👍 
테스트 코드를 잘 작성해주셨습니다 👍 
작성해주신 요구사항 위주로 코멘트를 드렸는데 확인해주시면 감사하겠습니다 😄

2022-07-01 16:54 UTC, ohtaeg commented on README.md
> +    * 메뉴에 속한 전체 상품들 조회
사소하지만 개인적으로 용어 사전에 단어를 나타내는 경우, 저는 아래와 같이 표기하곤 합니다 😄
단어에 하이라이트를 줌으로써 용어사전에 정의되지 않은 단어와 비교하기 쉬운 장점이 있더라구요 :)
(수정을 위한 리뷰가 아니오니 참고만 부탁드려요!)

```suggestion
### `메뉴`
* `메뉴` 등록
    * `메뉴` 가격은 0 이상이다.
    * 등록된 `메뉴 그룹`(분류)이 아닌 `메뉴`는 등록하지 못한다.
    * 등록된 `상품`으로만 `메뉴`을 구성해야한다
    * `메뉴`의 가격은 구성 상품들의 합보다 작거나 같아야 한다.
* `메뉴` 조회
    * `메뉴`에 속한 전체 `상품`들 조회
```

2022-07-01 16:54 UTC, ohtaeg commented on README.md
> +    * 주문은 0건은 주문 불가하다
소리내어서 읽어본다면 조금 어색한 문장인 것 같아요!
조금 더 문장을 다듬어보면 좋을 것 같아요 😄

2022-07-01 16:54 UTC, ohtaeg commented on README.md
> +    * 주문시 기본 처리 상태는 COOKING 이다.
용어사전 정의되지 않은 용어들인 것 같아요!
주문 상태에 대한 COMPLETION, COOKING 용어를 정의한다면 어떤 장점이 있을까요 :) ?

2022-07-01 16:54 UTC, ohtaeg commented on README.md
> +        * 같은 메뉴끼리 개수 관리
혹시 이건 어떤 뜻일까요? 😭 
OrderService에 어느 부분을 보고 해석해주신건지 알려주시면 감사하겠습니다..! 🙏 
이 부분도 한번 소리내어 읽어보시면 좋을 것 같아요 :)

2022-07-01 16:54 UTC, ohtaeg commented on README.md
> +* empty 상태 변경
empty 상태 변경이라는 요구사항은 어떤 상태를 empty로 변경하는지 쉽게 파악하기 힘든 것 같아요 :)

2022-07-01 16:54 UTC, ohtaeg commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +package kitchenpos.application;
전체적으로 테스트 케이스를 잘 작성해주셨네요 👍

2022-07-01 16:54 UTC, ohtaeg commented on src/main/java/kitchenpos/domain/Order.java
> +                 List<OrderLineItem> orderLineItems) {
테스트를 위한 생성자를 만들어주신 걸까요? 👍

2022-07-01 16:54 UTC, ohtaeg commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    @InjectMocks
> 현재 레거시 코드를 기준으로 테스트 코드를 작성했는데, 이후 리팩토링 과정에서 해당 테스트코드도 많이 수정이 될거 같더라구요.
mock 객체를 이용하다 보니 테스트가 덜 되는 부분도 있을것도 같아서 해당 테스트코드가 이후 리팩토링 할때 토대 역할을 제대로 할지
조금 생각이 들었던거 같습니다. 현재 테스트코드 처럼 하면 될지 코멘트 요청드립니다~~!! 감사합니다~

잘 작성해주셨어요 👍 다음 미션에서는 서비스에 있는 로직을 도메인 영역으로 옮기기 때문에
서비스에서 제공하는 메서드들의 행위는 변하지 않기 때문에 크게 변경될 것 같지 않다고 생각이 드네요 :)
mokito 활용도 잘해주셨습니다 👍

2022-07-01 17:01 UTC, ohtaeg commented
작성해주신 요구사항을 조금 더 자세하게 작성해주시면 좋을 것 같아요! :)

프로젝트를 진행하다보면  개발자, 기획자, 디자이너 등 구성원 간에 생각하고 있는 개념이나 목표가 서로 다른 경우가 있습니다. 
그로인해 커뮤니케이션 미스가 발생하는 경우가 종종 생기고 시스템을 만든 후에 각자가 생각한 것과 다른 결과물이 나오거나 
구현이 서로 기대했던 바와 달라서 문제가 발생하거나 많은 비용과 자원이 소요되는 경우가 있습니다..!

요구 사항을 좀 더 자세하게, 정확하게 작성한다면 위와 같은 문제를 어느정도 해결할 수 있다고 정현님은 어떻게 생각하시나요 :) ?

2022-07-02 01:27 UTC, hyunhyun commented on README.md
> +    * 메뉴에 속한 전체 상품들 조회
꿀팁이네요! 변경했더니 요구 사항 가독성이 더 좋아지네요!

2022-07-02 01:27 UTC, hyunhyun commented on README.md
> +    * 주문은 0건은 주문 불가하다
* `주문` 요청에는 `주문 항목`이 존재해야한다. 
위 내용으로 변경하였습니다.

2022-07-02 01:27 UTC, hyunhyun commented on README.md
> +    * 주문시 기본 처리 상태는 COOKING 이다.
COMPLETION, COOKING은 용어사전에 따로 저장하는거 보다 용어사전에서 주문 상태에 대한 설명에 조리-> 식사 -> 계산 
이렇게 되어있어서 이걸 활용하는게 오히려 효율적일거 같아서 해당 내용으로 바꾸었습니다.

2022-07-02 01:27 UTC, hyunhyun commented on README.md
> +        * 같은 메뉴끼리 개수 관리
if (orderLineItems.size() != menuDao.countByIdIn(menuIds)) {
            throw new IllegalArgumentException();
        }
이 부분이였는데 아래 내용으로 수정하였습니다!!
    * `주문 항목`은 `메뉴`별로 묶어서 주문된다.
      * `주문` 내역의 `주문 항목` 수와 `메뉴` 수가 동일하지 않으면 에러를 반환한다.

2022-07-02 01:27 UTC, hyunhyun commented on README.md
> +* empty 상태 변경
빈 테이블로 용어사전에 있는 단어로 변경하였습니다~

2022-07-02 01:27 UTC, hyunhyun commented on src/main/java/kitchenpos/domain/Order.java
> +                 List<OrderLineItem> orderLineItems) {
넵 테스트 코드 작성시 전부 setter로 생성하니 비효율적이라 생성자 추가하였습니다.

2022-07-02 13:18 UTC, ohtaeg approved these changes
리뷰가 늦어서 죄송합니다 🙇 
피드백 반영을 잘해주셨네요 👍 👍 
해당 요구사항 기반으로 도메인간 의존성을 고려하시면서 다음 미션을 진행해보아요 😄 
다음 미션도 화이팅입니다 🔥

2022-07-02 13:18 UTC, ohtaeg commented on README.md
> +    * `메뉴`에 속한 전체 `메뉴`들 조회
하이라이트 적용 👍

2022-07-02 13:18 UTC, ohtaeg commented on README.md
> +* `주문` 내역 조회
요구사항이 자세하게 작성되어졌어요 💯

2022-07-02 13:18 UTC, merged