Step1 코드 리뷰 요청 드립니다.
next-step/jwp-refactoring pull request #551
Opened 2022-07-01 16:16 UTC by lcjltj

해당.. 미션...을 보자 마자 당황을 많이 해서 .. 어디서 부터 손 대야 할지 막막 했습니다. 이번 단계에서는 리팩토링을 하기 전 현재 상태에 대한 
테스트 코드를 작성함으로써,  다음 단계(리팩토링)을 하여도 해당 테스트 케이스가 정상적으로 동작 하는 것을 통해, 정상적인 리팩토링이 됬다고 판단하기 위해 테스트 코드를 작성하는 단계라고 생각하여, 소스부분은 수정하지 않고 테스트 케이스를 만드는 것에 집중 하였습니다.
Controller 테스트 부분은 인수 테스트로 대체 하였으며, 서비스 테스트 부분도  mock을 통해 작성을 하긴 했는데... 해당 프로젝트 인 경우 단위테스트 하기 힘든 부분(DB 연동)에 대한 부분이 많아 작성하기 어려웠네요..

첫 미션 리뷰 요청 드립니다 .잘부탁 드립니다.!!

2022-07-02 04:50 UTC, wooobo requested changes
안녕하세요 찬준님!

이번미션 함께하게된 리뷰어 강태화입니다.
테스트 코드 꼼꼼하게 잘 작성해주셨네요 :+1: 

이번 단계는 요구사항을 면밀히 파악하고, 테스트 코드를 작성하는 부분이 중요하다고 생각하는데요!
누락된 요구사항이 없는지 좀 더 체크 해보시면 좋을것 같아요!

확인 후 재요청 부탁드려요 :pray:

2022-07-02 04:50 UTC, wooobo commented on README.md
> +    - [ ] 상품들 금액의 합이 메뉴 가격 보다 작거나 같아야 한다.
```
sum = sum.add(product.getPrice().multiply(BigDecimal.valueOf(menuProduct.getQuantity())));
```
코드를 보았을때, `상품가격 * 갯수` 의 개념이 들어가져야 할것 같아요! :thinking:

2022-07-02 04:50 UTC, wooobo commented on README.md
> +    - [ ] 손님 수는 0명 이상 이어야 한다.
`손님 수는 0명 이상 이어야 한다.` 의 조건은 
`방문한 손님 수`를 변경 할 때 적용되어야 하는것 같아요.


이렇게 해볼수도 있겠네요 :smile: 
```
* `주문 테이블`의 `방문한 손님 수`를 변경 할 수 있다.
    * `주문 테이블`의 `방문한 손님 수`는 0명 이상이어야 변경할 수 있다.
```

2022-07-02 04:50 UTC, wooobo commented on README.md
> +    - [ ] 주문 테이블 을 빈 테이블 로 변경 한다.
빈 테이블 유무를 변경 할 수 있는 요구사항 조건이 없는지 점검해보아요~!

2022-07-02 04:50 UTC, wooobo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    void changeOrderStatus() {
`@DisplayName` 을 활용해서 테스트의 설명을 잘 설명해놓으면 
어떠한 요구사항에 대한 테스트인지 빠르게 이해할수 있을것 같아요!

`주문 상태를 변경 한다.`

2022-07-02 08:27 UTC, lcjltj commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    void changeOrderStatus() {
displayname 추가 했습니다.

2022-07-02 08:32 UTC, lcjltj commented on README.md
> +    - [ ] 손님 수는 0명 이상 이어야 한다.
ㅠㅠ 가독성이 너무 떨어지게 작성해놨네여 ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ

2022-07-03 01:12 UTC, wooobo approved these changes
찬준님 잘 진행해주셨습니다!

1단계 `merge`진행하겠습니다~

다음단계도 잘 부탁드립니다! ^^

2022-07-03 01:12 UTC, wooobo commented on README.md
> 소스부분은 수정하지 않고 테스트 케이스를 만드는 것에 집중 하였습니다.

잘 진행해주셨습니다!
 
> 해당 프로젝트 인 경우 단위테스트 하기 힘든 부분(DB 연동)에 대한 부분이 많아 작성하기 어려웠네요..

맞아요, 지금은 서비스레이어에 많은 로직이 들어가져 있기 때문에 서비스레이어 중심으로 테스트를 진행해야 할꺼에요.
이부분은 깨지기 쉬운테스트가 될수도 있겠죠 DB연동 코드와 썩여져 있으니까요~
다음 단계 `서비스 리팩터링`를 진행하시면서 많은것을 느껴보셨으면 좋겠네요 ^^
그때에 요구사항 정리가 많은 도움 될꺼에요!

2022-07-03 01:12 UTC, merged