Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #552
Opened 2022-07-01 16:20 UTC by yangseungin

안녕하세요 태엽님

아직 2단계가 한참 남았지만 진행하다 몇가지 문의드릴내용이 있어서 우선 PR을 보냈습니다.

리팩토링하면서 api에서 직접 엔티티를 반환하지 않고 요청,응답(request, response)을 만들어서 반환하였는데요.

 이러다보니 상당히 많은 테스트들이 깨지게 되었는데 효율적이지 못한 것 같은데 어떻게생각하시나요?

아 그리고 지금 pr에서 현재까지 수정한 Product에서 Price를 원시값 포장을 하면서 일단은 `지코바치킨.getPrice().getPrice()`과 같은 코드들이 생기긴했는데 이부분도 추후에 수정할 예정입니다.

2022-07-06 11:46 UTC, yangseungin commented
https://github.com/next-step/jwp-refactoring/pull/552#issue-1291599342
해당부분은 DM으로 답변주셔서 확인하였습니다.

2022-07-06 12:07 UTC, yangseungin commented
리뷰요청드리고나서 보니 MenuProduct도 일급컬렉션으로 사용해도될 것 같습니다

2022-07-06 16:19 UTC, enemfk777 requested changes
안녕하세요 승인님 :)

코드량이 만만찮은 단계인데 미션 열심히 수행해주셨네요
몇가지 코멘트 드렸으니 확인 후 다시 한번 요청 부탁드립니다!

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        Menu menu = new Menu(menuRequest.getName(), menuRequest.getPrice(), menuGroup);
request에서 필요한 정보 대부분을 가지고 있는데, 서비스는 menugroup, menuproducts만 전달하고 request에게 menu 생성 책임을 부여해보시는건 어떨까요?

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        menu.addMenuProducts(menuProducts);
메뉴 객체 생성시 함께 전달해서 메뉴상품이 없는 객체가 발생하는걸 미연에 방지해보시는건 어떨까요?

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +                .orElseThrow(IllegalArgumentException::new);
메서드로 분리되면 좋을 것 같습니다 :)

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +        MenuGroup menuGroup = new MenuGroup(menuGroupRequest.getName());
이부분의 entity도 request에서 만들어 낼수 있을 것 같아요

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +                .orElse(BigDecimal.ZERO);
일급 컬렉션을 활용해서 계산 책임을 넘겨 보시는 건 어떨까요?

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    }
Price 객체를 활용해볼 수 있지 않을까요?

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/order/application/OrderService.java
> +                .orElseThrow(IllegalArgumentException::new);
이부분도 메서드로 분리될 수 있을 것 같아요 :)

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        if (CollectionUtils.isEmpty(orderLineItems.getOrderLineItems())) {
empty도 orderlineItems가 직접 반환할 수 있을 것 같아요

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/order/application/OrderService.java
> +                .orElseThrow(IllegalArgumentException::new);
전체적으로 이런 패턴이 많이 발견되네요 :)
메서드로 분리할 수 있는 곳 점검 부탁드려요!

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/product/domain/Price.java
> +public class Price {
의미있는 객체 분리 좋습니다 👍

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/product/application/ProductService.java
> +        Product save = repository.save(new Product(productRequest));
의존성의 방향은 presentation layer -> service layer -> domain layer로 흐르는 것이 좋습니다.
지금은 domain layer인  Product가 presentation layer인 request를 의존하게 되었네요
방향을 반대로 바꿔주시면 어떨까요?

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/table/application/TableService.java
> +        orderTable.ungroup();
생성에 필수적인 작업은 생성시 해주셔서 기본 validation이 통과되지 않는 객체가 생성되지 못하도록 하시는건 어떨까요?

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/table/application/TableService.java
> +                orderTableId, Arrays.asList(OrderStatus.COOKING, OrderStatus.MEAL))) {
조건절이 복잡하면 가독성이 떨어집니다. 
적절한 의미를 갖는 메서드로 분리해주시면 좋을 것 같아요

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/tablegroup/application/TableGroupService.java
> +        }
메서드로 분리되도 좋을 것 같아요 :)

2022-07-06 16:19 UTC, enemfk777 commented on src/main/java/kitchenpos/tablegroup/application/TableGroupService.java
> +        savedTableGroup.group(orderTables);
기본적인 관계 설정, 그룹핑은 객체 생성시 해보시면 좋을 것 같아요

2022-07-07 02:49 UTC, yangseungin commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        Menu menu = new Menu(menuRequest.getName(), menuRequest.getPrice(), menuGroup);
최근에 작업한 것들은 말씀하신것처럼 진행하였는데 저번주에 진행한 것들의 경우 안되어있네요 👍

2022-07-07 04:41 UTC, yangseungin commented on src/main/java/kitchenpos/tablegroup/application/TableGroupService.java
> +        }
이부분은 심지어 같은값을 비교하고있었군요 :(

2022-07-07 05:14 UTC, yangseungin commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        if (CollectionUtils.isEmpty(orderLineItems.getOrderLineItems())) {
이 부분도 더 나아가서 Order가 생성될때 확인해도 될것같네요

2022-07-07 06:19 UTC, yangseungin commented
전반적으로 비슷한 형태의 내용이 많았던 것 같아서 전체 프로젝트를 확인하고 수정해봤습니다 😁

2022-07-07 15:48 UTC, enemfk777 approved these changes
안녕하세요 승인님 :)

피드백 잘 반영해주셨네요 👍
이번 단계는 바로 머지하겠습니다.
고지가 얼마 남지 않았는데 화이팅입니다!

2022-07-07 15:48 UTC, merged