Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #559
Opened 2022-07-02 09:42 UTC by yong2ss

안녕하세요 리뷰어님 :)

미션하면서 계속 익히고는 있지만, 아직 JPA가 익숙하지 않아 2단계가 조금 오래걸렸네요ㅠ

리뷰 부탁드립니다!

2022-07-03 13:56 UTC, oper912 requested changes
2단계 구현 잘해주셨네요 🙂
다만 몇가지 아쉬운 부분들이 있어서 코멘트 남겼는데 확인후에 리뷰 재요청 부탁드립니다.
마지막까지 화이팅입니다 💪

2022-07-03 13:56 UTC, oper912 commented on src/main/java/kitchenpos/application/MenuService.java
> +@Ignore
여기서 @Ignore 애노테이션을 사용하신 이유가 무엇일까요?? 🤔

2022-07-03 13:56 UTC, oper912 commented on src/main/java/kitchenpos/application/MenuService.java
> +    public List<MenuResponse> list() {
@Transactional(readOnly = true) 

또한 트랜잭션을 읽기전용으로 했을 경우에 JPA 내부적으로 다르게 동작하는 부분도 있으니 찾아보시면 도움이 될 것 같습니다

2022-07-03 13:56 UTC, oper912 commented on src/main/java/kitchenpos/domain/Menu.java
> +        if(price.getPrice().compareTo(menuProducts.getTotalPrice()) > 0) {
```suggestion
        if (price.getPrice().compareTo(menuProducts.getTotalPrice()) > 0) {
```

2022-07-03 13:56 UTC, oper912 commented on src/main/java/kitchenpos/domain/Menu.java
> +    @ManyToOne(fetch = FetchType.LAZY)
필수값이라면 optional = false 옵션을 명시해주면 좋을 것 같습니다

2022-07-03 13:56 UTC, oper912 commented on src/main/java/kitchenpos/domain/Menu.java
> +        this.price = new Price(price);
> * 메뉴
    - 메뉴를 생성한다
        - 가격 = 상품별 가격 * 상품별 갯수이며, 합이 0원 이상이어야한다.
        - `유효한 메뉴 그룹이 있어야한다.`
        
Menu에 MenuGroup은 필수인 것 같은데요 현재는 Entity에서 엄격하게 강제하고 있지 않아서 연관관계에 대해서 파악하기가 쉽지 않은 것 같아요 

도메인 지식이 없는 사람이 투입되더라도 Entity들만 보고도 빠르게 전체적인 구조 파악이 가능하도록 구현을 하는게 좋을 것 같은데요 불필요한 생성자들은 정리하는게 좋을 것 같아요

추가로 메인 생성자 하나를 두고 서브 생성자들이 메인 생성자를 호출하는 방식으로 수정하면 좋을 것 같습니다 
```
public menu(~) { // sub
    this(~);
}

public menu(~) { // main
    this.~ = ~;
    this.~ = ~;
}
```

2022-07-03 13:56 UTC, oper912 commented on src/main/java/kitchenpos/domain/Menu.java
> +    @ManyToOne(fetch = FetchType.LAZY)
디폴트 생성자의 접근제한자를 protected로 최소화해볼 수 있겠네요
https://kjw1313.tistory.com/25

2022-07-03 13:56 UTC, oper912 commented on src/main/java/kitchenpos/domain/Menu.java
> +    @ManyToOne(fetch = FetchType.LAZY)
entity의 [equals, hashcode도 식별자로 재정의](https://jwkim96.tistory.com/256)해주면 어떨까요??

2022-07-03 17:06 UTC, yong2ss commented on src/main/java/kitchenpos/application/MenuService.java
> +@Ignore
잘못들어가서 수정했습니다!

2022-07-03 17:06 UTC, yong2ss commented on src/main/java/kitchenpos/application/MenuService.java
> +    public List<MenuResponse> list() {
추가했습니다 :)

2022-07-03 17:07 UTC, yong2ss commented on src/main/java/kitchenpos/domain/Menu.java
> +        if(price.getPrice().compareTo(menuProducts.getTotalPrice()) > 0) {
관련한 컨벤션 모두 찾아서 수정했습니다!

2022-07-03 17:07 UTC, yong2ss commented on src/main/java/kitchenpos/domain/Menu.java
> +    @ManyToOne(fetch = FetchType.LAZY)
수정했습니다!

2022-07-03 17:08 UTC, yong2ss commented on src/main/java/kitchenpos/domain/Menu.java
> +        this.price = new Price(price);
테스트를 위해 생성자를 너무 무분별하게 추가한게 문제였던 것 같네요...!
알려주신 서브 생성자를 통해, 조금 가독성있게 줄일 수 있었습니다.

2022-07-03 17:09 UTC, yong2ss commented
리뷰해주신 내용 기반으로 수정했습니다...!

2022-07-04 01:30 UTC, oper912 approved these changes
피드백 반영 잘해주셨네요 👍👍
바로 머지하도록 하겠습니다
다음 단계 진행해주세요~ 💪

2022-07-04 01:30 UTC, oper912 commented on src/main/java/kitchenpos/application/MenuService.java
> +    public List<MenuResponse> list() {
👍 피드백 반영 잘해주셨네요

2022-07-04 01:30 UTC, merged