Step2 - 서비스 리팩터링
next-step/jwp-refactoring pull request #584
Opened 2022-07-05 08:20 UTC by jaesungahn91

이번 단계도 잘부탁드립니다!

테스트 Fixture 피드백 반영을 하려했는데 하면 할 수록 뭔가 잘못되고있는거 같아 다시 삭제를 했습니다..

혹시 관련해서 볼만한 링크나 키워드가 있을까요?

2022-07-06 11:28 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨습니다~ 
코멘트 남겨었으니 확인 부탁드릴게요!

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/MenuService.java
> +            Product product = findProductById(menuProductRequest);
DB에 데이터를 조회하는 것은 비싼 비용인데요.
DB 접근을 O(n) -> O(1)으로 만들어보면 좋겠어요~

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/MenuService.java
>              throw new IllegalArgumentException();
리팩토링 진행하며 상황에 맞는 예외처리 메시지를 추가해보면 어떨까요?

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/OrderService.java
> +        validate(request);
order 생성 전 검증을 하지 않고 후에 하는 이유가 있을까요?

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/OrderService.java
> +        order.addOrderLineItems(request.toOrderLineItems());
order 생성과 orderLineItems 추가를 나눠서 처리하신 이유가 있을까요?

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/OrderService.java
> +    public List<OrderResponse> list() {
```suggestion
    @Transactional(readOnly = true)
    public List<OrderResponse> list() {
```

readOnly 옵션을 사용해 볼 수 있겠네요!

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/OrderService.java
> +        return OrderResponse.of(orderRepository.save(order));
`@Transactional`을 사용한다면 save를 따로 하지 않아도 되는데, save를 해준 것은 의도된 내용일까요?

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    public TableGroupService(final OrderRepository orderRepository, final OrderTableRepository orderTableRepository, final TableGroupRepository tableGroupRepository) {
120자가 넘는다면 줄바꿈을 통해 가독성을 높여보면 좋겠어요!

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/TableService.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(
쿼리로 검증하는 것과 도메인에서 검증하는 것은 어떠한 차이가 있을지 고민해보아요.

2022-07-06 11:28 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        validateUngroup(tableGroupId);
대부분의 검증은 도메인에서 할 수 있도록 해보면 어떨까요?

2022-07-06 11:28 UTC, jaeyeonling commented on src/test/java/kitchenpos/application/OrderServiceTest.java
>      private Order 주문;
픽스처에 대한 개념은 검색해보면 많이 나올 것 같아서 실제 사용하는 코드를 전달 드리도록 할게요!
코틀린 코드긴 하지만 어떤 식으로 작성하는지 참고만 하시면 될 것 같아서 https://github.com/woowacourse/service-apply/tree/master/src/test/kotlin/apply 를 확인해보시면 좋을 것 같습니다~

2022-07-06 12:07 UTC, jaesungahn91 commented on src/main/java/kitchenpos/application/TableService.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(
쿼리로 검증하면 로직이 서비스에 있고 도메인에서 검증하면 엔티티안에 있습니다! 이미 사용하고있던 쿼리라 사용을 했는데 변경하는게 더 좋을까요?!

2022-07-06 12:08 UTC, jaesungahn91 commented on src/main/java/kitchenpos/application/TableService.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(
아래 피드백이랑 동일하여 변경했습니다!

2022-07-06 12:26 UTC, jaesungahn91 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        validateUngroup(tableGroupId);
이부분에서 order를 조회해서 사용하는 일이없는데도 조회해서 도메인에서 검증하는게 좋을까요!?

2022-07-06 13:04 UTC, jaesungahn91 commented on src/main/java/kitchenpos/application/OrderService.java
> +        order.addOrderLineItems(request.toOrderLineItems());
추가된다는 느낌이있어서 구분지었던거같은데, 생성자를통해서 한번에 만들어지는게 좋을까요!?

2022-07-07 00:36 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
질문의 답변 남겨두었으니 확인 부탁드리고, 빠른 진행을 위해 머지하도록 하겠습니다~
다음 단계에서 반영해주세요 😄

2022-07-07 00:36 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/OrderService.java
> +        order.addOrderLineItems(request.toOrderLineItems());
두 가지 모두 장단점이 있겠지만, 주문 생성 시 무조건 주문에 대한 주문 항목이 있어야 한다는 의미를 전달하기 위해선 생성자에서 같이 받는 것도 좋을 것 같습니다 😄 
주문내역에 대한 검증도 도메인으로 옮길 수 있을 것 같고요~

2022-07-07 00:36 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/TableService.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(
비즈니스 로직의 경우 도메인에서 담당하는 것이 좋을 것 같습니다~

2022-07-07 00:36 UTC, jaeyeonling commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        validateUngroup(tableGroupId);
https://github.com/next-step/jwp-refactoring/pull/584#discussion_r913992547 해당 코멘트와 연관이 있는 것 같아요!
TableGroup을 조회해서 메시지를 던져 처리해보면 좋겠어요 :)

2022-07-07 00:36 UTC, merged