Step3 리뷰 요청 드립니다.
next-step/jwp-refactoring pull request #599
Opened 2022-07-06 13:39 UTC by jiyeonghwang

안녕하세요.
Step3 리뷰 요청 드립니다!

초반에 어떻게 분리해야 하는지 헤메느라 시간이 좀 지체되었네요..
이번 리뷰도 잘 부탁드리겠습니다 !

2022-07-07 10:08 UTC, seokhongkim requested changes
지영님, 3단계 미션 잘 진행해주셨습니다. 👍 
패키지별 분리는 잘 진행해주셨습니다.

코멘트 남긴 내용 확인 부탁드립니다! 🙏

2022-07-07 10:08 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public void validateMenuGroupId(Long menuGroupId) {
`public` 접근 제어자를 사용하신 이유가 있을까요?

2022-07-07 10:08 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    private void validPrice(BigDecimal price) {
`Price` 를 관리하는 클래스를 만들면 아래 밸리데이션을 `Price` 객체의 생성 제한 조건으로 관리할 수 있겠네요!

2022-07-07 10:08 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        validPrice(request.getPrice());
`Menu` 클래스에서 객체 생성 시 제한 조건으로 관리했다가 서비스로 옮기신 이유가 있을까요?

2022-07-07 10:08 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/TableService.java
> +import kitchenpos.order.repository.OrderRepository;
`order` -> `table` 방향의 의존관계가 있는데, `table` -> `order` 방향의 의존관계도 발생했네요.
순환 의존관계를 제거하려면 어떻게 해야할까요?

2022-07-07 10:08 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    @Column(name = "menu_group_id")
불필요한 연관관계 제거 좋습니다. 👍

2022-07-07 10:08 UTC, seokhongkim commented on src/main/java/kitchenpos/order/domain/Order.java
>  package kitchenpos.order.domain;
이번 요구사항 중 아래 내용이 구현되지 않은 것 같습니다.
> 메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.

현재 `OrderLineItem` 에 menuId 를 가지고 있는데, 메뉴 정보가 변경되더라도 주문 시점의 메뉴 정보를 저장하려면 어떻게 해야할까요?

2022-07-07 12:26 UTC, yeongever0 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public void validateMenuGroupId(Long menuGroupId) {
private 로 변환하였습니다..!

2022-07-07 12:35 UTC, jiyeonghwang commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    private void validPrice(BigDecimal price) {
validPrice를 제거하고 `Price`객체를 만들도록 개선하였습니다!

2022-07-07 12:44 UTC, seokhongkim requested changes
지영님, 피드백 드린 내용 잘 수정해주셨습니다. 👍 
미션 마무리를 위해 조금 더 필요한 부분이 있어 코멘트 남겨 놓았습니다.
코멘트 확인 부탁드립니다. 🙏

2022-07-07 12:44 UTC, seokhongkim commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
> +    @Column(name = "menu_name", nullable = false)
필드를 추가하셨으니, 테이블 스키마도 수정해야겠네요!
flyway 규칙에 맞춰서 DDL 을 추가 부탁드립니다.

참고로, flyway 를 사용하실 때는 이미 만들어져 있는 DDL 파일은 수정하시면 안됩니다.
[블로그](https://blog.gangnamunni.com/post/introducing-flyway/) 또는 [공식 사이트](https://flywaydb.org/documentation/getstarted/how) 내용을 참고하시어 작성 부탁드립니다!

2022-07-07 12:44 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
>                  .map(menuProduct -> productService.findById(menuProduct.getProductId()).getPrice().longValue()
`MenuProduct` 도 `Price` 를 가지고 있도록 변경한다면, `longValue()` 를 꺼낼 필요 없이 `Price` 간의 비교가 가능할 것 같습니다.

2022-07-07 12:50 UTC, jiyeonghwang commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        validPrice(request.getPrice());
상품이 있는지 검증하기 위해 DB 조회를 거치므로, 해당 과정에서 가격도 검증할 수 있도록 옮겼습니다..!

2022-07-07 12:59 UTC, yeongever0 commented on src/main/java/kitchenpos/table/application/TableService.java
> +import kitchenpos.order.repository.OrderRepository;
`OrderTableService`를 생성하여 순환 의존 관계를 제거하였습니다! 
해당 방법이 잘못된 방법이라면.. 피드백 부탁 드리겠습니다..

2022-07-07 13:00 UTC, jiyeonghwang commented on src/main/java/kitchenpos/order/domain/Order.java
>  package kitchenpos.order.domain;
앗.. 제가 요구 사항을 놓친 것 같습니다.. 
메뉴의 이름과 가격을 `OrderLineItem`에 추가하여 주문 시점의 정보를 저장하도록 개선하였습니다.. !

2022-07-07 19:06 UTC, jiyeonghwang commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
> +    @Column(name = "menu_name", nullable = false)
flyway 적용하여 DDL 추가하였습니다!

2022-07-07 19:19 UTC, yeongever0 commented on src/main/java/kitchenpos/menu/application/MenuService.java
>                  .map(menuProduct -> productService.findById(menuProduct.getProductId()).getPrice().longValue()
`longValue()`를 사용하지 않고 Price간 비교가 가능하도록 개선하였습니다!

2022-07-08 12:23 UTC, seokhongkim approved these changes
지영님, 3단계 미션 피드백 잘 반영해주셨습니다. 👍 
flyway 스크립트 작성까지 잘 마무리 해주셔서, PR 머지하도록 하겠습니다.
4단계 미션에서 뵙겠습니다. 😀

2022-07-08 12:23 UTC, merged