Step4 멀티 모듈 적용
next-step/jwp-refactoring pull request #607
Opened 2022-07-06 21:03 UTC by mmtos

4단계 PR 리뷰 요청 드립니다 ㅎㅎ 

table 테스트 빌드를 위해 order모듈의 TableOrderStatusChecker 구현체가 필요했었던 부분을 제거했습니다. 
그외에  소스내용 변경은 없고, 각 모듈로 위치만 변경되었고, build 스크립트를 작성했습니다.

2022-07-07 12:34 UTC, ohtaeg requested changes
4단계도 구현을 잘해주셨어요 👍 👍 
이전 단계들에서 잘해주셔서 크게 드릴 피드백이 없네요 💯 
마지막으로 고민해보시면 좋을 포인트 하나가 있어서 Request changes 하였습니다.
마지막 피드백이 될 것 같아요 :) 한번 고민해보신 후 재요청 주시면 감사하겠습니다 😄

2022-07-07 12:34 UTC, ohtaeg commented on build.gradle
> +subprojects {
공통된 의존성을 한번에 관리 👍

2022-07-07 12:34 UTC, ohtaeg commented on build.gradle
> +        implementation project(':module-table')
이 부분은 한번 고민해보시면 좋을 것 같아요. 
order <-> 테이블간 양방향 의존성을 가지고 있는 것 같아요..! 
마지막 미션에서의 핵심은 이 두 도메인간의 의존성을 어떻게 단방향으로 관리하는지가 포인트입니다.

이전 단계까지 잘해주셔서 코드 변경보다는 어떻게하면 의존성을 단방향으로 변경할 수 있을지 고민해보시면 좋을 것 같아요!
정답이 없는 부분이기에 고민해보신 후 승훈님이라면 현재 상황에 맞게 어떻게 해결할 수 있을지 해결 방법에 대해 코멘트 주시면 감사하겠습니다!

2022-07-07 12:34 UTC, ohtaeg commented on build.gradle
> +project(':module-core') {
테스트 픽스쳐를 별도 모듈로 빼주셨네요 👍

2022-07-07 13:22 UTC, mmtos commented on build.gradle
> +        implementation project(':module-table')
마지막까지 고민하다가 결국 테스트에서만 의존성을 제거했었던 부분이네요 
모듈로 변경하면서 발생한 재미있는 현상이라고 생각했던 부분이기도 합니다 ㅎㅎ
질문에 대한 답변부터 적자면 ```OrderStateCheck```라는 모듈을 새로 만들어서 ```module-order```, ```module-table```에서 사용하는 식으로 하면 양방향 의존성을 없앨 수 있지 않을까 생각해 봤습니다!

고민 과정은 아래에 정리해두었습니다.

--- 

모듈 구현 전의 상태는 다음과 같았습니다.
아래와 같이 의존성을 역전해서 제 의도대로 패키지 사이의 의존성을 만들어 낼 수 있었습니다. 

```
(table에서 order로 흐르던 의존성을 역전하기 위함)
Table Package (TableOrderStatusChecker.java) <- Order Package(TableOrderStatusCheckerImpl.java)
```
하지만 모듈로 분리하면서 실제로 Table 모듈을 독립적으로 실행하기위해서 아이러니하게도 구현부가 꼭 필요했었기에 런타임 의존성을 추가했었습니다.

이 런타임 의존성을 어떻게 이해하고 해석해야할까 고민을 많이 했습니다. 

당시에는 다음과 같이 생각했습니다 ㅎㅎ 

> 모듈로 분리하기전에, 즉 패키지 레벨일때도 런타임시에 실제로 사용되는 건 Order 패키지에 있던 TableOrderStatusCheckerImpl 였다.
> DI의 도움으로 이러한 런타임 의존성은 컴파일 타임에서는 숨길 수 있었다. 
> 하지만 모듈로 분리하면서 런타임 의존성을 명시할 필요성이 생겼다.   
> 어떻게 보면 앱이 가진 고유의 의존성이기도 하니까 자연스러운 상황일 수도 있다.
>
> 그래도 최소한 테스트는 분리해서 해보자. 

```패키지 레벨의 의존성 역전이 모듈에서의 런타임 의존성으로 돌아왔다는 점```이 재미있었습니다. 

하지만 지금 생각해보니, ```소프트웨어 유지보수를 위해서 필요한 의존성의 구성```은 ```앱 고유의 의존성```을 그대로 따르는 것과는 다른 것 같습니다. 
```패키지 레벨```에서 인터페이스를 통해 의존성을 역전했듯이 ```모듈 레벨에서의 의존성 역전``` 방법에 무엇이 있을지 고민해봤습니다. 
유지보수를 용이하기 위한 ```새로운 모듈```을 만들어내서 모듈간의 의존성을 역전시킬 수 있겠다는 결론에 도달했습니다 ㅎㅎ

2022-07-08 07:38 UTC, ohtaeg approved these changes
마지막까지 의견 공유를 잘해주셨습니다 👍 
마지막으로 제 의견을 드렸는데 확인해주시면 감사하겠습니다 :)

이로써 리팩토링 미션까지 완주를 하셨네요 🎉 
확인해보니 모든 미션을 클리어해주셨군요 👍 
9주동안 고생 많으셨으며, 꿀보다 달콤한 열매를 수확하셨길 바랍니다 🍒 
고생 많으셨습니다 🙇

2022-07-08 07:38 UTC, ohtaeg commented on build.gradle
> +        implementation project(':module-table')
의견 공유해주셔서 감사합니다 :)
테스트에서 분리하려는 부분이 인상적이네요 👍 
게다가 컴파일 의존성에서 런타임 의존성으로도 잘해주셨구요!
패키지 레벨에서 인터페이스를 통해 의존성을 역전했듯이 새로운 모듈로 의존성을 역전하는 방향이 좋네요 👍 👍 
의도하신 부분일지는 모르겠으나 이런 모듈(레이어)를 [손상 방지 계층](https://docs.microsoft.com/ko-KR/azure/architecture/patterns/anti-corruption-layer)이라고도 합니다!

<img width="856" alt="image" src="https://user-images.githubusercontent.com/20432323/177940729-59327f51-9dda-4646-8ee8-846cb8800bb1.png">


어댑터로써 모듈 간의 상호 작용을 중재하는 데 도움이 되며 서비스에 필요한 데이터만 전달되도록 합니다.
이런 레이어를 중간에 둠으로써 중요한 도메인들을 오염되지 않도록 하는 장점이 있습니다.
그만큼 단점도 있는데요! 위 링크를 참고하시어 해당 레이어의 장/단점을 알고가시면 좋을 것 같네요 :)

현재 구조에서 쉬운 방법으로 더 생각해보면
Order 컨텍스트 밑에 하위 컨텍스트로 Table 컨텍스트를 두어 하나의 모듈로 관리하는 방법이 최선일 것 같으며,
좀 더 나아가 이벤트 소싱하는 방법이 있을 것 같네요 :)

이벤트는 도메인 상태가 변경되는 경우 발생하고 기록하기에 이벤트 소싱이 완벽하게 동작하려면
모든 이벤트는 기록되어야하고 재전송 할 수 있도록 만들어져야 하기에 중간에 이벤트 스토어라는 레이어도 필요하게 되겠네요..!

정답이 없는 부분이기에 서로의 의견을 주고받고 구현을 해보면 베스트지만,
시간이 얼마 남지 않았고, 의존성에 대해 고민해보셨으며, 서로가 생각하는 방향이 공유된 상태라면 구현하지 않고 미션을 마무리하는 것도 좋다고 생각하여 코멘트를 드리게 되었습니다 🙏

2022-07-08 07:56 UTC, merged

2022-07-08 08:43 UTC, mmtos commented on build.gradle
> +        implementation project(':module-table')
아하 손상 방지 계층이라는 개념이 있군요 ㅎㅎ
미션 진행하면서 컨텍스트들을 동등한 레벨로만 두고 구현해나갔었는데  컨텍스트간의 depth도 있다는걸 알게되네요.
이벤트 소싱과 이벤트 스토어라는 영역도 공부하고 적용해 보겠습니다 ㅎㅎ

---

이번 미션동안 꼼꼼하게 리뷰해주시고 여러가지 인사이트와 더불어 유용한 링크도 많이 공유해주셔서 정말 많이 배웠습니다. 태경님도 남은 리뷰 잘 마무리하셨으면 좋겠습니다. 감사합니다 ㅎㅎ