3단계 - 의존성 리팩터링 PR 요청드립니다.
next-step/jwp-refactoring pull request #677
Opened 2022-12-12 15:20 UTC by earth-h

안녕하세요, 리뷰어님 :) 
3단계 PR 피드백 요청드립니다 ㅎㅎ

작업 전에 먼저, 우아한객체지향을 본 뒤에 시작하였는데요.
영상을 볼 때에는 어려워보이지 않았는데, 의존성 파악하는것도 시간이 꽤나 걸리는 작업이었습니다 ㅠ
- 관련해서, 2단계 merge 했을 시점 구조와 현 구조를 그려서 docs/내에 넣어두었습니다 :) 
  정확히 그렸는지 모르겠네요ㅠ😂

우선, 항상 조회하지 않는 연관관계는 최대한 끊으면서 패키지를 작게 유지할 수 있도록 패키지를 나누었습니다.
그런데, OrderLineItem/OrderLineItems/Order 과 Menu/MenuProduct/MenuProducts의 경우 사이클을 도는 것 같다는 생각이 드는데요..! 우선 이들은 각각 항상 같이 라이프사이클을 가져야 하고, MenuProducts는 사실상 MenuProduct이고, OrderLineItems는 OrderLineItem이라고 여겨서 해당 도메인들에 대한 연관관계는 끊지 않았습니다 !

항상 조회하지 않은 연관관계에 대해 레포지토리를 통해 조회하도록 함으로써 기존에 도메인에서 validation 체크하던 부분이 서비스쪽으로 빠진 부분이 존재하여 해당 부분은 validator를 생성하여 해당 클래스 내에서 진행하도록 하였습니다.

처음 생각은, validator가 존재하는 경우, validator에서 모든 정책 체크를 진행할까 하였으나 그렇게 할 경우 해당 도메인에 연관관계를 더 끊어야 하는 이슈가 있어 일부 validation에 대해서만 validator로 넣었습니다.
- 예) menu 도메인 내에서 menuProducts의 price를 비교하는 부분은 도메인에 그대로 두었습니다. 이 부분은 직접 레포지토리에 조회해서 가져오는 것보다 유리하다고 판단했습니다.
  - validation 이후에 객체 생성을 위해 menuProduct 생성을 위해 product를 조회하는 작업을 한 번 더 진행해야 했기 때문

여러 생각을 하면서 미션을 진행하였지만 부족한 부분이 많습니다..! 
앞선 두 단계에서도 피드백 주신 내용 통해 깨달은 점이 많아 좋은 피드백 기대하겠습니다 :) 감사합니다 !

2022-12-13 15:52 UTC, heowc requested changes
3단계를 잘 진행해주셨습니다!

다만, 약갼의 아쉬움이 있어 request change 드렸어요~
조금 더 연관관계를 끊어낼 수 없는지 한번 만 더 확인 부탁드릴게요 🙇 

궁금하신 점이나 의논할 것이 있다면 깃헙 코멘트나 슬랙 DM 으로 연락주세요 🙏

-----

> 우선 이들은 각각 항상 같이 라이프사이클을 가져야 하고, MenuProducts는 사실상 MenuProduct이고, OrderLineItems는 OrderLineItem이라고 여겨서 해당 도메인들에 대한 연관관계는 끊지 않았습니다 !

저도 동의합니다 👍 

> 처음 생각은, validator가 존재하는 경우, validator에서 모든 정책 체크를 진행할까 하였으나 그렇게 할 경우 해당 도메인에 연관관계를 더 끊어야 하는 이슈가 있어 일부 validation에 대해서만 validator로 넣었습니다.
>> validation 이후에 객체 생성을 위해 menuProduct 생성을 위해 product를 조회하는 작업을 한 번 더 진행해야 했기 때문

조회에 대한 비용으로 인해 이를 효율적으로 가져가고자 하신걸까요? 🤔

2022-12-13 15:52 UTC, heowc commented on src/main/java/kitchenpos/menu/domain/Menu.java
>          validateMenuProducts(price, menuProducts);
의존성을 제거하기 위해 validator 패키지에 도메인 서비스 역할의 클래스를 만들어주셨네요 👍
다만 이런 정책 관련 도메인 코드는 절차적인 형태일 때가 보거나 유지보수하기 쉬울 수 있습니다. MenuProducts 또한 validator 으로 옮겨보는건 어떨까요 🤔

2022-12-13 15:52 UTC, heowc commented on src/main/java/kitchenpos/menugroup/ui/MenuGroupRestController.java
> +package kitchenpos.menugroup.ui;
menu/menugroup/order/ordertable/product/tablegroup 를 각각의 도메인으로 보시는걸까요? 
그렇다면 각각의 도메인끼리는 모듈로 또는 별도의 애플리케이션으로 분리될 수 있다고 봐도 무방하다면 이것들은 서로 간접 참조하는것이 더 좋지 않을까 싶은데요. 어떻게 생각하시나요? 🤔

2022-12-13 15:52 UTC, heowc commented on src/main/java/kitchenpos/ordertable/application/TableService.java
> +        validateIfNotCompletionOrders(orders);
서비스 레이어보다는 도메인 레이어에 위치하는 것이 맞지 않을까요 🤔

2022-12-13 15:52 UTC, heowc commented on src/main/java/kitchenpos/ordertable/domain/OrderTables.java
> +    public List<OrderTable> findOrderTables() {
피드백 반영 👍

2022-12-13 15:52 UTC, heowc commented on src/main/java/kitchenpos/tablegroup/application/TableGroupService.java
> +        orderTables.ungroupOrderTables();
다른 도메인에서의 행위를 제거할 순 없을까요? 🤔

2022-12-13 15:52 UTC, heowc commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
>          orders.forEach(Order::validateIfNotCompletionOrder);
이 또한 validator 같은 클래스로 분리해볼 수 있지 않을까요 🤔

2022-12-13 15:52 UTC, heowc commented on src/test/java/kitchenpos/menu/domain/MenuTestFixture.java
> +    private static void validateMenuGroup(MenuGroup menuGroup) {
어떤 이유로 해당 코드가 추가되었을까요 🤔

2022-12-14 13:55 UTC, earth-h commented on src/test/java/kitchenpos/menu/domain/MenuTestFixture.java
> +    private static void validateMenuGroup(MenuGroup menuGroup) {
해당 코드가 추가된 사유는.. validation이 domain이 아닌, service단에서 validator.validate()의해 진행이 되다보니,
도메인 내에서 menuGroup 관련 validation이 사라져서 호출한 부분입니다..! 

그런데, 이거는 MenuTestFixture에 MenuValidator 직접 호출하는게 더 나을 것 같다는 생각이듭니다. 
수정해서 올려보겠습니다 ㅎㅎ

2022-12-14 13:56 UTC, earth-h commented on src/main/java/kitchenpos/menu/domain/Menu.java
>          validateMenuProducts(price, menuProducts);
이 부분은, 조회에 대한 비용으로 인해 도메인에서 진행하였는데요!
말씀해주신 것처럼, 이후 유지보수하기 편하기 위해서는 validator가 존재하는 한 validate 관련 기능은 validator에 모으는 것이 보기 좋을 것 같아 옮기고자 합니다 ㅎㅎ

모든 작업은 트레이드오프인거같네요..!

2022-12-14 14:06 UTC, earth-h commented on src/main/java/kitchenpos/menugroup/ui/MenuGroupRestController.java
> +package kitchenpos.menugroup.ui;
제가 판단하기로는, MenuProduct가 Product를 직접 참조하는거 외에는 각각 다른 도메인에 간접참조로 보이는데 혹시.. 직접 참조인 부분이 있을까요? ㅠ

제가 그림에 실수한 부분이 있어서, Menu > MenuGroup 참조를 직접 참조로 그렸지만 로직 상에서는 간접참조를 위해 menuGroupId로 필드 선언하였습니다 !

아무래도, Product과 MenuProduct간 직접 참조는 totalPrice() 계산 때문에 남겨둔 부분이 있는데요! 이 부분은 어떻게 끊어볼지 고민중이고, 그 외 다른 도메인에서 직접 참조가 있다면 코멘트 부탁드립니다..! 😭

2022-12-14 15:10 UTC, earth-h commented on src/main/java/kitchenpos/ordertable/application/TableService.java
> +        validateIfNotCompletionOrders(orders);
orderTable의 상태 변경 시, 해당 주문 테이블 내 주문들의 상태 체크를 하는 부분인데요!
orderTable과 order의 도메인이 달라 직접 참조를 막는다는 것이, validation 로직이 따로 validator도 아니면서 서비스레이어에 생겨버렸네요..! 수정하겠습니다 :)

2022-12-14 15:33 UTC, earth-h commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
>          orders.forEach(Order::validateIfNotCompletionOrder);
tableService와 tableGroupService에서 동일하게 order에 대해 주문 완료여부를 확인하고 있어
해당 부분을 orderValidator로 빼보았습니다 ! 피드백 감사합니다 :)

2022-12-14 15:34 UTC, earth-h commented on src/main/java/kitchenpos/tablegroup/application/TableGroupService.java
> +        orderTables.ungroupOrderTables();
아래 코멘트에 적은것과 동일하게, orderValidator 사용하는 방향으로 바꿔보았습니다 !

2022-12-14 15:36 UTC, earth-h commented
안녕하세요 !
주신 피드백 보면서, 로직 수정해보았습니다 :) 

OrderValidator에 validator() 메소드 외에 validateIfNotCompletionOrders()라는 validator public 메소드가 추가로 생성되었는데요..!
이렇게 하나의 validator 클래스 내에 public 메소드가 2개여도 되는 것인지 궁금합니다..

사내에서 사용할 때에는 보통, 한 validator()를 통해 진행을 하였는데 지금같은 경우 기존 validator()와 다른 상황의 validate라고 생각하여서 신규 메소드를 생성하였습니다.
- 그런데, validateIfNotCompletionOrders()가 생성됨에 따라 Order - OrderTable, Order - TableGroup 간의 참조가 순환이 된것인가 해서 이 부분 확인 요청드려도 괜찮을까요? 순환이라는게 정확히 클래스간 순환되면 안되는 것인지, 지금처럼 크게 Order 패키지와 OrderTable 패키지가 있을 때 Order 패키지에서 OrderTable 패키지를 참조하면, OrderTable 패키지에서 Order 패키지를 참조하면 안되는것인지 헷갈려서 여쭤봅니다 ㅠ

이외에도 주신 피드백 참고하여 수정해보았는데, 제대로 연관관계가 끊겼는지 피드백 부탁드리겠습니다 ! 
감사합니다 :)

2022-12-15 13:51 UTC, heowc commented on src/main/java/kitchenpos/menu/domain/Menu.java
>          validateMenuProducts(price, menuProducts);
맞아요... 선택의 연속이죠.. 🤣

2022-12-15 13:52 UTC, heowc commented on src/main/java/kitchenpos/menugroup/ui/MenuGroupRestController.java
> +package kitchenpos.menugroup.ui;
> Product과 MenuProduct간 직접 참조는 totalPrice() 계산 때문에 남겨둔 부분이 있는데요! 

그렇다면 이걸 남겨둔 이유는 무엇인가요~?

2022-12-15 13:58 UTC, earth-h commented on src/main/java/kitchenpos/menugroup/ui/MenuGroupRestController.java
> +package kitchenpos.menugroup.ui;
도메인에서 계산해야한다는 생각에 MenuProduct에 totalPrice() 로직을 넣었었습니다! 

그런데, 이는 productId를 통해 상품 조회하여서 Price 객체에 add() 및 multiply() 메시지를 던져도 되겠구나 하는생각이 들어 이번에 수정해두었습니다 :)

2022-12-15 14:01 UTC, heowc commented on src/main/java/kitchenpos/menugroup/ui/MenuGroupRestController.java
> +package kitchenpos.menugroup.ui;
👍  👍

2022-12-15 14:30 UTC, heowc commented
> OrderValidator에 validator() 메소드 외에 validateIfNotCompletionOrders()라는 validator public 메소드가 추가로 생성되었는데요..! 이렇게 하나의 validator 클래스 내에 public 메소드가 2개여도 되는 것인지 궁금합니다..

상관없다고 생각이 들어요. 보다 의미부여를 하여 검증 클래스를 만들면 더 좋겠다는 생각은 드는 것 같습니다 
하지만, 현재로는 지금 정도만으로도 충분해보여요 👍  

> * 그런데, validateIfNotCompletionOrders()가 생성됨에 따라 Order - OrderTable, Order - TableGroup 간의 참조가 순환이 된것인가 해서 이 부분 확인 요청드려도 괜찮을까요? 순환이라는게 정확히 클래스간 순환되면 안되는 것인지, 지금처럼 크게 Order 패키지와 OrderTable 패키지가 있을 때 Order 패키지에서 OrderTable 패키지를 참조하면, OrderTable 패키지에서 Order 패키지를 참조하면 안되는것인지 헷갈려서 여쭤봅니다 ㅠ

그러네요. validator로 인해 순환이 생긴 것 같습니다. (order, ordertable 간에)
패키지와 클래스 둘다 순환되는 것은 지양하는게 좋을 것 같아요

이를 어떻게 해결할 수 있을까요?
추가로, 이러한 참조는 테스트 또한 해당되는 부분입니다 🤔 

<img width="584" alt="스크린샷 2022-12-15 오후 11 32 09" src="https://user-images.githubusercontent.com/22594101/207887236-32b390f1-dcfe-4479-9e92-02a2aa05dc54.png">

참고: https://www.jetbrains.com/help/idea/dsm-analysis.html

2022-12-15 14:31 UTC, heowc approved these changes
빠르게 피드백 반영해주셔서 감사합니다 👍 

머지하기엔 충분한 것 같아 approve할게요~
다만 소소한 코멘트가 있으니 확인 부탁드립니다

궁금하신 점이나 의논할 것이 있다면 깃헙 코멘트나 슬랙 DM 으로 연락주세요 🙏

2022-12-15 14:31 UTC, heowc commented on src/test/java/kitchenpos/menu/application/MenuServiceTest.java
> -    @DisplayName("메뉴의 가격은 해당 메뉴에 존재하는 메뉴 상품들의 가격의 합보다 클 수 없다.")
적절하게 테스트를 리팩토링 해주셨네요 👍

2022-12-15 14:31 UTC, heowc commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    private Long productId;
👍

2022-12-15 14:31 UTC, merged