🚀 2단계 - 서비스 리팩터링 PR
next-step/jwp-refactoring pull request #680
Opened 2022-12-13 02:49 UTC by seogineer

2022-12-14 00:21 UTC, joojimin requested changes
안녕하세요~ 도경님!
미션진행 고생하셨습니다!
몇가지 궁금한 점 + 제안드릴게 있어서 코멘트 남겼습니다! 
확인한번 부탁드려요!

2022-12-14 00:21 UTC, joojimin commented on src/main/java/kitchenpos/application/MenuService.java
>              throw new IllegalArgumentException();
좀 더 의미가 명확한 Exception으로 변경해보면 어떨까요~? 아니면 Error 메세지라도 정의되어있으면 좋을 거 같은데 어떻게 생각하실까요?

2022-12-14 00:21 UTC, joojimin commented on src/main/java/kitchenpos/application/MenuService.java
> +        menu.validatePriceNull();
도메인으로 로직 잘 구성해주셨네요!!

2022-12-14 00:21 UTC, joojimin commented on src/main/java/kitchenpos/dao/MenuDao.java
> +public class MenuDao {
`JpaRepository`가 아닌 `JdbcTemplate`을 사용한 이유가 있을까요??

2022-12-14 00:21 UTC, joojimin commented on src/main/java/kitchenpos/domain/Menu.java
>  public class Menu {
지금까지 공부한 내용이 JPA 관련 리팩토링 연습이였는데요!! 이에 맞춰 해당 도메인도 Entity로 변경해보면 어떨까요?

2022-12-14 05:19 UTC, seogineer commented on src/main/java/kitchenpos/dao/MenuDao.java
> +public class MenuDao {
실무에서 레거시 코드를 리팩토링 한다고 가정했을 때 JPA를 사용하고 싶다고 함부로 JPA로 바꿀 수 있는 상황이 아니라고 생각해서 JPA를 사용하지 않고 리팩토링 중입니다.

2022-12-17 04:29 UTC, joojimin commented on src/main/java/kitchenpos/dao/MenuDao.java
> +public class MenuDao {
실무상황까지 생각하시다니 훌륭하십니다 👍 
저도 진짜 실무상황이라고 생각해보면 DB를 다루는 기술을 함부로 바꾸기 힘들었을 것 같아요!! 동의합니다!!
다만 저희가 배우던 기술이 JPA다보니 이번 교육과정은 JPA로 사용해보면 더 좋지않을까해서 제안드렸습니다 ㅎㅎ

2022-12-17 04:31 UTC, joojimin approved these changes
피드백 반영 고생하셨습니다 도경님!!
진심을 담아서 진행하시는 모습이 오히려 제가 배우고있는 것 같습니다!
이번 미션 바로 머지할께요! 마지막까지 화이팅입니다!

2022-12-17 04:31 UTC, merged