Step3 의존성 리팩터링 PR 리뷰 요청 드립니다.
next-step/jwp-refactoring pull request #692
Opened 2022-12-14 15:49 UTC by giraffelim

안녕하세요 영훈님! 3단계 미션 리뷰 요청 드립니다.
2단계에서 애그리거트 분리, 간접 참조, 도메인 서비스를 사용하도록 구현했더니 대부분의 의존성이 단방향으로 흐르고 있다고 생각이 되어,
우선 의존성 사이클이 생긴 부분만 의존성이 단방향으로 흐르도록 구성 하였는데 부족한 부분 코멘트 남겨주시면 감사하겠습니다.

2단계에서 달아주신 코멘트 중
> 오.. Menu Entity내에 MenuProducts라는 일급 클래스를 가지고 있어서, MenuProdicts 안에서 총합을 구할 수 있다고 생각했는데, 혹시 불가한 부분이 있을까요...?

 MenuEntity가 일급 컬렉션으로 MenuProducts를 구현하고 있지만 실제 MenuProduct 클래스 내부에는 Menu와 Product가 다른 애그리거트이기에 객체 참조 방식이 아닌 아래와 같이 ID만 가지고 있어, 실제 Product의 Price를 구해올 수가 없어 지금과 같이 MenuValidator에서 조회해서 계산하는 방향으로 구현했습니다.
```
@Embeddable
public class MenuProducts {
    @OneToMany(mappedBy = "menu", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<MenuProduct> menuProducts = new ArrayList<>();
  
    ...
}

@Entity
public class MenuProduct {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long seq;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "menu_id")
    private Menu menu;

    private Long productId;
```
따로 도메인 서비스를 추가한 뒤 도메인에 전달해 계산하라는 말씀이실까요?..

이번 단계도 잘 부탁드립니다. 🙇

2022-12-15 23:53 UTC, chae-yh requested changes
태양님 안녕하세요! step3도 코드 작성 잘해주셨습니다 👍 step2의 서비스 리팩터링 작업이 잘 되어 이번 step에서의 변화가 많지 않아 보이고, 해당 부분을 그림까지 그려가며 잘 표현해주셔서 좋았습니다 ㅎㅎ 다만 조금 더 고민해주시면 좋을만한 부분이 있어 코멘트 드리니 확인 부탁드립니다.

감사합니다 : )

2022-12-15 23:53 UTC, chae-yh commented on README.md
> +  - resource/static 경로에 개선 전 후 그림을 간략하게 그려두었습니다.
간단하게라도 기능 요구 작성 계속 해주셔서 좋네요 👍 
그리고 질문 주신 내용 여기서 답변 드리겠습니다.

`MenuEntity가 일급 컬렉션으로 MenuProducts를 구현하고 있지만 실제 MenuProduct 클래스 내부에는 Menu와 Product가 다른 애그리거트이기에 객체 참조 방식이 아닌 아래와 같이 ID만 가지고 있어, 실제 Product의 Price를 구해올 수가 없어 지금과 같이 MenuValidator에서 조회해서 계산하는 방향으로 구현했습니다.`

이 부분은 제가 코드를 잘못읽었습니다 ㅎ.ㅎ;; MenuProduct가 실제 객체를 가지고 있다고 착각을 해서 합을 구할 수 있다고 생각을 했는데, 실제로는 간접 참조임을 확인했습니다. 이 부분은 무시해주셔도 좋을 것 같아요..!

2022-12-15 23:53 UTC, chae-yh commented on README.md
> +## Step3 - 의존성 리팩터링
전체적인 구조에 관련된 부분이라 여기서 작성하겠습니다...!

```
2단계에서 애그리거트 분리, 간접 참조, 도메인 서비스를 사용하도록 구현했더니 대부분의 의존성이 단방향으로 흐르고 있다고 생각이 되어,
우선 의존성 사이클이 생긴 부분만 의존성이 단방향으로 흐르도록 구성 하였는데 부족한 부분 코멘트 남겨주시면 감사하겠습니다.
```

말씀하신대로 step2에서 이번 step의 목적인 의존성 리펙토링이 같이 작업되었기 때문에 실제 작업량이 많지 않은 것으로 보입니다. 👍 

코드를 볼 때 두 개 이상의 애그리거트의 참조가 필요할 경우 도메인 서비스를 적절히 구현해주셔서 잘 해결하신 것 같아요. 그런데 두 가지 애그리거트의 결합을 줄이기 위해 이벤트를 도입해보는 것은 어떨까요...? 예를 들어 테이블 그룹의 상태 변경(테이블 묶기, 테이블 해제 등)에 대한 이벤트를 발행하고, 해당 이벤트를 handle하는 방향으로도 서로간의 결합을 줄일 수 있을 것 같아요. 사실 테이블 그룹의 상태 변경은 결합을 반드시 줄여야하는 범위인지에 약간의 의문도 있지만, 학습의 대상으로 이벤트를 사용해보는 것도 좋아보입니다. ㅎㅎ 혹은 결합을 줄이면 좋을만한 부분을 탐색한 후 적용 시켜도 좋을 것 같아요..! 다음 단계는 모듈간의 분리 작업이 있게 되기 때문에 해당 작업을 하기 어려울 것 같아 이번 step에서 작업을 해보는 것은 어떨지 제안드려봅니다...!

2022-12-15 23:53 UTC, chae-yh commented on src/main/java/kitchenpos/order/domain/PlaceOrderValidator.java
> +    void validateTableEmpty(Long tableId);
의존성을 끊기 위해 만들어주신 것 같군요. 의존 역전 👍

2022-12-15 23:53 UTC, chae-yh commented on src/test/java/kitchenpos/ordertable/domain/OrderTableEmptyValidatorTest.java
> +class OrderTableEmptyValidatorTest {
구현체에 대한 테스트 👍

2022-12-16 07:17 UTC, giraffelim commented on README.md
> +## Step3 - 의존성 리팩터링
@chae-yh 
넵! 말씀해주신 것 처럼 학습의 기회로 이벤트를 도입해보도록 하겠습니다.
사실 이번 단계에서 이벤트를 사용해보고 싶어, 말씀하신 것 처럼 테이블 그룹의 상태 변경 시 이벤트를 발행하는 쪽으로 생각을 했었는데, 이번 기회에 적용하며 학습해보도록 하겠습니다. 👍

2022-12-16 14:15 UTC, giraffelim commented on README.md
> +## Step3 - 의존성 리팩터링
@chae-yh 
안녕하세요 영훈님!
말씀해주신 것 처럼 학습에 의의를 두고 이벤트를 도입해보았습니다!, 예로 들어주신 상황(테이블 그룹의 상태 변경)이 제일 적절할 것 같아 트리거 방식으로 구현 해보았습니다. AbstractAggregateRoot를 이용한 도메인 이벤트 발행을 처음 사용해보았는데 알맞게 사용한 것인지 잘 모르겠네요. 🤔
테이블 삭제 시 Hard Deletion으로 구현되어 있어 그렇게 구현하다보니, OrderTable의 외래 키 제약이 문제가 되어 softDeletion으로 변경할까 하다가 도메인 이벤트를 학습해보는게 목표이니 우선 sql 파일에서 외래키를 제거하는 방향으로 처리했습니다. 😅
TableGroupService를 기존 Mock을 사용하던 방식에서 이벤트 전달 테스트를 위해 `@SpringBootTest` 방식으로 변경하고, 구현체인 Handler를 Mock을 이용해 테스트 하는 방향으로 변경해보았습니다. 올바르게 테스트를 진행한 것 일까요? 
더 좋은 방법이 있다면 알려주시면 감사하겠습니다. 🙇‍♂️

2022-12-17 11:51 UTC, chae-yh approved these changes
태양님 안녕하세요. 피드백 잘 반영해주셨습니다 💯 참고해주시면 좋을만한 내용에 대해서 코멘트 드렸으나, 그 외의 특별히 수정 요청 드릴만한 내용은 없는 것 같습니다 ㅎㅎ

이제 마지막 step이네요. 파이팅 입니다 : )

2022-12-17 11:51 UTC, chae-yh commented on src/main/java/kitchenpos/ordertable/domain/TableGroupedEventHandler.java
> +    @EventListener
transaction 처리 시에 이슈가 발생할 수도 있을 것 같은데, `@TransactionalEventListener 을 사용해보면 어떨까요...?

2022-12-17 11:51 UTC, chae-yh commented on src/main/java/kitchenpos/ordertable/domain/TableGroupedEventHandler.java
> +public class TableGroupedEventHandler {
이벤트 처리 👍

2022-12-17 11:51 UTC, chae-yh commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +public class TableGroup extends AbstractAggregateRoot<TableGroup> {
AbstractAggregateRoot를 상속해서 이벤트 처리하는 방법은 저도 사실 많이 사용하지는 않는 형태입니다 ㅎ.ㅎ;; 

저 같은 경우는 ApplicationEventPublisher를 의존해서 사용하는데, 보통 아래와 같이 의존을 추가하고, 
`private final ApplicationEventPublisher applicationEventPublisher;`
아래와 같이 이벤트를 발행하는 방법을 사용합니다.
`applicationEventPublisher.publishEvent(XXXEvent.of(XXX.getId(), XXX.method()));`

AbstractAggregateRoot를 사용하니, 이벤트 처리가 코드로 나오지 않고 바로 Entity에서 확인할 수 있어서 간편한 점이 있는 것 같네요. 구현도 잘해주신 것 같습니다 👍

2022-12-17 11:51 UTC, chae-yh commented on src/main/resources/db/migration/V1__Initialize_project_tables.sql
> -ALTER TABLE order_table
외래키 제약 조건은 사실 이런 식으로 사용하기 까다로운 점이 있습니다. 그래서 저희의 경우는 실제 서로 참조관계가 있더라도 운영환경에서는 외래키를 강제로 사용하는 부분은 반드시 제거한 후 테이블을 만들어줍니다. 이 부분은 참고만 부탁드립니다 ㅎㅎ

2022-12-17 11:51 UTC, chae-yh commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +    @PreRemove
엔티티 삭제 전에 실행해줄 수 있는 형태군요 👍

2022-12-17 11:51 UTC, chae-yh commented on src/test/java/kitchenpos/ordertable/domain/TableGroupedEventHandlerTest.java
> +class TableGroupedEventHandlerTest {
이벤트 핸들러 테스트 👍

2022-12-17 11:51 UTC, chae-yh commented on src/test/java/kitchenpos/tablegroup/application/TableGroupServiceTest.java
> +@SpringBootTest
이벤트 발행 시 해당 처리 확인을 위해 SpringBootTest로 바꿔주신 것 같네요..! 여기는 service layer의 슬라이싱 테스트 이므로, 이벤트는 잘 발행되었다고 가정하고(mocking) 테스트를 작성해도 좋을 것 같습니다만, 제 생각에는 현재 해당 형태도 좋을 것 같습니다 👍

2022-12-17 11:51 UTC, chae-yh commented on src/main/java/kitchenpos/tablegroup/domain/TableGroupedEvent.java
> +public class TableGroupedEvent {
이벤트도 과거형으로 잘 표현했네요 👍

2022-12-17 11:51 UTC, merged

2022-12-17 13:25 UTC, giraffelim commented on src/main/java/kitchenpos/tablegroup/domain/TableGroup.java
> +public class TableGroup extends AbstractAggregateRoot<TableGroup> {
@chae-yh 
말씀해주신 것 처럼 AbstractAggregateRoot를 사용하면 이벤트 처리가 추상화 되어 있다는 장점이 있는데, 영훈님께서는 어떠한 장점 때문에 ApplicationEventPublisher를 사용하시는지 궁금합니다..!

2022-12-17 13:25 UTC, giraffelim commented on src/main/java/kitchenpos/ordertable/domain/TableGroupedEventHandler.java
> +    @EventListener
@chae-yh 
넵! 공부해보도록 하겠습니다. 감사합니다. 🙇‍♂️