[김은혜] Step2 서비스 리팩터링 PR 요청
next-step/jwp-refactoring pull request #726
Opened 2022-12-17 19:36 UTC by eunveloper

안녕하세요 두번째 과제로 돌아왔습니다!

와... 우테캠 모든 과정중에서 가장 오래걸렸고 가장 힘들었습니다 ㅠㅠ
해도해도 끝이 나지 않은거 같아서 끝이 나려나 싶었는데 다행히 끝이 났네요 ㅠㅠ

한 작업은 크게
1. 패키지 구조 변경
2. JAP Entity 방식으로 변경
3. 서비스 로직 리팩토링 (서비스 레이어 -> 도메인 레이어 이관)
4. 테스트코드 수정
5. 도메인 단위테스트 추가 개발
입니다!

이번 피드백도 잘 부탁드립니다!

2022-12-18 06:41 UTC, seokhongkim requested changes
은혜님, 2단계 미션 잘 구현해주셨습니다. 👍 

코드 양이 많고 의존 관계도 복잡해서 미션 진행하는데 힘드셨을 것 같아요.
도메인으로 코드를 이동하면서 패키지 구조도 함께 변경하셔서 미션을 진행할 때 더 어려우셨을 것 같네요.

코드 변경이 많아서 코멘트 양도 많은데, 대부분 각 서비스, 도메인에 대해 중복되는 내용입니다.
코멘트 확인 부탁드립니다. 🙏

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        return menuGroupRepository.findById(menuGroupId).orElseThrow(IllegalArgumentException::new);
1. 예외 메시지에 요청된 값을 포함해서 전달하면, 문제 상황에서 어떤 값으로 인해 문제가 발생했는지 추적할 때 도움이 됩니다. :)
`menuGroupId`를 포함해서 메시지를 만들어서 예외를 발생시켜 보시면 좋겠습니다.
2. 엔티티가 존재하지 않을 때 `IllegalArgumentException`을 사용하신 이유가 있을까요?

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/domain/Price.java
> +public class Price {
`Price`는 `domain` 패키지로 남겨 놓으신 이유가 있을까요?

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public MenuResponse create(final MenuRequest menuRequest) {
`MenuProducts`를 먼저 만드신 후, `Menu`를 생성할 때 `MenuProducts`를 포함해서 생성해보시면 좋겠습니다.

`Menu`는 존재하는 상품으로만 만들 수 있고, 상품 가격의 합보다 큰 가격을 가질 수 없다는 제약 조건이 있습니다. 이 부분을 `validate`로 구현하셨을 것 같아요.
다른 개발자가 `Menu`를 사용할 때 `validate`를 호출하지 않으면 어떻게 될까요?

반드시 필요한 값은 생성자에서 인자로 받는 것이 좋고, 필요한 밸리데이션도 생성자에서 진행하면 실수를 방지하는데 도움이 될 것 같습니다. :)

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public void validatePrice(Price sum) {
외부에 제공해야 하는 기능이 아니라면 private 접근 제어자를 사용해보시면 좋겠습니다. :)

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        List<Menu> menus = menuRepository.findAll();
전체 메뉴를 조회하면 N+1 쿼리가 발생할 것 같아요.
fetch join 을 사용하거나, hibernate batch size 를 이용해서 N+1 쿼리를 방지할 수 있는 방법을 학습해보고 적용하시면 좋겠습니다. :)

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +    public MenuGroupResponse create(final MenuGroupRequest menuGroupRequest) {
서비스의 인자와 반환 값으로 도메인을 사용하지 않고, dto 를 사용하신 이유가 있는지 궁금합니다.

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        Order order = Order.create(orderTable, OrderStatus.COOKING.name(), LocalDateTime.now());
여기도 주문을 만드는 시점에 orderLineItems 가 필요하다면, Order 생성자의 인자로 전달 받아보시면 좋겠습니다. :)
`validate` 메서드도 생성자에서 호출할 수 있겠네요!

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        final List<Order> orders = orderRepository.findAll();
여기도 N+1 쿼리가 발생할 것 같아요!

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +    private OrderTable getOrderTable(Long orderTableId) {
`OrderTable`, `Menu`를 아이디로 조회하고 엔티티가 없을 때 예외를 발생시키는 기능을 각 도메인의 서비스에서 제공해주면 어떨까요?
서비스의 응집도가 올라가고, 비슷한 코드를 사용하는 다른 곳에서도 재사용이 가능하다는 장점이 있습니다.

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/order/domain/OrderValidator.java
> +    public static void validateParam(List<OrderLineItemRequest> orderLineItems) {
이 밸리데이션은 order 에서 직접 할 수도 있을 것 같네요!

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/order/domain/OrderValidator.java
> +    public static void validateMenus(List<OrderLineItemRequest> orderLineItems, long menuCount) {
`OrderLineItem`을 만드는 과정에서 존재하지 않는 menu 가 있으면 예외가 발생하도록 되어 있네요.
이 밸리데이션이 없어도, 위 과정에서 존재하는 메뉴에 대해서만 주문이 가능할 것으로 보이네요!

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/order/repository/OrderRepository.java
> +    boolean existsByOrderTableIdInAndOrderStatusIn(List<Long> orderTableIds, List<String> asList);
1. `asList`에는 무슨 값이 들어있을까요?
2. `OrderStatus` enum 이 있는데, `String` 타입을 사용하신 이유가 있을까요?

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        OrderTable orderTable = OrderTable.create(null, orderTableRequest.getNumberOfGuests(), orderTableRequest.isEmpty());
`TableGroup`이 필수값이 아니라면, 생성자를 오버로딩해서 `TableGroup`이 없는 경우에 사용할 생성자를 만들어보시는 것도 좋겠습니다.

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        List<OrderTable> menuGroups = orderTableRepository.findAll();
여기도 N+1 쿼리가 발생할 수 있겠네요!

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +public class OrderTableService {
클래스에 `@Transactional` 설정을 추가해보셔도 좋겠습니다. :)

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        savedOrderTable.validateExist();
`validateExist`라는 이름을 봤을 때, `OrderTable`이 존재하는지 검증하는 것처럼 보이기도 하네요.
`validateGrouped`와 같은 이름을 사용해보는 건 어떨까요?

또한, 이 밸리데이션이 `empty` 상태로 변경하기 위해 반드시 필요한 것이라면, `updateEmpty` 메서드 내부에서 직접 밸리데이션 메서드를 호출하도록 구현해보시면 좋겠습니다.

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(
`order` -> `table` 패키지로 의존성이 있는데, `table` -> `order` 패키지로도 의존성이 생기면서 순환참조가 발생하게 되네요.
의존성이 단방향이 되도록 개선해보시면 좋겠습니다. :)

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/table/domain/TableGroup.java
> +    private OrderTables orderLineItems = new OrderTables();
변수명이이 `orderLineItems`가 아닌 `orderTables` 겠죠?

2022-12-18 06:41 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        for (OrderTable savedOrderTable : savedOrderTables) {
`orderTable`과 `tableGroup` 간에도 순환참조가 되지 않도록 의존방향을 한 방향으로 개선해보시면 좋겠습니다. :)
`tableGroup`을 생성할 때 필수인 값을 생성자의 인자로 추가하고, 밸리데이션도 `tableGroup` 내부에서 수행해보셔도 좋겠습니다.

2022-12-18 06:41 UTC, seokhongkim commented on src/test/java/kitchenpos/menu/unit/MenuTest.java
> +package kitchenpos.menu.unit;
테스트의 패키지를 프로덕션 코드와 동일하게 맞춰서 작성하시면 좋겠습니다.
도메인 클래스에 대한 단위 테스트라면 `kitchenpos.menu.domain` 패키지가 되겠네요!

2022-12-18 06:41 UTC, seokhongkim commented on src/test/java/kitchenpos/menu/application/MenuGroupServiceTest.java
> +public class MenuGroupServiceTest {
단위 테스트 꼼꼼하게 잘 작성해주셨네요! 👍

2022-12-18 14:46 UTC, eunveloper commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        return menuGroupRepository.findById(menuGroupId).orElseThrow(IllegalArgumentException::new);
기존에 사용한 예외를 그대로 이용해서 그런거 같아요!
사용자 정의 예외를 구현에서 상황에 맞는 예외와 메세지를 던져보도록 할게요!

2022-12-18 14:48 UTC, eunveloper commented on src/main/java/kitchenpos/domain/Price.java
> +public class Price {
Price 객체가 도메인으로서 비지니스 로직의 행위를 가지고 있어서 도메인 패키지에 넣어놨는데
또 여러 패키지 도메인이 공용으로 사용하다보니 공용 도메인 객체라고 생각이 들어서 일부 서비스 패키지에 종속시키지 않고 따로 빼보았습니다!

2022-12-19 13:37 UTC, eunveloper commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public MenuResponse create(final MenuRequest menuRequest) {
`다른 개발자가 Menu를 사용할 때 validate를 호출하지 않으면 어떻게 될까요?`

오... 이부분은 생각치도 못한 부분이었네요! 수정해보겠습니다!

2022-12-19 13:37 UTC, eunveloper commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public void validatePrice(Price sum) {
아마 단위테스트를 구현하면서 퍼블릭으로 변경된거 같습니다 ㅠㅠ

2022-12-19 13:39 UTC, eunveloper commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +    public MenuGroupResponse create(final MenuGroupRequest menuGroupRequest) {
도메인은 데이터베이스의 엔티티와 매핑이 되는 객체로서 서비스 레이에서 - 레파지토리 레이어간에
데이터 베이스 통신을 위한 객체라고 생각했습니다.

실제로 도메인 객체 자체로 API 요청과 응답을 하면 실제로 사용되지 않을 필드(컬럼) 들도 많고
각 레이어에 맞지 않는 행위의 객체들이 사용되는것 같아서 수정하였습니다!

2022-12-19 13:43 UTC, eunveloper commented on src/main/java/kitchenpos/order/application/OrderService.java
> +    private OrderTable getOrderTable(Long orderTableId) {
제가 이 부분을 다른분과 과제를 진행할때도 이야기를 나눈 부분인데요.

한 도메인 서비스에서 필요한 다른 도메인의 repository에 직접 접근하여 데이터를 가져오는것과
한 도메인 서비스에서 필요한 다른 도메인의 서비스에 메소드를 호출하여 데이터를 가져오는것중에 어떤게 좋을지 였습니다.

그때 제 의견은 
전자는 동일한 레파지토리에 접근하여 예외를 내는 부분이 각 서비스 레이어마다 중복이 된다는 것이었고
후자는 서비스간에 의존도가 높아서 양방향 의존관계를 야기할 수 있는 부분이 단점이라고 말씀드렸습니다.

그때 리뷰어 분은 전자를 택하면서 레파지토리에 접근하는 일부 소스가 중복될순 있지만,
이 또한 하나의 비지니스 로직이라고 생각할수 있기때문에 변경의 여지를 두고 따로 가져가고
서비스의 의존도를 낮추는게 좋을거 같다는 결ㄹ론이 나왔었는데요!

이번 리뷰어님은 반대로 생각하시는듯 해서요~! 혹시 이런 내용을 어떻게 생각하시나요?

2022-12-19 13:45 UTC, eunveloper commented on src/main/java/kitchenpos/order/repository/OrderRepository.java
> +    boolean existsByOrderTableIdInAndOrderStatusIn(List<Long> orderTableIds, List<String> asList);
1. 앗 이부분은 제가 메소드 자동 생성을 하면서 차마 확인을 못한 부분이네요 ㅠㅠ
2. enum의 내부함수인 name() 을 이용하여 String 객체를 사용하였습니다!

2022-12-19 13:47 UTC, eunveloper commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        OrderTable orderTable = OrderTable.create(null, orderTableRequest.getNumberOfGuests(), orderTableRequest.isEmpty());
생성자를 다양하게 들고가는것에 대해서 어떻게 생각하시나요?
저도 적재적소에 사용해야 한다고 생각하긴 하지만,
예전에 클린코드 책에서 읽었을때 오버로딩하여 생성자를 계속 추가하면 개발자들이 그 생성자를 항상 접근하여
어떤 필드를 수정하는지 확인해야한다는 단점이 있다고 봤었습니다!

저는 기본생성자와 엔티티 내부의 필수 정보들만 세팅해주는 아규먼트가 있는 생성자만 두개 만드는걸 선호하는 편인데...

리뷰어님은 어떻게 생각하시나요?

2022-12-19 13:47 UTC, eunveloper commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +public class OrderTableService {
앗 이곳에 누락이 되어있군요 ㅠㅠ 확인 감사드립니다

2022-12-19 13:48 UTC, eunveloper commented on src/main/java/kitchenpos/table/domain/TableGroup.java
> +    private OrderTables orderLineItems = new OrderTables();
앗 넵 :) 또 누락이 되어있네요 ㅠㅠ

2022-12-19 13:48 UTC, eunveloper commented on src/test/java/kitchenpos/menu/unit/MenuTest.java
> +package kitchenpos.menu.unit;
수정하겠습니다 :)

2022-12-19 16:22 UTC, eunveloper commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        OrderTable orderTable = OrderTable.create(null, orderTableRequest.getNumberOfGuests(), orderTableRequest.isEmpty());
코드를 수정하면서 필요에 따른 부분은 적절히 수정해보겠습니다 :)!

2022-12-19 16:48 UTC, eunveloper commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    public MenuResponse create(final MenuRequest menuRequest) {
함수로 구성한 validate 들을 서비스 레이어에서 단독으로 호출하는게 아닌
생성자를 통해 객체가 생성될때 내부에서 호출하도록 수정해보겠습니다

2022-12-19 17:59 UTC, eunveloper commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        List<Menu> menus = menuRepository.findAll();
맞습니다! 일대다의 관계에서 List 객체를 탐색이 된다면 쿼리 한번으로 데이터를 가져오는것이 아닌 리스트 수만큼 쿼리를 요청하여 N+1 이라는 큰 성능이슈가 있겠네요

fetch join 방식을 도입하겠습니당!

2022-12-22 15:39 UTC, eunveloper commented on src/main/java/kitchenpos/order/domain/OrderValidator.java
> +    public static void validateMenus(List<OrderLineItemRequest> orderLineItems, long menuCount) {
앗 어느부분에서 검증이 진행될까요? ㅠㅠ
제가 소스코드를 훑어봤는데, 메뉴의 여부를 조회하거나 하는 곳이 없는거 같아서요!
이 부분에서 메뉴가 데이터베이스에 있는지 여부를 확인하는거 같거든요!

2022-12-22 15:41 UTC, eunveloper commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        savedOrderTable.validateExist();
그렇네요! validateExist 명칭이, 특히 exist 라는 동사는 개발하면서도 존재여부를 확인할때 많이 사용하니까 혼동의 여지가 있을거 같아요!

밑에 피드백도 정말 좋은 피드백이신거 같아요! 개발자가 따로 벨리데이션 체크 메소드를 호출하지 않아도!
업데이트를 해야하니 업데이트 로직만 호출해도! 자동으로 벨리데이션 체크를 해주겠네요 ㅎㅎㅎ

2022-12-22 16:33 UTC, eunveloper commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        for (OrderTable savedOrderTable : savedOrderTables) {
여러 피드백과 동일한 내용인거 같은데요.

서비스 - 여러 레파지토리의 의존관계
서비스 -> 서비스 간의 단반양 의존관계 에 대한 케이스 인거 같은데 제가 잘 이해한게 맞을까요?

테이블 그룹과 주문 테이블의 관계는 도메인끼리의 의존 방향이 확실하니
리뷰어님의 말씀처럼 서비스 간의 단방향 의존관계도 괜찮을거 같아요.

테이블 그룹을 만들때, 주문 테이블이 존재해야 하니, 단뱡향으로 변경해 보겠습니다!

2022-12-22 16:39 UTC, eunveloper commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        for (OrderTable savedOrderTable : savedOrderTables) {
벨리데이션 작업은 모두 도메인으로 이관하면서 요구사항을 만족한거 같은데,
순환참조라는 부분이 이해가 잘 되지 않는데요.

TableGroup의 서비스 레이어에서 OrderTable을 조회해오고 해당 Ordertable을 가공하는 행위가 순환참조가 된다는 말씀이실까요?

2022-12-22 16:47 UTC, eunveloper commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        for (OrderTable savedOrderTable : savedOrderTables) {
1. 주문 테이블을 생성할때는 테이블 그룹에 의존하지 않게 변경하고
2. 테이블 그룹을 생성할때는 요청이 온 주문 테이블을 먼저 확인하고 그 값을 가지고 테이블 그룹을 생성하도록 변경하였습니다.

2022-12-22 17:14 UTC, eunveloper commented
안녕하세요 리뷰어님! 두번째 피알이 좀 늦어졌습니다 ㅠㅠ!

전첵으로 작업한 리스트들은
1. 사용자 정의 예외처리
2. 각종 validation 체크 로직을 도메인에서 구현
3. 각종 미비한 패키지 명 함수명 파라미터명 변경
4. N+1 가능성 쿼리 fetchjoin으로 변경
5. 양방향 의존관계 변경

2022-12-23 11:01 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        return menuGroupRepository.findById(menuGroupId).orElseThrow(IllegalArgumentException::new);
리팩터링 과정에서 기존과 동일한 상황에서 동일한 예외를 사용하도록 유지하신 점 좋습니다. :)

2022-12-23 11:04 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public void validatePrice(Price sum) {
private method 의 테스트는 두 가지 방향으로 고민해보시면 도움이 될 것 같습니다.
* public method 를 테스트하는 과정에서 함께 테스트를 진행한다.
  * private method 는 public method 의 부분 동작이므로, public method 를 테스트하는 과정에서 자연스럽게 private method 도 테스트가 되어야 합니다.
* private method 를 별도의 클래스로 분리한다.
  * 테스트가 너무 복잡해진다면, 어쩌면 한 클래스가 너무 많은 역할을 가지고 있기 때문일수도 있습니다. 필요에 따라 별도의 클래스로 분리하는 방법을 고민해보셔도 좋겠습니다.

2022-12-23 11:07 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +    public MenuGroupResponse create(final MenuGroupRequest menuGroupRequest) {
말씀하신 이유도 이해가 되네요!
현재는 프리젠테이션 레이어가 하나지만, 추후 다양한 프리젠테이션 레이어가 추가되면서 각 프리젠테이션 레이어에서 사용하는 DTO의 형태가 다를 경우 이를 서비스 레이어에서 제공하는 것이 맞을지도 고민해보시면 좋겠습니다. :)
예를 들면, 현재는 API만 있지만, 화면을 내려줄 때 서버사이드 렌더링을 위해 데이터를 포함한다거나, 배치, 이벤트 컨슈머 등이 추가되는 경우 이들은 프리젠테이션 레이어가 될 수 있습니다.

2022-12-23 11:10 UTC, seokhongkim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +    private OrderTable getOrderTable(Long orderTableId) {
저는 서비스간의 의존도는 도메인의 의존 방향과 동일하다면 괜찮다고 생각합니다.
예를 들면, `Order` -> `OrderTable` 도메인으로 의존 관계가 있다면, `OrderService` -> `OrderTableService` 의존 관계도 추가되어도 괜찮다고 생각합니다.

프로젝트가 커지면서 monolithic architecture 에서 micro services architecture 로 변경되면 특정 도메인이 별도의 시스템으로 분리되는 경우가 있는데, 이때 데이터 조회는 서비스를 통해서만 사용하면 서비스를 분리하는 과정이 좀 더 수월할 수 있다고 생각합니다. 또한, 이 과정에서 자연스럽게 서비스에 의존하도록 변경이 필요하므로(분리된 시스템에서 API 제공 필요), 서비스에 의존하는 것이 문제가 되지는 않는다고 생각합니다.

2022-12-23 11:13 UTC, seokhongkim commented on src/main/java/kitchenpos/order/repository/OrderRepository.java
> +    boolean existsByOrderTableIdInAndOrderStatusIn(List<Long> orderTableIds, List<String> asList);
`Order` 에서 `orderStatus` 필드를 `OrderStatus` 타입으로 관리하시고, `@Enumerated(value = EnumType.STRING)` 으로 관리해보셔도 좋겠습니다.
enum 값을 만드셨으니, 가능하면 `String` 타입으로 변경하기보다는 enum 을 그대로 사용하시는 것이 더 안정적인 코드를 만드는데 도움이 될 것 같습니다.

2022-12-23 11:15 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +        OrderTable orderTable = OrderTable.create(null, orderTableRequest.getNumberOfGuests(), orderTableRequest.isEmpty());
생성자를 계속 추가하면 말씀하신 문제가 발생할 수 있겠네요!
생성자는 기본 생성자와 모든 필드를 받는 생성자를 놓고, static factory method 를 만들어보는 건 어떨까요? :)

2022-12-23 11:23 UTC, seokhongkim commented on src/main/java/kitchenpos/order/domain/OrderValidator.java
> +    public static void validateMenus(List<OrderLineItemRequest> orderLineItems, long menuCount) {
`OrderService#create` 메서드의 아래 코드에서 `getMenu`를 할 때, 존재하지 않는 메뉴 아이디면 예외가 발생할 것으로 보이네요!
```java
Menu menu = getMenu(orderLineItemRequest.getMenuId());

OrderLineItem orderLineItem = OrderLineItem.create(menu, orderLineItemRequest.getQuantity());
```

2022-12-23 11:23 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        Price sumPrice = Price.create(BigDecimal.ZERO);
`Price.ZERO` 와 같은 값을 상수로 저장해놓고 재사용해도 좋을 것 같습니다. :)

2022-12-23 11:23 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +            sumPrice.add(product.getPrice().multiply(BigDecimal.valueOf(menuProductRequest.getQuantity())));
`Price`는 불변 객체로 만들어보셔도 좋겠습니다.
그럼 이 코드도 `sumPrice = sumPrice.add()`로 변경이 필요하겠네요!

2022-12-23 11:23 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/OrderTableService.java
> +public class OrderTableService {
클래스의 `@Transactional` 에서 `readOnly` 속성을 true 로 관리하신 이유가 있는지 궁금합니다. :)

2022-12-23 11:25 UTC, seokhongkim approved these changes
은혜님, 2단계 미션 코멘트 잘 반영해주셨습니다. 👍 
2단계 PR은 머지하겠습니다.

다음 단계 미션을 진행하며 도메인 분리와 관련된 부분을 추가로 진행할 수 있을 것 같습니다.
코멘트 남긴 내용도 다음 단계 미션을 진행하실 때 참고 부탁드립니다.
3단계 미션에서 뵙겠습니다. 😀

2022-12-23 11:25 UTC, merged