Step3 - 의존성 리팩토링 리뷰요청드립니다.
next-step/jwp-refactoring pull request #753
Opened 2022-12-20 07:11 UTC by aksgudwns

안녕하세요 3단계 리뷰요청 드립니다.

entity_dependency_before.jpeg에 step2에서 엔티티간의 의존관계를 그려보고,
entity_dependency_after.jpeg에 step3에서 작업할 엔티티간의 의존관계를 미리 설계하고 작업해보았습니다.

package안에서는 Event Handler를 활용하여 양방향관계를 해소하고 단방향관계를 유지하였습니다.
타패키지에 있는 엔티티는 직접참조하지 않고, id만 가지고 있다가 Validator를 호출하여 필요한 유효성 체크와 response dto데이터 조회를 위한 작업을 진행하였습니다.

response dto작업 때문에 소스가 계속 복잡해지고 방대해지는 느낌을 받았습니다.
특히 Order쪽에서 메뉴부터 상품정보까지 조회하다 보니 많은 Validator를 가지게 되었습니다...

이번리뷰도 잘 부탁드리며,
수정이나 보완 필요한 부분 있다면 커멘트 부탁드리겠습니다 :)

감사합니다.

2022-12-20 14:46 UTC, heowc requested changes
의존성 리팩토링을 진행해주셨네요! 😄 

이대로 머지하기엔 다소 아쉬운 부분이 있어 requeset changes 드렸습니다.
코멘트 확인해보시고 궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

2022-12-20 14:46 UTC, heowc commented on src/main/java/kitchenpos/menu/application/MenuService.java
>          return menuRepository.findAll()
전체 메뉴를 조회시, 메뉴를 검증하는 것이 다소 어색한 것 같습니다 🤔 
여기서 메뉴를 검증해야할 필요가 있을까요?

2022-12-20 14:46 UTC, heowc commented on src/main/java/kitchenpos/order/application/OrderService.java
> +            final MenuProductValidator menuProductValidator,
주문의 경우 어쩔 수 없이 많은 도메인들과 의존을 맺고있네요, 다른 도메인서비스가 아닌 (가령 table, menu 와 협업하는 validator 등..)을 통해 조금 더 느슨한 구조로 갈 수 없을까요? 🤔

2022-12-20 14:46 UTC, heowc commented on src/main/java/kitchenpos/product/domain/MenuProducts.java
> +        }
생성자에서 파라미터가 없는데 의미있는 로직일까요? 🤔

2022-12-20 14:46 UTC, heowc commented on src/main/java/kitchenpos/order/domain/OrderEventHandler.java
> +    @EventListener
`@TransactionalEventListener`라는 것이 있는데 이것과 어떤 차이가 있을까요 ? 🤔

2022-12-20 14:46 UTC, heowc commented on src/main/java/kitchenpos/product/domain/Price.java
> +    private static final BigDecimal MINIMUM_PRICE = BigDecimal.ZERO;
피드백 반영 👍

2022-12-20 14:46 UTC, heowc commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        tableGroupRepository.delete(tableGroup);
도메인 레이어에 비즈니스 로직이 있어야 하는 오히려 이벤트가 그 로직을 처리를 함으로써 역할을 해야할 주체가 바뀐 것 같습니다. 어떻게 생각하시나요? 🤔

2022-12-20 14:46 UTC, heowc commented on src/main/java/kitchenpos/order/domain/OrderValidator.java
> +    public Order findOrderByOrderTableId(Long orderTableId) {
저는 리팩토링 미션을 하면서 인텔리제이에서 DSM이라는 도구를 알게 되었는데요. 이를 통해 순환 참조되는 것을 분석할 수 있습니다.

<img width="685" alt="스크린샷 2022-12-20 오후 11 43 37" src="https://user-images.githubusercontent.com/22594101/208693567-25adf126-bc98-4b43-918d-af6a91c1efca.png">

이 도구를 통해 살펴보면, 패키지간의 순환되는 모습을 볼 수 있는데요.
확인해보시고 패키지간의 순환참조가 되지 않고 단방향으로 흐를 수 있도록 다시 한번 고민해주셨으면 좋겠습니다 🙏

2022-12-22 18:00 UTC, aksgudwns commented on src/main/java/kitchenpos/product/domain/MenuProducts.java
> +        }
밑에 생성자에 들어가야 하는데 잘못 들어갔네요..
수정하였습니다!

2022-12-22 18:02 UTC, aksgudwns commented on src/main/java/kitchenpos/menu/application/MenuService.java
>          return menuRepository.findAll()
검증하는 로직은 없고.. 엔티티 조회하는 로직만 있었는데, Validator클래스를 사용해서 읽는 사람이 혼란스러울 수 있을 것 같습니다!
수정하겠습니다!

2022-12-22 18:03 UTC, aksgudwns commented on src/main/java/kitchenpos/order/domain/OrderValidator.java
> +    public Order findOrderByOrderTableId(Long orderTableId) {
좋은 기능 알려주셔서 감사합니다!
앞으로 자주 사용할 것 같습니다 :)
참고하여서 단방향으로 흐를 수 있도록 수정하겠습니다!

2022-12-22 18:04 UTC, aksgudwns commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        tableGroupRepository.delete(tableGroup);
좀 더 도메인 지향적으로 소스 수정해보겠습니다!

2022-12-22 18:04 UTC, aksgudwns commented on src/main/java/kitchenpos/product/domain/Price.java
> +    private static final BigDecimal MINIMUM_PRICE = BigDecimal.ZERO;
감사합니다 :)

2022-12-22 18:31 UTC, aksgudwns commented on src/main/java/kitchenpos/order/application/OrderService.java
> +            final MenuProductValidator menuProductValidator,
OrderMapper를 이용하여 수정해보겠습니다!

2022-12-22 18:39 UTC, aksgudwns commented on src/main/java/kitchenpos/order/domain/OrderEventHandler.java
> +    @EventListener
@EventListener는 호출시점에 바로 실행됩니다.
@TransactionalEventListener는 커밋이나 롤백이 되는 시점에 이벤트가 실행됩니다. 
주문완료 후 메일을 발송하는 등의 비즈니스 로직 구현시 사용하면 좋을 것 같습니다!

2022-12-22 18:42 UTC, aksgudwns commented
피드백 빠르게 해주셔서 감사합니다!

말씀주신 내용 고민해보고 반영해보았습니다.
부족한 부분 있다면 커멘트 부탁드리겠습니다!

감사합니다.

2022-12-23 05:54 UTC, heowc approved these changes
피드백 반영 감사합니다 👍 

다시 DSM로 확인해보니 순환하는 모습이 보이지 않는 것 같습니다 💯
다음 단계를 진행해주세요~

2022-12-23 05:54 UTC, merged