Step2
next-step/jwp-refactoring pull request #762
Opened 2022-12-20 20:09 UTC by diqksrk

acceptance의 코드가 얼마나 유효한지를 생각해보았습니다. 처음 개발하거나 리팩토링할때는 필요하지만, Service를 만들고 Service에서 검증이 대부분 이루어지기에 더는 테스트로써의 가치가 없다고 생각하였습니다. 왜냐면 다시 또 개발을 한다면 서비스 뿐만 아니라 Acceptance까지 수정해야 하니까 시간이 배로 늘어날거라 생각해서요. 그래서 해당 테스트를 정리했습니다. 일단 맞는지 아닌지는 잘 모르겠지만, 제 생각은 그랬습니다. 좋은 의견 주시면 도움이 될것 같습니다.

2022-12-21 10:36 UTC, seokhongkim commented
> acceptance의 코드가 얼마나 유효한지를 생각해보았습니다. 처음 개발하거나 리팩토링할때는 필요하지만, Service를 만들고 Service에서 검증이 대부분 이루어지기에 더는 테스트로써의 가치가 없다고 생각하였습니다. 왜냐면 다시 또 개발을 한다면 서비스 뿐만 아니라 Acceptance까지 수정해야 하니까 시간이 배로 늘어날거라 생각해서요. 그래서 해당 테스트를 정리했습니다. 일단 맞는지 아닌지는 잘 모르겠지만, 제 생각은 그랬습니다. 좋은 의견 주시면 도움이 될것 같습니다.

민준님. 먼저, 코멘트 남겨주신 내용에 대해 제 생각 먼저 말씀 드립니다.
* 인수 테스트는 내부 구현과는 무관하게 사용자 관점에서의 기능 또는 시나리오를 중심으로 테스트를 작성한다고 생각합니다. 따라서 제품의 스펙이 달라지는 것이 아니라면, 코드의 구현이 변경되더라도 테스트를 수정할 일이 없어야 한다고 생각합니다.
* 코드를 변경하는 과정에서 인수 테스트의 변경이 발생했다면, 인수 테스트를 작성할 때 mock 을 사용했거나, 사용자 스토리 기반으로 시스템의 행위를 검증하는 것이 아닌 구현을 검증하셨을 가능성이 있어 보입니다.
* 말씀하신 것처럼 개발을 완료한 이후에 단위 테스트 또는 통합 테스트가 충분히 있어서 인수 테스트의 효용성이 떨어지는 것처럼 느껴질 수 있습니다. 다만, 시스템이 정말 변하지 않는 경우, 즉 기능의 변경은 물론 리팩터링도 없을 때에만 말씀하신 상황이 유효할 것 같기도 합니다. 조금이라도 기능이 추가되거나 변경이 발생할 때, 기존의 인수 테스트가 잘 동작한다면, 이는 코드 변경이 기존 서비스에 영향이 없다는 것을 나타내므로 의미가 있다고 생각합니다.

2022-12-21 11:25 UTC, seokhongkim requested changes
민준님, 2단계 미션 잘 진행해주셨습니다. 👍
단위 테스트를 작성하며 비즈니스 로직을 서비스에서 도메인으로 잘 옮겨주셨네요.
코멘트 남긴 내용 확인 부탁드립니다. 🙏

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +public class MenuGroupService {
메서드를 추가할 때 `@Transactional` 설정을 누락하는 상황을 방지하기 위해 클래스에도 `@Transactional` 을 디폴트 값으로 설정해보면 어떨까요?

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +    public MenuGroupResponse create(final MenuGroupRequest request) {
서비스의 인자와 반환 타입으로 DTO를 사용하신 이유가 있을까요?

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/dto/MenuProductRequest.java
> +                .findFirst().get();
기존에는 주문하려는 상품이 없을 때 `IllegalArgumentException`이 발생했는데, 현재는 다른 예외가 발생할 것 같네요!

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +    public void validatePrice() {
이 메서드도 생성자에서 호출해서 검증이 필요할 수 있겠네요!

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +        menu.create(allMenuProducts);
`Menu`에 `MenuProduct`가 반드시 필요한 값이라면, 생성자에서 받도록 변경해보시면 좋겠습니다.
그럼 생성할 때 필요한 밸리데이션도 생성자에서 모두 처리할 수 있을 것 같습니다.

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        return MenuResponse.list(menuRepository.findAll());
전체 메뉴를 조회하면 N+1 쿼리가 발생할 것 같아요.
fetch join 을 사용하거나, hibernate batch size 를 이용해서 N+1 쿼리를 방지할 수 있는 방법을 학습해보고 적용하시면 좋겠습니다. :)

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/order/dto/OrderRequest.java
> +        order.order(items);
여기도 `orderLineItems`가 필수 값이라면 생성자에서 인자로 받고, 밸리데이션도 생성자에서 처리해보시면 좋겠습니다.
`Menu`가 없는 경우에 발생하는 예외도 `IllegalArgumentException`에서 다른 예외로 변경된 것으로 보이네요!

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        return OrderResponse.list(orderRepository.findAll());
여기도 N+1 쿼리가 발생하겠네요!

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/product/dto/ProductResponse.java
> +    public static List<ProductResponse> list(List<Product> products) {
`ProductResponse.list(products)`를 호출하면 타입을 변경하는군요.
`list`라는 이름만 봤을 때 타입이 변경된다는 사실을 알기 어려운 것 같은데, 민준님이 보시기에는 어떤가요?

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        this.orderRepository = orderRepository;
`order` 패키지에서 `table` 패키지로 의존성이 있는데, `table` 패키지에서 `order` 패키지로도 의존성이 발생하네요.
패키지간의 순환 의존 관계를 제거해보시면 좋겠습니다.

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +    public void checkOrderTableIsEmpty() {
민준님, 메서드 배치는 어떤 순서로 하시나요? :)

2022-12-21 11:25 UTC, seokhongkim commented on src/main/java/kitchenpos/table/domain/OrderTableRepository.java
> +    List<OrderTable> findAllByIdIn(List<Long> orderTableIds);
선언된 메서드 두 개 모두 사용하지 않는 것 같아요. 사용하지 않는 코드는 제거해보시면 좋겠습니다.

2022-12-21 11:25 UTC, seokhongkim commented on src/test/java/kitchenpos/acceptance/MenuAcceptanceTest.java
>  public class MenuAcceptanceTest extends AcceptanceTest {
테스트가 하나도 없는 클래스를 남겨놓으신 이유가 있을까요? 삭제해도 괜찮을 것 같습니다.

2022-12-21 11:25 UTC, seokhongkim commented on src/test/java/kitchenpos/menu/domain/MenuProductTest.java
> +}
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요.
파일 마지막의 newline 은 무슨 역할을 하는지 학습해보신 후, IDE 설정을 통해 휴먼 에러를 방지해보시면 좋겠습니다.

2022-12-21 11:25 UTC, seokhongkim commented on src/test/java/kitchenpos/menu/domain/MenuProductTest.java
> +class MenuProductTest {
꼼꼼한 단위 테스트 작성 좋습니다. 👍 
단위 테스트로 변경하시면서 일부 도메인 로직에 대한 테스트가 누락된 것 같아요.
브랜치 테스트 커버리지를 확인해보신 후 누락된 테스트도 추가로 작성해보시면 좋겠습니다.

2022-12-23 02:51 UTC, diqksrk commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +    public MenuGroupResponse create(final MenuGroupRequest request) {
Entity가 아닌 domain을 쓴 이유를 물어보시는거라면, 두가지 이유가 있다고 생각합니다.
1. Entity의 모든 변수가 외부에서 주입받는건 아니라고 생각했습니다. 예를 들어서, id는 내부적인 값일수도 있고 create에서는 전달받지 않는 변수입니다. 그래서 해당 사항들을 고려해서 명확하게 나누고 싶었습니다.
2. 반환 타입도 마찬가지입니다. Entity의 모든정보가 아닌 필요한 정보들을 반환하고 싶었고, 그러기 위해서 물론 @JsonIgnore같은 어노테이션을 사용해도 되지만 이는 어떤 사이드 이펙트를 후에 초래할지도 모릅니다. 그래서 DTO를 사용하였습니다.

2022-12-23 02:52 UTC, diqksrk commented on src/main/java/kitchenpos/menu/dto/MenuProductRequest.java
> +                .findFirst().get();
확인하겠습니다 ~

2022-12-23 03:38 UTC, diqksrk commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +    public void checkOrderTableIsEmpty() {
음. 일단 크게 나누어서 다음과 같은 규칙을 따릅니다.
1. 맨 상단에는 생성자 위치
2. 하단에는 public메소드 위치 -> 상단 public 메소드안에 있는 private 메소드 -> 다른 public 메소드 순서로 합니다 !

2022-12-23 03:38 UTC, diqksrk commented on src/main/java/kitchenpos/table/domain/OrderTableRepository.java
> +    List<OrderTable> findAllByIdIn(List<Long> orderTableIds);
넵넵 알겠습니다

2022-12-23 03:38 UTC, diqksrk commented on src/test/java/kitchenpos/acceptance/MenuAcceptanceTest.java
>  public class MenuAcceptanceTest extends AcceptanceTest {
넵 알겠습니다 !

2022-12-23 03:38 UTC, diqksrk commented on src/test/java/kitchenpos/menu/domain/MenuProductTest.java
> +}
설정 찾아보겠습니다 !

2022-12-23 03:38 UTC, diqksrk commented on src/test/java/kitchenpos/menu/domain/MenuProductTest.java
> +class MenuProductTest {
넵 커버리지 확인하겠습니다 !

2022-12-23 05:05 UTC, diqksrk commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +        menu.create(allMenuProducts);
물론 하신말씀도 맞지만, 제가 생성자를 이용하지 않았던건 다음과 같은 이유에서 였습니다.
1. Menu Product를 만들기 위해서는 Menu가 필요합니다. 따라서 미리 Menu를 생성해서 MenuProduct를만들고 만들어진 MenuProduct를 적용했습니다.
2. 그렇지 않다면, MenuProductRequest를 Menu에 인자로 전달해야 하는데, 이는 하위 layer가 상위 layer의 정보를 알고 있는거고 이는 의존성 역전 현상이 발생한다고 생각하기에 위와 같은 로직을 생각했던 겁니다 !

2022-12-23 05:05 UTC, diqksrk commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        return MenuResponse.list(menuRepository.findAll());
넵넵 Batch Size 이용해보겠습니다 !

2022-12-23 05:09 UTC, diqksrk commented on src/main/java/kitchenpos/order/dto/OrderRequest.java
> +        order.order(items);
넵넵 예외 처리해줘야 겠네요 !

2022-12-23 05:09 UTC, diqksrk commented on src/main/java/kitchenpos/order/application/OrderService.java
> +        return OrderResponse.list(orderRepository.findAll());
넵넵

2022-12-23 05:12 UTC, diqksrk commented on src/main/java/kitchenpos/product/dto/ProductResponse.java
> +    public static List<ProductResponse> list(List<Product> products) {
ProductResponse객체의 list 메소드이기 때문에, 저는 ProductResponse라고 인지할거라고 생각했는데. 아닐수도 있겠네요.
메소드명을 좀더 명확하게 수정하겠습니다 !

2022-12-23 05:24 UTC, diqksrk commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        this.orderRepository = orderRepository;
음... 말씀하신 내용을 깊게 생각해보았는데, 서로간의 의존성은 로직상으로 뗄수가 없다고 생각했습니다.
그래서 생각한게, Order 도메인으로 Table도메인 내용들이 들어가야 한다고 생각했고 그렇게 수정했습니다 !

2022-12-23 13:02 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +    public MenuGroupResponse create(final MenuGroupRequest request) {
DTO와 엔티티 또는 도메인간의 변환을 컨트롤러에서 하는 방법도 있을 것 같아서, 서비스에서도 DTO를 사용하신 이유가 궁금했습니다. :)
말씀해주신 이유가 충분히 이해가 되네요.

현재는 프리젠테이션 레이어가 하나지만, 추후 다양한 프리젠테이션 레이어가 추가되면서 각 프리젠테이션 레이어에서 사용하는 DTO의 형태가 다를 경우 이를 서비스 레이어에서 제공하는 것이 맞을지도 고민해보시면 좋겠습니다. :)
예를 들면, 현재는 API만 있지만, 화면을 내려줄 때 서버사이드 렌더링을 위해 데이터를 포함한다거나, 배치, 이벤트 컨슈머 등이 추가되는 경우 이들은 프리젠테이션 레이어가 될 수 있습니다.

2022-12-23 13:05 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/dto/MenuRequest.java
> +        menu.create(allMenuProducts);
말씀하신 내용도 이해가 되네요.
`MenuProduct`를 만들기 위해서 `Menu`가 필요한 것처럼, `Menu`를 만들기 위해서 `MenuProduct`가 필요하다면 순서의 문제인 것 같기도 하네요.
`Menu`를 먼저 만들고 `MenuProduct`를 전달하신 순서를 변경하면, `MenuProduct`를 먼저 만들고 `Menu`에게 `MenuProduct`를 전달한 후, `Menu`에서 `MenuProduct`와 관계를 맺는 방법도 있을 것 같습니다. :)

2022-12-23 13:13 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        this.orderRepository = orderRepository;
양방향으로 의존관계가 필요할 때 사용할 수 있는 방법으로, 아래와 같은 방법도 있으니 다음 단계에서 고민해보셔도 좋겠습니다.
* `order` 패키지에서는 `ordertable` 패키지에 있는 서비스를 사용함
* `ordertable`에서 `order`의 기능이 필요한 경우, 이를 인터페이스로 `ordertable` 패키지에 추가함
  * `order` 패키지에서 `ordertable` 패키지에 있는 인터페이스를 구현한 서비스를 만듦
  * 위에서 만든 서비스를 빈으로 `ordertable` 패키지에서 주입받음
```java
public interface InterfaceInOrderTable {
  void doSomething();
}

@Service
public class ImplementationInOrder implement InterfaceInOrderTable {

  @Override
  public void doSomething() {
    // do something.
  }
}
```

잘 아시겠지만, 위와 같은 방법을 통해 의존관계를 역전(`ordertable` -> `order`로 발생하는 의존을 역방향으로 변경함)시킬 수 있고, 관련해서 SOLID 원칙의 DIP와 연결됩니다. :)

2022-12-23 13:19 UTC, seokhongkim commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +        if (Objects.isNull(price) || price.compareTo(BigDecimal.ZERO) < 0) {
`menuProducts.getTotalPrice()`와 비교하는 검증을 제거하신 이유가 있을까요?

2022-12-23 13:19 UTC, seokhongkim commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        this.orderRepository = orderRepository;
패키지를 한 곳으로 모으더라도, 각 도메인 객체(`Order`, `OrderTable`, `TableGroup`), 그리고 이와 관련된 서비스는 패키지 내에서도 가능하면 의존성을 한 방향으로 관리하시는 것이 좋습니다.

2022-12-23 13:20 UTC, seokhongkim approved these changes
민준님, 2단계 미션 코멘트 잘 반영해주셨습니다. 👍 
2단계 PR 머지하겠습니다.
수정해주신 코드, 남겨주신 코멘트에 대해 코멘트 추가로 남겼습니다. 이 부분은 다음 단계 미션 진행하실 때 참고 부탁드립니다.
3단계 미션에서 뵙겠습니다. 😀

2022-12-23 13:20 UTC, merged