🚀 1단계 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #763
Opened 2022-12-21 09:07 UTC by withbeth

잘 부탁드립니다 :)

2022-12-22 02:48 UTC, mskangg requested changes
안녕하세요 종은님!
이번 미션의 리뷰를 맡게된 강민수입니다. 🙇
요구사항 정리 및 Business Object 테스트코드 작성하신 부분 잘하셨어요!
다만, API 테스트코드나 통합테스트코드를 작성하지 않았네요 😥
리팩토링을 진행하다보면 서비스 레이어가 변경되는일이 잦다보니 기껏 보호한 테스트코드가 깨지는일이 발생합니다.
그렇기에 end-to-end 테스트코드의 보호를 받는게 안전합니다! 😄
추가작성부탁드리고 재요청 기다릴게요!! 🔥

2022-12-22 07:48 UTC, withbeth commented
E2E 테스트 코드 있는편이 더욱 안전하게 리팩토링 가능할 것 같네요 :)
개선해보겠습니다

2022-12-23 17:42 UTC, withbeth commented
안녕하세요 리뷰어님
컨트롤러 테스트와 인수테스트추가작성했습니다.

2022-12-23 18:14 UTC, mskangg approved these changes
피드백 반영 정말 고생하셨습니다! 👏
인수테스트에 API 테스트까지,, 👍 
이제 리팩토링하는데에 있어 거침없이 진행해도 테스트코드가 보호해주어 안전하겠네요 😄
그럼 다음 단계 진행해주세요! 🔥

2022-12-23 18:14 UTC, mskangg commented on README.md
> +    - [x] TableGroup
👍

2022-12-23 18:15 UTC, merged