🚀 3단계 - 의존성 리팩터링
next-step/jwp-refactoring pull request #769
Opened 2022-12-22 03:43 UTC by chosundeveloper

2022-12-23 09:16 UTC, shared-moon requested changes
요한님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
미션 요구사항이 아직 조금 미비된 부분이 있는 것 같아 리뷰 재요청 부탁드립니다!

2022-12-23 09:16 UTC, shared-moon commented on src/main/java/kitchenpos/menu/domain/MenuValidator.java
> +public class MenuValidator {
👍

2022-12-23 09:16 UTC, shared-moon commented on src/main/java/kitchenpos/table/application/TableService.java
> +import kitchenpos.order.domain.Order;
OrderService와 TableService가 아직 강하게 결합되어있는 것 같아요! 추상화를 통해 결합도를 낮춰볼 수 있지 않을까요 ?

2022-12-23 12:23 UTC, chosundeveloper commented on src/main/java/kitchenpos/table/application/TableService.java
> +import kitchenpos.order.domain.Order;
Order 의존성을 줄이는 방식으로 수정했어요~

2022-12-24 06:20 UTC, shared-moon approved these changes
요한님 안녕하세요!
피드백 반영 잘 진행 해 주셨네요 :)
이번 미션은 머지 하도록 하겠습니다!
고생 많으셨어요 :)

2022-12-24 06:20 UTC, merged