🚀 4단계 - 멀티 모듈 적용 PR
next-step/jwp-refactoring pull request #778
Opened 2022-12-23 08:33 UTC by seogineer

의존성 리팩토링을 제대로 하지 않아서 4단계 진행하면서 추가로 의존성 리팩토링을 진행했습니다. ㄷㄷ
통합 테스트 코드는 제대로 작동하지 않아서 제거했습니다.

2022-12-24 05:58 UTC, joojimin requested changes
미션진행 고생하셨습니다 도경님~
한가지 코멘트 남겼는데 확인하시구 리뷰 재요청 부탁드려요~

2022-12-24 05:58 UTC, joojimin commented on src/test/java/kitchenpos/table/ui/TableRestControllerTest.java
> -public class TableRestControllerTest extends BaseTest {
해당 테스트는 인수테스트들 인데요! 적어주신것처럼 동작안해서 삭제하게되면 테스트로 코드를 보호하여 리팩토링한다는 의도에 맞지않는 것 같아요~
해당 테스트가 정상동작되게 수정부탁드립니다~

2022-12-24 08:12 UTC, seogineer commented on src/test/java/kitchenpos/table/ui/TableRestControllerTest.java
> -public class TableRestControllerTest extends BaseTest {
꺾이지 않는 마음이 중요하군요.
어제 그렇게 힘들게 하더니 결국 해결했습니다. 헥헥...

2022-12-25 01:39 UTC, joojimin approved these changes
미션진행 고생하셨습니다 도경님~!

2022-12-25 01:39 UTC, merged