Feature/separate module
next-step/jwp-refactoring pull request #84
Opened 2021-01-25 15:23 UTC by lazy-moon

4단계 - multi module 적용 과제 제출합니다

모듈은 레이어별로 구성할까 하다가
사실 이번 과제에서 레이어별 구성은 별 의미가 없을 것 같아서 .. ( 계층 간 의존성은 딱히 문제 될 게 없기 때문에 )
컨텍스트 범위를 조금 널널하게 잡아서 common/ ui / table / order / menu 로 구성 해 봤습니다.

저번 과제에서 마지막으로 피드백 주신 링크도 잘 읽어 보았구요, 회사에서 이번에 설계한 프로젝트가 좀 그런 모양새로 되어 있어서 (잘 못 이해한건진 모르겠지만 ㅎㅎ) 뭔가 괜히 검증받은 기분같고 그러네요 :)

이런거 열심히 생각하다가 이렇게 용어까지 정의돼있고 하는거 나중에 발견하면 뭔가 허탈하기도 하고 사람 생각하는게 다 똑같은가 싶기도 하고 ㅎㅎ

아무튼, 이번 과제 진행간에는 저번에 말씀하셨던 TableGroup 쪽에서 OrderRepository를 직접 참조하는 부분을 좀 손 대 봤습니다. 마지막 피드백 주신 내용이 만약 어그리거트 별로 모듈이 분리된다면? 어플리케이션이 분리된다면? 이라는 질문을 주셨는데, 그 질문을 한번 반영 해 보려고 일부러 이렇게 나눈 것도 있습니다 ㅎㅎ

제 의견으로는, 일단 OrderRepository를 직접 참조하는 부분은 문제가 안된다고 생각합니다. (아마 이걸 지적하신건 아니라고 생각하긴 하지만!) 그 후에, 모듈의 분리, 어플리케이션의 분리에 대해서 고민 해 보자면 ..
모듈 단위로 분리되는 지점부터는 역시 의존성 사이클을 신경써야 한다고 생각합니다. 사용할 수 있는 건 최대한 사용하고, 끊어낼 수 있는건 최대한 끊어내고 .. 이번 과제로 제출 한 모듈은 약간 그런 생각을 반영 해 봤는데, 어떻게 보이려나 모르겠네요 ㅎㅎ ( order가 menu와 table에 의존하고 menu와 table의 기능을 사용 하지만, table과 menu는 order를 모르니 자체적으로 해결하는..)

어플리케이션 단위로 분리되는 시점에서는 .. 글세요 그때부터는 외부 요인에 따라 경우의 수가 너무 많아서, 그때그때 상황에 맞게 대처하는게 답이라고 생각이 드네요. 물론 그때도 모듈 단위로 분리 했을 때 처럼 의존성은 끊어놔야겠지만.

order의 도메인에서도 아직 결합도를 낮출 수 있다고 생각하긴 합니다. id 기준으로 연관관계를 끊어서 약한 결합을 유지하는 방법을 사용 할 수 있긴 한데.. 이번 과제에서는 거기까진 반영하지 않아도 되지 않을까 하여 스킵했습니다. 😅 

그럼, 마지막 리뷰 잘 부탁드립니다 :)

2021-01-26 15:57 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-01-26 15:57 UTC, kyucumber commented on build.gradle
>  }
이건 미션 내용과는 크게 관련이 없을 것 같은데.

`plugins block`을 제거하고 `buildscript block`으로 변경하신 이유가 있을까요?
최근 나오는 Gradle 문서들을 보면 `plugins`를 조금 더 권장하는 추세인 것 같아서요.

2021-01-26 15:57 UTC, kyucumber commented on build.gradle
> +project(':kitchenpos-table') {
레이어별로 나누었을거라고 생각했는데, Aggregate 단위로 나누어서 모듈을 분리해주셨군요 👍

2021-01-26 15:57 UTC, kyucumber commented on build.gradle
> +    dependencies {
```
제 의견으로는, 일단 OrderRepository를 직접 참조하는 부분은 문제가 안된다고 생각합니다. (아마 이걸 지적하신건 아니라고 생각하긴 하지만!) 그 후에, 모듈의 분리, 어플리케이션의 분리에 대해서 고민 해 보자면 ..
모듈 단위로 분리되는 지점부터는 역시 의존성 사이클을 신경써야 한다고 생각합니다. 사용할 수 있는 건 최대한 사용하고, 끊어낼 수 있는건 최대한 끊어내고 .. 이번 과제로 제출 한 모듈은 약간 그런 생각을 반영 해 봤는데, 어떻게 보이려나 모르겠네요 ㅎㅎ ( order가 menu와 table에 의존하고 menu와 table의 기능을 사용 하지만, table과 menu는 order를 모르니 자체적으로 해결하는..)

어플리케이션 단위로 분리되는 시점에서는 .. 글세요 그때부터는 외부 요인에 따라 경우의 수가 너무 많아서, 그때그때 상황에 맞게 대처하는게 답이라고 생각이 드네요. 물론 그때도 모듈 단위로 분리 했을 때 처럼 의존성은 끊어놔야겠지만.
```

말씀하신대로 OrderRepository를 직접 참조하는 부분은 크게 문제가 되진 않을것 같아요.
서로 반대편 쪽 패키지의 데이터들을 참조하면서 일부 사이클이 생길수도 있겠지만..

어플리케이션 분리에 대해 질문을 남긴 이유는 Anti Corruption Layer를 하나 더 두는 경우에 어플리케이션이 분리되었을 때 어떤 식으로 리팩토링이 일어날 수 있는지 고민해보시면 좋을 것 같아서 해당 질문을 남겨드렸었습니다.

Anti Corruption Layer를 두기 위해 인터페이스를 정의해둘테고 분리된 어플리케이션 서버로 api를 쏘거나 하는 구현체를 하나 더 만들면 깔끔하게 분리할 수 있지 않을까? 요런 내용을 말씀드리고 싶었어요.

2021-01-26 15:57 UTC, kyucumber commented on kitchenpos-table/src/main/java/kitchenpos/support/OrderSupport.java
> +public interface OrderSupport {
인터페이스에 `@Component`어노테이션을 붙이고 Bean으로 정의하신 이유가 있을까요?

실제 사용되지 않을 것 같은데 `OrderSupportImpl`만 빈으로 정의되어도 괜찮지 않을까요?

2021-01-26 15:57 UTC, kyucumber commented on kitchenpos-order/src/main/java/kitchenpos/order/support/OrderSupportImpl.java
> +        return false;
Anti Corruption Layer를 의도하고 만들어주신 것 같아요.

예상했던 `OrderTable` 관련 빈도 없고, 구현이 안된 것으로 보이는데 이 부분도 의도하신걸까요?

2021-01-26 16:05 UTC, lazy-moon commented on build.gradle
>  }
아 그렇군요, 큰 의미는 없었습니다. plugins로 해도 되긴 했었는데, 뭔가 subproject에 plugin을 또 달아두니 괜히 중복같은 느낌이 들어서 과거에 스프링프레임워크 스크립트 만들어논거 참고했었어요 ㅎㅎ.. 정보 감사합니다 :)

2021-01-26 16:06 UTC, lazy-moon commented on build.gradle
> +    dependencies {
넵 그런 목적이실거같아서 요렇게 진행 해 봤습니다 ㅎㅎ 잘 알아들은거 같아 다행이네요 :)

2021-01-26 16:14 UTC, lazy-moon commented on kitchenpos-table/src/main/java/kitchenpos/support/OrderSupport.java
> +public interface OrderSupport {
모듈로 나눈 이상 table은 order가 없더라도 제 기능을 해야 한다고 생각합니다. 현재도 Table Service 테스트 시에는 MockBean으로 정의해서 문제가 없지만 혹시 다른 경우 (현재는 TableRequestTest가 되겠네요)에 스프링 컨테이너를 사용하게 된다면 문제가 생길 것으로 보입니다. 물론, 테스트를 MockBean을 이용하거나 스프링 컨테이너를 사용하지 않으면 별 상관은 없지만 그냥 테스트에만 국한 된 내용은 아니기에 .. 아무튼 의도는 이렇습니다 ㅎㅎ

2021-01-26 16:14 UTC, lazy-moon commented on kitchenpos-order/src/main/java/kitchenpos/order/support/OrderSupportImpl.java
> +        return false;
세상에 .. 아뇨 이건 전혀 의도한게 아닙니다 .. 말도 안되는걸 누락을 시켜버렸네요 죄송합니다 ㄷㄷ..;

2021-01-26 17:03 UTC, lazy-moon commented on kitchenpos-table/src/main/java/kitchenpos/support/OrderSupport.java
> +public interface OrderSupport {
세상에 ㅋㅋ 저번에 분명 테스트 다 돌려서 성공하는걸 보고 푸시했다고 생각했는데 뭔가 착오가 있었나봅니다. 인터페이스에 컴포넌트 달아놓고 테스트 통과하길래 오 인터페이스에 달아도 따로 프록시 생성해주는 방법이 있는건가 하고 좀 뿌듯해하고 있었는데 큰 착각이었네요 ㄷㄷ 의도는 위에 쓴 것과 같았습니다만 방법이 잘못됐었네요 ㅋㅋ 부끄럽게 .. 아무튼 해당 내용 반영해서 다시 푸시하겠습니다 ㅎㅎ;

2021-01-26 17:21 UTC, lazy-moon commented on build.gradle
> +    dependencies {
왠지 두루뭉술 넘어간 느낌이 살짝 들어서, 어플리케이션 단위 분리에 대해서는 모듈 단위 분리에서 이미 손상 방지를 위해 만들어 둔 인터페이스가 있을 테니 그 구현체만 바꾸면 얼마든지 달라지는 시스템에 대응할 수 있다고 생각합니다. ( 코멘트 적으신 걸 그대로 읽은 느낌이 들지만 정말 이렇게 생각하고 있었어요 ㅎㅎ) 경우의 수가 너무 많다는 언급을 한 것은, 그 외부 시스템이 어떻게 구성되느냐에 따라 그 구현체의 세부 로직이 여러 가지로 나뉠 수 있다는 얘기를 하고 싶었습니다. ㅎㅎ 뭔가 서로 같은얘길 하는데 굉장히 길게 얘기 한 기분이네요 ! 이런 토론시간 되게 좋아해서.. ㅎㅎ 코멘트로만 주고받는게 아쉽네요 :)

2021-01-27 11:49 UTC, kyucumber commented
여러가지로 토의하고, 교류하려고 생각한 이런 저런 내용들을 많이 공유해드렸던 것 같은데 도움이 되셨을지 잘 모르겠네요

마지막 미션까지 진행하시느라 고생 많으셨습니다. 👍

2021-01-27 11:49 UTC, kyucumber approved these changes
레거시 코드 리팩토링 미션 마지막까지 구현하시느라 고생 많으셨어요~

다음 단계 진행을 위해 머지합니다. 🙏

2021-01-27 11:49 UTC, kyucumber commented on kitchenpos-order/src/main/java/kitchenpos/order/support/OrderSupportImpl.java
> +}
👍 제가 생각했던 요 부분이 없어서 저도 당황했네요 ㅎㅎ 고생하셨습니다~

2021-01-27 11:49 UTC, merged