"레거시 코드 리팩터링" 3단계 - 양방향을 단방향
next-step/jwp-refactoring pull request #85
Opened 2021-01-25 16:11 UTC by orgojy

안녕하세요. 김규남 리뷰어님!
"우테캠 Pro" 수강생 안이민입니다.
PR 요청 드립니다.

이번 양방향을 단방향으로 적용한 부분은 다음과 같습니다.
- Service Layer에서 양방향 참조 제거(이 과정에서 Order와 OrderTable 간 양방향 참조를 제거하기 위해서 OrderTableAdapter를 도메인 서비스의 구현체로 추가하였습니다.)
- 각 Layer는 Controller -> Service -> Domain 순으로 참조하게 만들었구요.
- 양방향 참조가 된 Entity의 @OneToMany를 제거해서 다대일 단방향으로 끊어내고 서비스 레이어에서 데이터를 직접 핸들링하는 방식으로 구현하였습니다.

이번 리뷰도 잘부탁드립니다.

2021-01-26 16:21 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겼으니 확인 부탁드립니다.

2021-01-26 16:21 UTC, kyucumber commented on src/main/java/kitchenpos/ordertable/domain/OrderTableDomainService.java
> +public interface OrderTableDomainService {
Anti Corruption Layer의 역할을 위한 인터페이스로 보이는데 맞을까요?

`OrderTableDomainService`라는 인터페이스 이름은 "도메인 서비스"를 염두에 두고 만드신거라고 생각됩니다.


도메인 서비스의 역할과 사용 경우를 아래 간단하게 정의해봤어요, 이 부분도 개인마다 생각하는 부분은 다르겠지만..

- 도메인 서비스는 도메인 계층에 있는 비즈니스 로직을 응용 계층으로 넘어가는것을 막아주는 역할을 한다.
- 다루는 데이터가 비즈니스 규칙에 가까운 경우 도메인 서비스를 사용한다.

도메인의 손상 방지를 위한 레이어가 비즈니스 규칙을 다루거나, 도메인 계층의 비즈니스 로직이 응용 계층으로 넘어가는것을 막아주는 역할을 한다고 볼 수 있을까요?

저는 개인적으로는 손상 방지 레이어와 도메인 서비스는 구분이 되어야 할 것 같다고 생각해요.
정답은 없으니 여기에 생각하셨던 의견 편하게 남겨주시면 감사하겠습니다. 🙏

2021-01-26 16:21 UTC, kyucumber commented on src/main/java/kitchenpos/ordertable/domain/OrderTable.java
> -    @OneToMany(mappedBy = "orderTable")
👍 연관관계를 적절히 잘 끊어주셨습니다.

지금처럼 다대 일로 유지해도 좋지만 만약 양방향 참조가 되지 않으면  서비스 레이어에서 데이터를 직접 핸들링할 때 로직이 너무 지저분해지거나 구현이 매끄럽지 못한 경우가 있습니다.

그런 경우에 저는 직접적인 연관관계는 맺지 않지만 id를 통해 참조하도록 합니다.
객체지향적으로 양방향 참조가 되지 않으면서도 서로의 정보를 가지고 있을 수 있어서 저는 아이디로 참조를 하는걸 선호하는 편입니다.

간단하게 예시를 한번 작성해봤어요, 많이 사용하는 패턴이라 이미 잘 알고 계실 것 같지만 도움이 되실까봐 남겨두었습니다.

```java
class Order {
    @ManyToOne
    @JoinColumn(name = "order_table_id")
    private OrderTable orderTable;
}

class OrderTable {
    List<Long> orderIds = new ArraysLit<>();
}
```

2021-01-26 16:21 UTC, kyucumber commented on src/main/java/kitchenpos/order/application/OrderService.java
> +import kitchenpos.ordertable.infra.OrderTableAdapter;
`OrderTableAdapter`가 현재 `ordertable.infra` 패키지에 위치하고 있네요.

저는 이 어댑터의 경우 `order` 하위에 있는게 조금 더 손상 방지 레이어의 역할을 잘 수행할 수 있을 것 같은데 어떻게 생각하시나요?

지금은 `OrderTableRepository`와의 의존성은 끊었지만 `ordertable.infra.OrderTableAdapter`간의 의존성이 생겨 기존과 큰 차이가 없을 것 같아요.

2021-01-26 16:21 UTC, kyucumber commented on README.md
> +    - OrderTable-Order Service Layer에서 OrderTableAdapter를 통해서 양방향 참조 제거
몇가지 코멘트 남겨드리긴 했는데 고민 많이 하시고 꼼꼼하게 잘 작성해주신 것 같습니다 👍 

```
Controller -> Service -> Domain Layer 별 방향성 단방향  
```

위와 같은 코멘트를 남겨주셔서 고민해볼만한 질문 하나 드리자면

`Response`와 같은 Dto를 Service 레이어에서 참조하고 반환하거나 하는 부분은 어떻게 생각하시나요?
다들 큰 고민 없이 `Service`에 Dto를 위치시키시고 있는데  `Controller`에서 데이터를 주고받기 위한 Dto 또한 바깥 레이어의 참조로 볼 수 있지 않을까요?

2021-01-26 16:21 UTC, kyucumber commented on src/main/java/kitchenpos/common/config/H2ServerConfiguration.java
> +    public Server h2TcpServer() throws SQLException {
이건 어떤 연유로 추가하신건지 궁금하네요

IntelliJ에서 H2 연결을 위해 정의하신걸까요?

2021-01-26 17:07 UTC, orgojy commented on src/main/java/kitchenpos/ordertable/domain/OrderTableDomainService.java
> +public interface OrderTableDomainService {
네. 손상 방지 레이어 패턴 맞습니다.
양방향 참조를 어떻게 끊어야할지 솔루션이 생각이 안나더라구요.
돌아다니다 보니까 다른 분들 코멘트 부분을 봐서 개념을 찾다보니 다음 링크를 보고 적용해봤습니다. [링크](https://github.com/iamkyu/TIL/blob/master/books/summary/ddd-start.md#9-%EB%8F%84%EB%A9%94%EC%9D%B8-%EB%AA%A8%EB%8D%B8%EA%B3%BC-bounded-context)
제가 적절하게 적용한 것 같지는 않아보이네요. ㅎㅎ

말씀하신대로 DDD에서 도메인 서비스에 대한 정의는 김규남 리뷰어님께서 말씀해주신 역할과 사용 경우라고 동감합니다.
제가 생각하는 도메인 서비스를 말씀드리면,
DDD에서 서비스는 크게 두 가지 `도메인 서비스` 와 `애플리케이션 서비스` 입니다.
두루 보면 도메인에서 해결할 수 있는 부분을 도메인 서비스로 가지고 나와서 구현되는 경우가 많아서 도메인 서비스는 최대한 지양하는 방향으로 설계하는 것이 적절하다고 생각하구요.
`도메인 서비스`는 도메인을 다루는데 있어서 VO나 Entity 자체에서 구현되기 어색한 부분의 로직에 적용되어야한다고 생각합니다.
또한 도메인 계층에 있는 비즈니스 로직이 응용 계층으로 넘어가지 않게 하는 것이라고 생각합니다.

**결론을 말씀드리면,**
제가 생각한 손상 방지 레이어는 어쨌든 해당 OrderTable 도메인 내에서 전달되는 데이터이기 때문에 해당 패키지 내에서 인터페이스로 규약을 정의하는게 맞다고 생각했구요.
도메인 엔티티 내부에서 정의할 수 없고 접근할 수 없는 형태의 외부 요청을 응용 계층까지 가지 않고 처리할 수 있는 하나의 `도메인 서비스`의 역할이라고 생각했습니다.
이름이 변경이 필요하다 생각하시면 변경토록 하겠습니다. 좋은 코치해주셔서 감사합니다.👍

2021-01-26 17:08 UTC, orgojy commented on src/main/java/kitchenpos/common/config/H2ServerConfiguration.java
> +    public Server h2TcpServer() throws SQLException {
네. 말씀이 맞습니다. 😄 
intellij H2 연결을 해서 테이블간의 관계를 Visualization해서 쉽게 보려는 의도에서 셋팅했습니다.
console로만 보는건 좀 한계가 있는 것 같다고 판단했습니다!

2021-01-26 17:10 UTC, orgojy commented on src/main/java/kitchenpos/ordertable/domain/OrderTable.java
> -    @OneToMany(mappedBy = "orderTable")
네 공유 감사드립니다! 적용해보도록 하겠습니다. ㅎㅎ

2021-01-26 17:16 UTC, orgojy commented on src/main/java/kitchenpos/order/application/OrderService.java
> +import kitchenpos.ordertable.infra.OrderTableAdapter;
네 이 부분 적극 찬성합니다.
제가 처음주신 코멘트 부분에서 손상 방지 레이어도 도메인 서비스로 볼 수 있다라고 생각한다고 말씀드렸었는데요.
그렇게 바라보니까 해당 도메인 영역 안에 있어야지 않을까 생각해서 ordertable.infra쪽으로 구현했는데요.
저도 개인적으로는 패키지 의존 방향으로 봤을땐 말씀하신 부분처럼 order가 적절하다고 생각합니다.
이동하도록 하겠습니다. 👍

2021-01-26 17:39 UTC, orgojy commented on README.md
> +    - OrderTable-Order Service Layer에서 OrderTableAdapter를 통해서 양방향 참조 제거
ㅎㅎ 정곡이네요... 🙇 
저도 아무 생각 없이 DTO의 존재를 망각하고 있었습니다.
네 말씀하신대로 Response DTO는 Service 관점에서는 사실 관심 있는 부분은 아니라고 생각합니다.
Request DTO와 Service의 관계를 생각하면,
Service는 사실 Request DTO에 관심 없고, 관심있는 부분은 사실 어떤 파라미터가 들어와서 Service가 처리해야하는지겠네요.
마찬가지로 Response DTO와 Service의 관계를 생각하면,
Service는 Response DTO에 관심 없고, 관심있는 부분은 Service가 로직을 처리한 데이터이겠네요.

결론적으로는 말씀하신대로 구현하면, DTO가 Service layer에서 참조가 되지 않겠네요.
구현 방안을 고민해보겠습니다. 👍

2021-01-27 11:50 UTC, kyucumber commented on src/main/java/kitchenpos/ordertable/domain/OrderTableDomainService.java
> +public interface OrderTableDomainService {
엇 변경하실 필요는 없습니다~ 의견 공유해주셔서 감사합니다. 🙏

2021-01-27 11:53 UTC, kyucumber commented on README.md
> +    - OrderTable-Order Service Layer에서 OrderTableAdapter를 통해서 양방향 참조 제거
이부분은 다들 알고 있지만 어쩔 수 없이 지금 하신것 처럼 많이 구현하는 것 같아요.

저는 Controller와 Service 레이어 자체 모듈을 다르게 해서 Dto 참조를 하지 않고 구현한적이 있는데.. 레이어 별로 데이터 전달을 위한 객체를 따로 만들거나 하면서 굉장히 코드 작성이 번거로워졌던 기억이 있네요 ㅎㅎ

말씀해주신 내용을 보다보니 그런 부분은 어떻게 고민하고 계신지 궁금해서 코멘트 남겨봤습니다. 🙏

2021-01-27 11:54 UTC, kyucumber approved these changes
3단계 미션 진행하시느라 고생 많으셨습니다.

다음 단계 진행을 위해 머지할게요~

2021-01-27 11:54 UTC, merged