4단계 - multi module 적용
next-step/jwp-refactoring pull request #95
Opened 2021-01-26 16:24 UTC by byungkyu-ju

마지막 단계 리뷰도 잘 부탁드립니다!

2021-01-26 16:25 UTC, byungkyu-ju commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +		savedMenu.addMenuProducts(menuProducts);
https://github.com/next-step/jwp-refactoring/pull/86#discussion_r564433932
개선했습니다!

2021-01-27 09:27 UTC, wbluke requested changes
멀티모듈 잘 적용해주셨습니다 ㅎㅎ
관련해서 코멘트 남겨봤는데 한번 확인 부탁드려요 🙂

2021-01-27 09:27 UTC, wbluke commented on settings.gradle
> +include 'kitchenpos-web'
- 각 모듈에 build.gradle이 없는 것 같아요.
- 지금 상태에서 혹시 전체 테스트 수행되실까요? :)

2021-01-27 09:27 UTC, wbluke commented on kitchenpos-domain/src/main/java/kitchenpos/menu/domain/MenuProduct.java
>  package kitchenpos.menu.domain;
각 모듈별로 별도의 root 패키지를 가져가는 것이 좋습니다.
예를 들어 `kitchenpos.domain` `kitchenpos.web` 요렇게요 ㅎㅎ
모듈이 나눠진 것처럼 보여도 실제로는 하나의 코드로 합쳐져서 인식되기 때문에 Bean 스캔을 하거나 할 때 문제가 생기지 않으려면 패키지를 구분하는 것이 좋습니다!

2021-01-27 09:38 UTC, byungkyu-ju commented on kitchenpos-domain/build.gradle
> +}
https://github.com/next-step/jwp-refactoring/pull/95#discussion_r565149073
build.gradle 파일이 전부 누락됐었네요 😢

2021-01-27 09:39 UTC, byungkyu-ju commented on kitchenpos-domain/src/main/java/kitchenpos/domain/menu/domain/Menu.java
> +package kitchenpos.domain.menu.domain;
https://github.com/next-step/jwp-refactoring/pull/95#discussion_r565151551
모듈간 root 패키지를 분리하였습니다!

2021-01-27 09:57 UTC, wbluke approved these changes
빠른 피드백 반영 감사합니다 👍 
마지막 미션 고생 많으셨어요 🙂

2021-01-27 09:57 UTC, merged