Step1 1단계 - 테스트를 통한 코드 보호
next-step/jwp-refactoring pull request #98
Opened 2021-01-27 03:32 UTC by carry1126

리뷰요청드립니다.

2021-01-27 17:27 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-01-27 17:27 UTC, kyucumber commented on README.md
> +  **주문상태가 완료(COMPLETION)이면 수정할 수 없음**
"주문 상태"에는 어떠한 상태들이 있는지도 따로 아래에 정리해주시면 어떨까요?

용어 사전 항목에 적어도 좋을 것 같네요.

2021-01-27 17:27 UTC, kyucumber commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +}
미션의 내용과는 별개지만 참고가 되실까봐 내용 첨부합니다.

파일의 끝에 newline이 포함해주시면 좋을 것 같아요
POSIX 표준에 맞지 않기도 하고 작업 시 newline을 붙이는데 다른 작업자가 붙이지 않는 경우 불필요한 file change가 생기기도 합니다.

저 같은 경우 IntelliJ에서 newline을 자동으로 추가하는 설정을 사용하고 있습니다.

![image](https://user-images.githubusercontent.com/34656258/81493539-030f0d80-92dc-11ea-8129-756ca65b99cc.png)

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-01-27 17:27 UTC, kyucumber commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        when(menuGroupDao.findAll()).thenReturn(Arrays.asList(menuGroup));
Given, When, Then으로 나누어 테스트를 작성하는 것과 관련해서 문서를 하나 남겼으니 참고해보시면 좋을 것 같아요.

https://velog.io/@pop8682/%EB%B2%88%EC%97%AD-Given-When-Then-martin-fowler

추가로 위 방식대로 하는 경우 기존 `Mockito.when`과 조금 안맞는 부분이 있어 저는 아래 패키지의 `given`, `then`을 사용하고 있습니다.

```
org.mockito.BDDMockito.given
org.mockito.BDDMockito.then
```

따로 변경해주실 필요는 없어요, 기존 방식대로 작성하셔도 됩니다.

2021-01-27 17:27 UTC, kyucumber commented on src/test/java/kitchenpos/ui/MenuRestControllerTest.java
> +class MenuRestControllerTest {
작성할 테스트가 많으셨을텐데 Controller layer까지 테스트를 잘 작성해주셨네요 👍

2021-01-27 21:12 UTC, carry1126 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +}
유용한 정보 감사합니다.

2021-01-28 10:41 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

다음 단계 진행을 위해 머지할게요

2021-01-28 10:41 UTC, merged

2021-01-28 11:23 UTC, carry1126 commented
감사합니다.